import type { Category } from './types'

export const AIRWAY: Category = {
  id: 'airway',
  name: 'Airway, Respiration & Ventilation',
  short: 'Airway',
  desc: 'Upper and lower airway, ventilation parameters, respiratory failure, advanced airway management, capnography, pediatric airway.',
  color: '#06b6d4',
  icon: 'lung',
  flashcards: [
    { id: 'aw-fc-1', front: 'Adult tidal volume target for BVM or mechanical ventilation', back: '6 to 8 mL/kg IDEAL body weight (NOT actual weight, especially in obesity). Using actual weight overinflates lungs and causes barotrauma. Overventilation also raises intrathoracic pressure, kills venous return, and tanks cardiac output. In arrest this collapses coronary perfusion pressure and ROSC odds drop hard.' },
    { id: 'aw-fc-2', front: 'Pediatric uncuffed and cuffed ETT size formulas', back: 'Uncuffed: (Age/4) + 4 mm. Cuffed: (Age/4) + 3.5 mm. Depth at lip = tube ID x 3 (so a 4.0 sits at 12 cm at the lip). Newborn term: 3.0 to 3.5 uncuffed. Use Broselow tape when in doubt; eyeballing pediatric tubes under stress is unreliable.' },
    { id: 'aw-fc-3', front: 'Adult cardiac arrest ventilation rate WITH advanced airway', back: '1 breath every 6 seconds (10/min) with continuous compressions, no pauses. Faster than this drops venous return through increased intrathoracic pressure and tanks coronary perfusion pressure. Mental cue: squeeze, wait wait wait wait wait, squeeze.' },
    { id: 'aw-fc-4', front: 'BVM rate by patient type (with pulse, no advanced airway)', back: 'Adult: 1 breath every 5 to 6 seconds (10 to 12/min). Peds (1y to puberty): 1 every 2 to 3 seconds (20 to 30/min). Neonate post-resuscitation: 40 to 60/min. Each breath should be over 1 second with just enough volume to see chest rise. No more.' },
    { id: 'aw-fc-5', front: 'Type I vs Type II respiratory failure', back: 'Type I (hypoxemic): PaO2 under 60 with normal/low PaCO2. Failure of OXYGENATION. Causes: ARDS, pneumonia, PE, pulmonary edema. Type II (hypercapnic): PaCO2 over 50 with respiratory acidosis. Failure of VENTILATION. Causes: COPD, opioid OD, neuromuscular disease, severe asthma late stage. Mixed Type I+II is common in severe disease.' },
    { id: 'aw-fc-6', front: 'Normal ETCO2 range and what each deviation means', back: 'Normal: 35 to 45 mmHg. Below 35: hyperventilating, low cardiac output, hypoperfusion, PE. In CPR, ETCO2 under 10 means compressions are inadequate. Sudden rise to over 35-40 in arrest = ROSC. Above 45: hypoventilation, hypermetabolism (sepsis, fever, MH), bicarb administration, tourniquet release.' },
    { id: 'aw-fc-7', front: 'Capnography waveform: shark fin shape', back: 'Sloped, fin-shaped waveform = bronchospasm (asthma, COPD exacerbation, anaphylaxis). The slope is alveolar gas exiting unevenly through narrowed airways. The steeper the slope, the worse the obstruction. Treatment is bronchodilators, not airway maneuvers. Watch the shape flatten as your beta-agonist works.' },
    { id: 'aw-fc-8', front: 'Sellick maneuver - when and how', back: 'Cricoid pressure during intubation to occlude esophagus and reduce aspiration risk. Current evidence is mixed and many systems have dropped it because it can worsen view and cause esophageal injury. If used: 10N pre-induction, 30N once unconscious, release if intubation difficult or active vomiting. AHA does NOT recommend during cardiac arrest.' },
    { id: 'aw-fc-9', front: 'Three-step difficult airway recognition (LEMON)', back: 'Look externally (trauma, beard, big tongue, small mandible). Evaluate 3-3-2 (3 fingers in mouth, 3 fingers chin to hyoid, 2 fingers hyoid to thyroid). Mallampati class. Obstruction (stridor, swelling, foreign body). Neck mobility. Failing any of these = backup plan ready before you push paralytic.' },
    { id: 'aw-fc-10', front: 'Apneic oxygenation', back: 'High-flow O2 via NC at 15 L/min during intubation attempt extends safe apnea time by 1 to 6+ minutes. Critical for obese, pregnant, septic, or critically ill patients who desat fast. Set it up BEFORE first attempt. Costs nothing, buys time, no downside. Every RSI should have it.' },
    { id: 'aw-fc-11', front: 'Why 100% O2 in COPD is NOT the killer most people think', back: 'The classic teaching that high O2 knocks out hypoxic drive is oversimplified. The real mechanisms are V/Q mismatch worsening (Haldane effect releasing CO2 from hemoglobin) and absorption atelectasis. In real life: titrate to SpO2 88 to 92% in known CO2 retainers. But never withhold O2 from a hypoxic COPD patient. Hypoxia kills faster than hypercapnia.' },
    { id: 'aw-fc-12', front: 'CPAP indications and contraindications', back: 'Indications: CHF/pulmonary edema (best evidence), COPD exacerbation, asthma, pneumonia with hypoxia, drowning. Contraindications: apnea, decreased LOC unable to protect airway, vomiting/active GI bleed, facial trauma, pneumothorax, hypotension (CPAP drops preload). Start 5 cmH2O, titrate up to 10. Watch BP.' },
    { id: 'aw-fc-13', front: 'Tension pneumothorax - why decompress fast', back: 'Air enters pleural space, cant escape, pressure builds, mediastinum shifts, kinks great vessels, venous return falls, obstructive shock. Signs: severe dyspnea, tracheal deviation (LATE), JVD, absent breath sounds one side, hypotension, hyper-resonance. Decompress 2nd ICS midclavicular OR 4th/5th ICS anterior axillary (newer evidence prefers lateral).' },
    { id: 'aw-fc-14', front: 'Needle decompression - adult length and landmarks', back: 'Use at least 8 cm (3.25 inch) catheter for adults. Standard 5 cm catheter fails in 30 to 50% of adults due to chest wall thickness. Insert OVER the third rib (avoid neurovascular bundle on inferior rib edge). Listen for air rush, leave catheter in, follow with chest tube.' },
    { id: 'aw-fc-15', front: 'Cricothyrotomy indications', back: 'Cant intubate, cant oxygenate (CICO scenario). Failed BVM, failed supraglottic, failed ETT. Causes: angioedema, massive facial trauma, anaphylaxis with airway swelling, severe burns. Find membrane between thyroid and cricoid cartilage, vertical skin incision, horizontal stab through membrane, dilate, tube in. Surgical airway is a last resort but you cannot hesitate when youre there.' },
    { id: 'aw-fc-16', front: 'Asthma severe vs life-threatening - clinical distinction', back: 'Severe: cant complete sentences, RR over 30, HR over 120, peak flow under 50% predicted, accessory muscle use. Life-threatening: silent chest (no air movement = no wheeze), exhaustion, altered LOC, cyanosis, paradoxical chest movement, bradycardia, hypotension. Silent chest is NOT good - it means they cannot move air at all.' },
    { id: 'aw-fc-17', front: 'Asthma drug ladder', back: 'Albuterol nebulizer (or MDI with spacer if mild). Add ipratropium for moderate-severe (combined gives more bronchodilation than either alone). IM epinephrine 0.3 to 0.5 mg if life-threatening or no response. IV magnesium 2 g over 20 min. Steroids early (methylprednisolone 125 mg IV). Avoid intubation unless absolutely necessary - these patients are extremely hard to ventilate.' },
    { id: 'aw-fc-18', front: 'Ventilator-induced auto-PEEP in obstructive disease', back: 'In severe asthma/COPD, exhalation is too slow; next breath stacks on top before air fully escapes. Pressure climbs, BP drops, can cause PEA arrest. Fix: DISCONNECT BVM/vent, push on chest to force exhalation, then ventilate at slow rate (6 to 8/min) with long expiratory time (1:4 or 1:5 I:E ratio). Permissive hypercapnia is OK.' },
    { id: 'aw-fc-19', front: 'Pulmonary embolism classic triad and reality', back: 'Classic: dyspnea, chest pain, hemoptysis (only present in 20%). Reality: most PE patients have nonspecific symptoms - sudden dyspnea, tachycardia, tachypnea, low-grade fever, syncope. Massive PE: hypotension, RV strain, hypoxia not responding to O2. Wells score helps stratify. A normal SpO2 does NOT rule out PE.' },
    { id: 'aw-fc-20', front: 'Croup vs epiglottitis - never miss this', back: 'Croup (viral, 6mo-3yr): barking cough, gradual onset, low fever, child looks ok, drooling rare. Treat with cool mist, dexamethasone, racemic epi if stridor at rest. Epiglottitis (bacterial, any age): tripod position, drooling, NO COUGH, high fever, toxic appearance, sudden onset. NEVER agitate. Do not look in throat. Do not start IV. Get to OR for controlled airway. Missing epiglottitis is fatal in minutes.' },
    { id: 'aw-fc-21', front: 'Anaphylaxis airway - when to act', back: 'IM epi 0.3 to 0.5 mg (0.01 mg/kg peds) lateral thigh, repeat every 5 to 15 min. Stridor, voice change, lip/tongue swelling = airway closing. Intubate EARLY - once swollen, you may not be able to. Have surgical airway gear out. Adjuncts (antihistamines, steroids) are SECOND LINE. Epi is the only thing that saves lives in anaphylaxis.' },
    { id: 'aw-fc-22', front: 'Drowning physiology and management', back: 'Aspiration causes surfactant washout and pulmonary edema (both fresh and salt water - old teaching about hypotonic vs hypertonic differences is largely irrelevant clinically). Hypoxia is the killer. Even minor aspiration can cause delayed pulmonary edema 4 to 8 hours later. Asymptomatic drowning patients still need observation. CPAP early if any respiratory symptoms.' },
    { id: 'aw-fc-23', front: 'Foreign body airway obstruction - pediatric', back: 'Conscious infant under 1: 5 back blows + 5 chest thrusts, repeat. NO abdominal thrusts (liver injury risk). Conscious child over 1: abdominal thrusts. Unconscious: CPR with airway look on each ventilation, blind finger sweep contraindicated, only remove visible objects. Common culprits: hot dogs, grapes, nuts, balloons, small toys. Magnets and button batteries are esophageal emergencies.' },
    { id: 'aw-fc-24', front: 'Smoke inhalation - three concerns', back: '1) Thermal injury (upper airway swelling, watch for soot in nares, singed nasal hairs, hoarseness). 2) Carbon monoxide (treat with 100% O2; SpO2 reads falsely normal). 3) Cyanide (from burning plastics; treat with hydroxocobalamin). Intubate EARLY if any airway burn signs - the swelling will close the airway in hours.' },
    { id: 'aw-fc-25', front: 'Pulse oximetry - where it lies', back: 'False high readings: CO poisoning (reads 100% in dead patients), methemoglobinemia (caps around 85%), nail polish, severe anemia. False low: motion, cold extremities, hypotension/poor perfusion, dark skin tone (FDA warning). Always correlate with clinical picture and ETCO2. SpO2 of 95% in a CO patient means nothing.' },
    { id: 'aw-fc-26', front: 'Oxygen device delivery percentages', back: 'NC 1-6 L/min: 24-44%. Simple mask 6-10: 35-60%. NRB 10-15: 60-90%. Venturi: 24, 28, 31, 35, 40% (precise FiO2). High-flow NC (HFNC): up to 60 L/min and FiO2 close to 100%, also provides PEEP-like effect. CPAP: 100% if set up that way. BVM with reservoir at 15 L/min: near 100%.' },
    { id: 'aw-fc-27', front: 'Tracheal deviation: which way means what', back: 'Tension pneumothorax: trachea pushed AWAY from affected side (tension is pushing things). Massive atelectasis or pneumonectomy: trachea pulled TOWARD affected side (collapsed lung pulls things in). Tracheal deviation in tension pneumo is a LATE sign - by the time you see it the patient is crashing. Decompress on suspicion, not on tracheal deviation.' },
    { id: 'aw-fc-28', front: 'PEEP - what it does and what it costs', back: 'Positive end-expiratory pressure keeps alveoli open at end of exhalation. Improves oxygenation in ARDS, pulmonary edema, atelectasis. Cost: increased intrathoracic pressure decreases venous return and cardiac output. In hypovolemic patients PEEP can drop BP fast. Standard: 5 cmH2O. Titrate up for refractory hypoxia, watch hemodynamics.' },
    { id: 'aw-fc-29', front: 'Capnography in cardiac arrest - three uses', back: '1) ETT confirmation: any waveform with CO2 = tube is in trachea (not esophagus). 2) CPR quality: ETCO2 under 10 = compressions are not generating perfusion. Push harder, push faster. 3) ROSC detection: sudden rise to 35-45 = circulation returned, often before pulse is palpable. Watch the number, dont stop CPR until you see it sustained.' },
    { id: 'aw-fc-30', front: 'Suctioning - adult and pediatric limits', back: 'Adult: max 15 seconds suction time, 100 to 150 mmHg pressure. Peds: 10 seconds, 80 to 100 mmHg. Infant: 5 seconds, 60 to 80 mmHg. Insert without suction, withdraw with suction. Hyperoxygenate before. Vagal stimulation can drop HR especially in peds - be ready to stop if bradycardic. Closed suction systems preferred for vented patients.' },
  ],
  scenarios: [
    {
      id: 'aw-1',
      q: 'A 68 y/o male, 130 kg actual / 80 kg ideal body weight, in cardiac arrest. ETT placed. Partner is bagging at 14/min with full-bag squeezes (~800 mL each). ETCO2 reads 9 mmHg. After 4 minutes still no ROSC. What is the MOST important immediate change?',
      choices: [
        { text: 'Increase epi to 2 mg every 3-5 min', exp: 'Wrong dose. Standard arrest epi is 1 mg every 3-5 min. Doubling does not improve outcomes and causes worse post-ROSC dysfunction. The problem here is mechanical (bad ventilation/perfusion), not pharmacologic.' },
        { text: 'Slow ventilation to 10/min and reduce volume to ~500 mL (6-7 mL/kg IBW)', exp: 'Correct. Hyperventilation at 14/min with full bags is destroying coronary perfusion pressure (low ETCO2 reflects this). Slowing rate and using IBW-based volume restores venous return. Volume should be based on IDEAL body weight, not actual.' },
        { text: 'Switch to manual chest compression only, stop ventilations', exp: 'Wrong. Once an advanced airway is in, asynchronous ventilation at 10/min with continuous compressions is standard. Stopping ventilation entirely abandons oxygenation. The fix is correcting rate and volume, not eliminating ventilation.' },
        { text: 'Push 1 amp sodium bicarbonate', exp: 'Wrong reflex. Routine bicarb in arrest is not recommended. Only consider for known hyperkalemia, TCA overdose, or prolonged downtime with documented severe acidosis. Will not fix the ventilation problem.' },
      ],
      correct: 1,
      exp: 'Hyperventilation in arrest is one of the most lethal common errors. Rate must be 10/min, volume must be IBW-based (6-8 mL/kg). The low ETCO2 of 9 is the smoking gun - coronary perfusion is gone.',
      difficulty: 8,
      tags: ['arrest', 'ventilation', 'capnography'],
    },
    {
      id: 'aw-2',
      q: 'A 4-year-old presents with stridor, drooling, refusing to lie down, tripod posture, fever 103.4°F, no cough. Mom says symptoms started 6 hours ago. SpO2 92% on room air. What is your IMMEDIATE priority?',
      choices: [
        { text: 'Establish IV, give racemic epinephrine and dexamethasone', exp: 'Dangerous. Starting an IV agitates the child and can precipitate complete airway obstruction. Racemic epi/dex is for croup (gradual onset, barking cough, no drooling) - this presentation screams epiglottitis.' },
        { text: 'Examine the oropharynx with a tongue depressor', exp: 'Could kill the patient. Stimulating the pharynx in epiglottitis can cause laryngospasm and complete obstruction. Visual exam is contraindicated until controlled airway management is ready.' },
        { text: 'Keep child calm in mother\'s lap, give blow-by O2, transport upright to facility with surgical/anesthesia capability, alert OR', exp: 'Correct. This is epiglottitis until proven otherwise. Anything that agitates the child can close the airway. Definitive management is controlled intubation in OR. Pre-hospital priority is non-agitation transport.' },
        { text: 'Place patient supine and prepare for needle cricothyrotomy', exp: 'Wrong. Supine positioning worsens airway patency in epiglottitis. Needle cric is a last resort if total obstruction occurs, not a primary intervention. The patient is still moving air.' },
      ],
      correct: 2,
      exp: 'Classic epiglottitis: rapid onset, drooling, NO cough, tripod, toxic appearance. The most important intervention is "do nothing that agitates them." Definitive airway is in OR with anesthesia ready for surgical backup.',
      difficulty: 9,
      tags: ['pediatric', 'airway-emergency'],
    },
    {
      id: 'aw-3',
      q: 'A 24 y/o asthmatic on a vent post-intubation. Set: AC 16, Vt 500, PEEP 5, FiO2 100%. Suddenly: BP drops 88/42 from 120/70, peak airway pressure spiked from 28 to 52, SpO2 falling. Breath sounds equal but distant bilaterally. ETCO2 trending up. What is the MOST likely cause and intervention?',
      choices: [
        { text: 'Tension pneumothorax - needle decompress right side', exp: 'Possible but unlikely with EQUAL breath sounds and no tracheal deviation. Tension pneumo would give unilateral findings. Without lateralizing signs, this is not the leading diagnosis.' },
        { text: 'Auto-PEEP from breath stacking - DISCONNECT vent, decompress chest manually, slow rate', exp: 'Correct. Severe asthmatic on vent with rising pressures, hypotension, equal breath sounds = breath stacking. Disconnect, push on chest to exhale, then slow vent rate (6-8/min) with long expiratory time. Permissive hypercapnia OK.' },
        { text: 'ETT migration into right mainstem - pull back 2 cm', exp: 'Right mainstem causes UNEQUAL breath sounds (diminished on left). Equal sounds rule this out. Also would not typically spike pressures this fast.' },
        { text: 'Pulmonary embolism - start heparin', exp: 'PE possible in any hypoxic patient but does not explain peak pressure spike. Mechanical ventilation problems present like this; PE presents differently. And starting heparin is not the move in an unstable trapped-air situation.' },
      ],
      correct: 1,
      exp: 'Asthmatics on vents are at huge risk for breath stacking. Air enters faster than it exits, intrathoracic pressure climbs, BP crashes. The intervention is counterintuitive: DISCONNECT them, manually exhale them, then ventilate slowly with long expiratory time.',
      difficulty: 9,
      tags: ['asthma', 'vent-management'],
    },
    {
      id: 'aw-4',
      q: 'A 55 y/o with 80 pack-year COPD, dyspneic, RR 32, accessory muscle use, SpO2 79% on room air. Tripod, audible wheeze. You start NRB at 15 L/min. After 5 min SpO2 is 96% but he is now sleepy and harder to arouse. What is your NEXT move?',
      choices: [
        { text: 'Continue NRB and reassure - SpO2 is improved, he\'s just tired', exp: 'Wrong. The change in mental status is a warning sign of CO2 narcosis from over-oxygenation worsening V/Q mismatch and Haldane effect. Continuing without intervention risks respiratory arrest.' },
        { text: 'Remove all oxygen and let him drive his breathing', exp: 'Dangerous. Hypoxia kills faster than hypercapnia. Stripping O2 in a previously hypoxic patient causes rebound desaturation and may arrest him. The fix is titrating, not removing.' },
        { text: 'Switch to nasal cannula 2-4 L/min targeting SpO2 88-92%, prepare BiPAP/CPAP', exp: 'Correct. Titrate O2 to 88-92% in CO2 retainers. The mental status change is a tell that he is heading toward narcosis. NIV is the next-step intervention before he loses his airway.' },
        { text: 'RSI and intubate now', exp: 'Premature. NIV (CPAP/BiPAP) prevents intubation in COPD exacerbations the majority of the time when applied early. Skipping NIV jumps too far up the ladder. Intubated COPD patients are very hard to ventilate.' },
      ],
      correct: 2,
      exp: 'Classic CO2 narcosis from over-oxygenation. Target 88-92%, NOT 100%. NIV is first-line for COPD exacerbation in patients still able to protect airway. Intubation is a last resort.',
      difficulty: 8,
      tags: ['copd', 'oxygen-titration'],
    },
    {
      id: 'aw-5',
      q: 'You arrive at a house fire victim, 35 y/o female pulled from smoke-filled bedroom 4 minutes ago. AAOx3, RR 22, SpO2 99% on room air. Visible soot on face, no facial burns, no singed nasal hair. She is hoarse and complains of throat tightness. What is your MOST appropriate action?',
      choices: [
        { text: 'Reassure and transport with NRB - vitals are stable, no obvious airway compromise', exp: 'Misses the boat. Hoarseness + throat tightness + soot + smoke exposure = upper airway thermal injury developing. Stable vitals now do not rule out impending closure. Waiting will lose the airway.' },
        { text: 'Aggressive intubation now while you can still see landmarks', exp: 'Correct. Hoarseness is the early sign that vocal cord/upper airway swelling is starting. Wait, and the airway becomes anatomically impossible to intubate. Tube it now while you have a target. Have surgical airway gear out.' },
        { text: 'Apply CPAP at 10 cmH2O', exp: 'Wrong. CPAP does nothing for upper airway thermal injury and may worsen edema. CPAP treats lower airway problems (CHF, COPD). This is an upper airway thermal injury demanding definitive airway control.' },
        { text: 'Give IV methylprednisolone and observe', exp: 'Steroids do not work fast enough for evolving airway swelling and have weak evidence in inhalation injury. Definitive airway management does not wait for steroids to maybe work.' },
      ],
      correct: 1,
      exp: 'Inhalation injury rule: when in doubt, tube early. Hoarseness, stridor, voice change, soot in airway, facial burns = airway is closing. The window from "can intubate" to "cannot intubate" can be 30 minutes.',
      difficulty: 9,
      tags: ['burns', 'inhalation-injury'],
    },
    {
      id: 'aw-6',
      q: 'Pediatric arrest: 3 y/o, weight ~14 kg, asystole. ETT placed, confirmed with capnography. Compressor is doing 100/min. Partner asks what ventilation rate to use. Best answer:',
      choices: [
        { text: '20-30 breaths/min asynchronous', exp: 'That is the rate for a child WITH a pulse and no advanced airway. In arrest with advanced airway, the rate is different.' },
        { text: '8-10 breaths/min asynchronous (1 every 6-8 sec)', exp: 'Correct per 2020+ AHA guidelines. Updated peds in-arrest with advanced airway is 1 breath every 2-3 seconds for some sources, but AHA Pediatric Advanced Life Support 2020 update raised it: in pediatric cardiac arrest with advanced airway, 20-30/min is acceptable. HOWEVER for NREMT testing, the older standard of 1 every 6 seconds (10/min) was historically taught as identical to adult - so ALWAYS verify with current guidelines. The lower rate avoids hyperventilation.' },
        { text: '40-60 breaths/min synchronous with compressions', exp: 'That is neonatal post-resuscitation rate. Way too fast for a 3-year-old in arrest - would massively hyperventilate and tank perfusion.' },
        { text: '12 breaths/min synchronized 30:2', exp: 'Synchronized 30:2 is for arrest WITHOUT an advanced airway. Once tube is in, ventilation is asynchronous from compressions.' },
      ],
      correct: 1,
      exp: 'AHA 2020 PALS update: in pediatric cardiac arrest WITH advanced airway, give 1 breath every 2-3 seconds (20-30/min). Older guidance was 1 every 6 seconds (10/min). NREMT may test the older rate. Either way, AVOID hyperventilation - it kills perfusion.',
      difficulty: 9,
      tags: ['pediatric', 'arrest', 'aha-update'],
    },
    {
      id: 'aw-7',
      q: 'You intubate a 70 kg adult. After ETT placement you see a square waveform on capnography reading 12 mmHg. Bilateral chest rise, equal breath sounds, no epigastric sounds. SpO2 92% and dropping. CPR is ongoing. What is the MOST likely explanation?',
      choices: [
        { text: 'Esophageal intubation - pull tube and re-attempt', exp: 'Wrong. A waveform with any CO2 reading confirms tracheal placement. Esophageal would show no waveform or a small initial puff that disappears. Equal breath sounds further support tracheal placement.' },
        { text: 'Tube is correct but compressions are inadequate', exp: 'Correct. Waveform present = tracheal placement confirmed. Low ETCO2 (under 10-15) during arrest indicates poor cardiac output from inadequate compressions. Push deeper, faster, with full recoil. Switch compressors if fatigue.' },
        { text: 'Pulmonary embolism causing dead space ventilation', exp: 'PE does cause low ETCO2 but in arrest the much more likely cause is poor compressions. Always blame compressions first in low ETCO2 during arrest.' },
        { text: 'Hyperventilation', exp: 'Hyperventilation does drop ETCO2 but in arrest with no return of circulation, low ETCO2 reflects no perfusion regardless of rate. The fix is better compressions.' },
      ],
      correct: 1,
      exp: 'During arrest, ETCO2 reflects pulmonary blood flow. Under 10-15 = compressions are not generating output. The tube is fine; the problem is downstream. Improve compression depth/rate/recoil before anything else.',
      difficulty: 8,
      tags: ['capnography', 'cpr-quality'],
    },
    {
      id: 'aw-8',
      q: 'A 40 y/o woman with peanut anaphylaxis. Lip and tongue swelling, hoarse voice, audible stridor at rest, SpO2 91%, BP 76/40, HR 138. You give IM epi 0.3 mg lateral thigh. 3 minutes later: still stridor, SpO2 88%, BP 70/38. What is your priority?',
      choices: [
        { text: 'Repeat IM epi, start IV epi infusion, prepare for difficult intubation', exp: 'Correct. Refractory anaphylaxis requires repeat epi (every 5-15 min, dont wait) and IV epi infusion if still hypotensive. Airway is closing - intubate before it shuts. Have surgical airway gear out. Antihistamines/steroids are second-line and never first.' },
        { text: 'Push IV diphenhydramine 50 mg and methylprednisolone 125 mg', exp: 'These are second-line. They do not save lives in anaphylaxis - epinephrine does. Giving them while patient is crashing wastes time and gives false sense of progress.' },
        { text: 'Apply CPAP at 10 cmH2O for stridor', exp: 'Dangerous. CPAP does not fix upper airway swelling and can worsen the obstruction or cause aspiration. The airway needs definitive control, not positive pressure mask.' },
        { text: 'Wait 5 more minutes for first epi to take effect', exp: 'Wrong. Patient is still in shock with worsening airway. AHA guidance says repeat epi every 5-15 min with no upper limit if still symptomatic. Waiting kills patients.' },
      ],
      correct: 0,
      exp: 'Refractory anaphylaxis: repeat epi, start IV infusion, intubate EARLY. The window from "can intubate" to "cannot intubate" in airway anaphylaxis is small. Antihistamines and steroids are adjuncts, not treatments.',
      difficulty: 9,
      tags: ['anaphylaxis', 'airway-emergency'],
    },
    {
      id: 'aw-9',
      q: 'A trauma patient post-MVC, awake but combative, GCS 11, suspected C-spine injury, blood in airway, RR 8 and shallow. SpO2 84% on NRB. Which airway approach is BEST?',
      choices: [
        { text: 'Nasopharyngeal airway and continue NRB', exp: 'NPA does not protect against aspiration with active blood in airway. Patient is hypoventilating regardless. Inadequate.' },
        { text: 'RSI with in-line C-spine stabilization, video laryngoscopy preferred', exp: 'Correct. Patient cannot protect airway, is hypoventilating, hypoxic, and combative. RSI is the right call. C-spine stabilization (manual in-line, not the collar pulled up tight) preserves alignment. Video scope improves first-pass success in hard airways.' },
        { text: 'Awake fiberoptic intubation', exp: 'Awake FOI requires cooperative patient and time. Combative trauma patient with active bleeding and hypoventilation does not have time for awake technique. Field-impossible in most cases.' },
        { text: 'Cricothyrotomy', exp: 'Surgical airway is for cant intubate cant oxygenate. You havent attempted yet - skipping to cric is over-aggressive. Try RSI with optimal setup first; have cric ready as backup.' },
      ],
      correct: 1,
      exp: 'Hypoventilation, hypoxia, cant protect airway, blood in mouth = need definitive airway now. RSI with manual in-line C-spine stabilization is standard. Video scope when available. Have surgical backup ready.',
      difficulty: 8,
      tags: ['trauma', 'rsi'],
    },
    {
      id: 'aw-10',
      q: 'You tube a patient with hypoxic respiratory failure. Pre-tube SpO2 was 78%. Post-tube SpO2 is 84%. Capnography shows good waveform 38 mmHg. Tube taped at 22 cm, breath sounds equal, no epigastric sounds. What is the MOST appropriate next step?',
      choices: [
        { text: 'Pull tube - bad placement', exp: 'Wrong. Capnography waveform 38 mmHg confirms tracheal placement. Equal breath sounds and no epigastric sounds further confirm. Pulling correctly placed tube is a critical error.' },
        { text: 'Raise PEEP, raise FiO2, recruit alveoli, suction airway, address shunt physiology', exp: 'Correct. Tube is in the right place. Persistent hypoxia post-tube = shunt physiology (alveoli not gas-exchanging). Need PEEP to recruit, FiO2 turned up, suction if mucus plugging, consider lung pathology (ARDS, pneumonia, edema, pneumothorax).' },
        { text: 'Switch to BVM, manually ventilate harder', exp: 'Manual harder bagging causes barotrauma and overdistension. The ventilator/bag is not the problem; the lung is. More force does not fix shunt.' },
        { text: 'Pull tube back 2 cm', exp: 'Tube depth 22 cm is reasonable for adult. Equal breath sounds rule out mainstem. Pulling it without indication risks accidental extubation.' },
      ],
      correct: 1,
      exp: 'Persistent hypoxia after correct intubation usually means shunt physiology. The tube is fine. Treat the lung: PEEP, FiO2, recruit, suction, address underlying disease.',
      difficulty: 8,
      tags: ['post-intubation', 'oxygenation'],
    },
    {
      id: 'aw-11',
      q: 'A 22 y/o female, suspected heroin overdose. RR 4, pinpoint pupils, SpO2 76% on room air, BP 88/50, GCS 6. Track marks visible. Best initial airway management?',
      choices: [
        { text: 'Naloxone 2 mg IV push, then re-evaluate airway', exp: 'Correct. In opioid OD, naloxone reverses the airway/breathing problem at the source. If you can ventilate with BVM and reverse with naloxone, you avoid intubation. Start with airway support during onset (BVM with OPA), give naloxone, watch for respiratory drive return.' },
        { text: 'RSI and intubate immediately', exp: 'Premature. Opioid OD is reversible. Intubating without trying naloxone subjects patient to invasive procedure that can be avoided. Reserve intubation for after failed reversal or aspiration.' },
        { text: 'Apply NRB and observe', exp: 'Inadequate. Patient is hypoventilating (RR 4) and hypoxic. NRB does not increase ventilation. Patient needs assisted ventilation AND reversal.' },
        { text: 'Apply CPAP at 10 cmH2O', exp: 'CPAP requires patient to be ventilating spontaneously and able to protect airway. RR 4 and GCS 6 fails both criteria. Will not work.' },
      ],
      correct: 0,
      exp: 'Opioid OD is one of the few airway problems with a fast reversal. BVM during onset, naloxone, watch for return of breathing. Intubate only if naloxone fails or aspiration occurred. Saves patient an unnecessary tube.',
      difficulty: 7,
      tags: ['overdose', 'naloxone'],
    },
    {
      id: 'aw-12',
      q: 'You are managing a patient on mechanical ventilation. Suddenly the high-pressure alarm sounds. Peak pressure has gone from 24 to 56. SpO2 is dropping. What is the BEST initial assessment approach (DOPE pneumonic order)?',
      choices: [
        { text: 'Disconnect - Oxygen - Position - Equipment', exp: 'Wrong order. The standard is DOPE = Displacement, Obstruction, Pneumothorax, Equipment. The mnemonic targets specific causes in order of frequency.' },
        { text: 'Displacement (tube migrated/dislodged) - Obstruction (mucus, kinking) - Pneumothorax - Equipment failure', exp: 'Correct. DOPE walks you through the four most common causes of sudden vent compromise. Check tube depth and breath sounds (Displacement), suction and check kinks (Obstruction), assess for tension pneumo (Pneumothorax), then check vent/circuit (Equipment).' },
        { text: 'Drugs - Oxygen - Position - Equipment', exp: 'Made-up mnemonic. Drugs do not commonly cause sudden peak pressure rise on the vent.' },
        { text: 'Oxygen - Position - Drugs - ETT check', exp: 'Random ordering. The systematic DOPE approach exists because under stress people skip steps. Use the standard.' },
      ],
      correct: 1,
      exp: 'DOPE: Displacement, Obstruction, Pneumothorax, Equipment. Memorize it. When the vent alarms and you do not know why, run DOPE in order. The first three are patient causes; equipment is last because patient causes are more common and more dangerous.',
      difficulty: 7,
      tags: ['vent-troubleshooting'],
    },
    {
      id: 'aw-13',
      q: 'A 65 y/o post-thoracotomy patient suddenly develops severe dyspnea, tachycardia 138, BP 86/48, JVD, decreased breath sounds on the right, hyper-resonance to percussion, tracheal deviation to LEFT. You suspect tension pneumothorax. Where is your needle decompression target?',
      choices: [
        { text: 'Left side, 2nd ICS midclavicular line', exp: 'Wrong side. Tension pneumo pushes trachea AWAY from affected side. Trachea deviated LEFT means pneumo is on RIGHT. Decompressing the wrong side is catastrophic.' },
        { text: 'Right side, 2nd ICS midclavicular line OR 4th-5th ICS anterior axillary', exp: 'Correct. Tracheal deviation away from affected side localizes tension to right. 2nd ICS MCL is traditional; 4th-5th ICS anterior axillary line has better evidence in adults due to chest wall thickness. Use at least 8 cm catheter.' },
        { text: 'Right side, 5th ICS midaxillary line', exp: 'That is the chest tube site (triangle of safety). Needle decompression is more anterior. The midaxillary spot has more muscle/chest wall thickness which fails more often with shorter needles.' },
        { text: 'Bilateral 2nd ICS MCL', exp: 'Wrong. Tension pneumo is unilateral. Bilateral decompression in absence of bilateral pathology creates iatrogenic pneumothorax on the unaffected side.' },
      ],
      correct: 1,
      exp: 'Trachea deviates AWAY from tension. Decompress on the affected side. 4th-5th ICS anterior axillary is now favored for adults (better chest wall thickness data). Use long catheter (8 cm+).',
      difficulty: 8,
      tags: ['pneumothorax', 'procedure'],
    },
    {
      id: 'aw-14',
      q: 'You are setting up RSI for a 90 kg adult with sepsis-induced respiratory failure. BP 86/52, HR 122, SpO2 91% on NRB. Which induction agent profile is BEST?',
      choices: [
        { text: 'Etomidate 0.3 mg/kg - minimal hemodynamic effect, but causes adrenal suppression', exp: 'Etomidate has the best hemodynamic profile of induction agents and is commonly chosen in shock. The adrenal suppression issue is real but a single dose effect is debated and clinically minor for one-shot RSI.' },
        { text: 'Ketamine 1-2 mg/kg - sympathomimetic, supports BP, bronchodilator', exp: 'Correct. Ketamine releases endogenous catecholamines, supports BP, has bronchodilator effects, makes it ideal for hypotensive septic or asthmatic intubations. Avoid in pure cardiogenic shock if catecholamines are depleted (then it can drop BP), but in sepsis usually preferred.' },
        { text: 'Propofol 1.5-2.5 mg/kg - clean hemodynamics in sepsis', exp: 'Wrong. Propofol drops BP significantly in shock. Causes vasodilation and myocardial depression. Worst choice in sepsis with already low BP.' },
        { text: 'Midazolam 0.1 mg/kg - short acting, safe', exp: 'Inadequate as sole induction agent for RSI. Slow onset (90+ sec), unreliable depth of anesthesia, causes hypotension. Not the move for RSI.' },
      ],
      correct: 1,
      exp: 'Hemodynamic instability + RSI: ketamine (or etomidate at lower dose) preserves BP. Ketamine has the additional benefit of bronchodilation and analgesia. Propofol is the wrong call in shock.',
      difficulty: 8,
      tags: ['rsi', 'pharmacology'],
    },
    {
      id: 'aw-15',
      q: 'A 6-month-old, 7 kg, in respiratory distress with bronchiolitis. RR 70, retractions, SpO2 88% on room air. Which intervention is FIRST line?',
      choices: [
        { text: 'Nebulized albuterol', exp: 'Bronchiolitis (RSV) does not reliably respond to bronchodilators in infants. Most bronchiolitis trials show no benefit. Not first-line.' },
        { text: 'Suctioning nasopharynx, supplemental O2, possibly HFNC', exp: 'Correct. Bronchiolitis is largely an obstruction-from-secretions problem. Suctioning the nose alone often dramatically improves work of breathing. O2 to maintain SpO2 90%+. High-flow nasal cannula is excellent if available - provides flow, low PEEP, and humidification.' },
        { text: 'Nebulized racemic epinephrine', exp: 'Some evidence for transient benefit in moderate-severe but does not reduce admission rates and not first-line. Suction first.' },
        { text: 'IV methylprednisolone', exp: 'Steroids do not work in bronchiolitis. Multiple large trials show no benefit. Different from croup, where steroids do work.' },
      ],
      correct: 1,
      exp: 'Bronchiolitis: suction, O2, HFNC. The classic mistake is treating it like asthma with bronchodilators and steroids - neither works in true bronchiolitis. Most kids do well with supportive care.',
      difficulty: 8,
      tags: ['pediatric', 'bronchiolitis'],
    },
    {
      id: 'aw-16',
      q: 'You arrive at a 28 y/o woman 35 weeks pregnant, in respiratory distress. RR 28, SpO2 89%, HR 110, BP 132/78. Audible wheezing, history of asthma. Which positioning is BEST during transport?',
      choices: [
        { text: 'Supine with legs elevated (Trendelenburg)', exp: 'Wrong. Supine in late pregnancy compresses IVC against vertebral column (aortocaval compression), drops cardiac output, can worsen oxygenation. Trendelenburg adds nothing.' },
        { text: 'Left lateral decubitus or 15-30 degree left tilt', exp: 'Correct. Left tilt offloads IVC compression by gravid uterus, restoring venous return and cardiac output. Critical in any pregnant patient over 20 weeks needing supine procedures (CPR uses manual uterine displacement to the left).' },
        { text: 'Right lateral decubitus', exp: 'Wrong direction. Right tilt does not offload IVC compression - the IVC is on the right side, so right tilt presses gravid uterus harder into it.' },
        { text: 'Prone position', exp: 'Pregnancy + prone is mechanically problematic and potentially dangerous late term. Not a transport position.' },
      ],
      correct: 1,
      exp: 'Late pregnancy: left lateral or left tilt to offload IVC. Affects breathing through cardiac output and venous return. Same principle for pregnant CPR (manual left uterine displacement).',
      difficulty: 7,
      tags: ['obstetric', 'positioning'],
    },
    {
      id: 'aw-17',
      q: 'CPAP at 10 cmH2O on a CHF/pulmonary edema patient. After 5 min: BP drops from 168/96 to 92/52, patient becoming sleepy. SpO2 was 88, now 92. What is your INTERPRETATION and action?',
      choices: [
        { text: 'CPAP is working - BP normalized from hypertensive crisis. Continue.', exp: 'Wrong. The drop is too fast and too low. This is not "fixing" hypertension - this is dropping preload too aggressively. Sleepy with low BP = hypoperfusion.' },
        { text: 'PEEP from CPAP dropped venous return too much. Lower CPAP to 5 cmH2O, reassess', exp: 'Correct. CPAP raises intrathoracic pressure and drops preload, which is desired in CHF (offloads pulmonary congestion). But if it drops cardiac output too much, BP crashes. Lower the pressure or remove CPAP if not tolerated.' },
        { text: 'Patient is having an MI - give nitro and aspirin', exp: 'Possible co-morbidity but the timeline of BP drop matches CPAP application. Address the immediate hemodynamic insult first.' },
        { text: 'Septic shock - start fluids and pressors', exp: 'Wrong context. CHF patient on CPAP with new hypotension immediately after CPAP - the CPAP is the most likely cause.' },
      ],
      correct: 1,
      exp: 'CPAP/PEEP can crash BP in volume-down or preload-dependent patients. The trade-off is real: better oxygenation vs. worse cardiac output. Titrate to find the sweet spot. Lower pressure or remove if hypotensive.',
      difficulty: 8,
      tags: ['cpap', 'chf'],
    },
    {
      id: 'aw-18',
      q: 'A patient with severe COPD, on home O2 2 L/min NC, presents with worsening dyspnea x 3 days. Color: dusky. RR 30, SpO2 81% on home O2. You bump O2 to 4 L/min NC, SpO2 climbs to 89%. Awake, mentating well, complete sentences with effort. Best NEXT intervention?',
      choices: [
        { text: 'Continue 4 L/min NC and transport', exp: 'Patient still working hard, evidence of fatigue, will likely deteriorate without escalation. Transport without NIV gives up the best chance to avoid intubation.' },
        { text: 'Initiate BiPAP at 10/5 cmH2O', exp: 'Correct. BiPAP is first-line for COPD exacerbation in patients alert and able to protect airway. The IPAP/EPAP combo offloads work of breathing and improves CO2 clearance better than CPAP alone. Reduces intubation rate by 50%+.' },
        { text: 'RSI and intubate', exp: 'Premature. NIV trial first. Intubated COPD patients are notoriously hard to ventilate (auto-PEEP, breath stacking) and have high mortality.' },
        { text: 'Switch to NRB at 15 L/min', exp: 'Higher FiO2 alone risks worsening hypercapnia in CO2 retainer without addressing work of breathing. NIV beats NRB in COPD exacerbations.' },
      ],
      correct: 1,
      exp: 'COPD exacerbation + alert + able to protect airway = BiPAP. Better than CPAP for hypercapnia (the dual pressures actively assist ventilation). Cuts intubation rate dramatically.',
      difficulty: 7,
      tags: ['copd', 'niv'],
    },
    {
      id: 'aw-19',
      q: 'A 45 y/o was found unresponsive in a closed garage with a running car. AAOx0, RR 24, HR 110, BP 140/85, SpO2 100% on room air. Skin: cherry red. Best initial airway/breathing management?',
      choices: [
        { text: 'Reassure - SpO2 is 100%, oxygenation is fine', exp: 'Catastrophic error. Pulse oximetry CANNOT distinguish carboxyhemoglobin (CO bound to Hgb) from oxyhemoglobin. SpO2 reads falsely normal in CO poisoning. Patient is profoundly hypoxic at the cellular level.' },
        { text: 'Apply NRB at 15 L/min, transport to facility with hyperbaric chamber', exp: 'Correct. 100% O2 via NRB is first-line for CO poisoning to displace CO from Hgb (cuts half-life from 320 min to 80 min). Severe cases (LOC, neurological signs, pregnancy, ischemic ECG) get hyperbaric O2 (cuts half-life to 23 min).' },
        { text: 'Intubate immediately and ventilate at 100% FiO2', exp: 'Patient is mentating poorly but breathing. Intubation is reasonable for unconscious patients but NRB is the field standard. Save tube for those who cannot protect airway.' },
        { text: 'Nasal cannula at 4 L/min', exp: 'Inadequate FiO2. CO needs maximum O2 to displace it from hemoglobin. NRB at 15 L/min is the minimum standard.' },
      ],
      correct: 1,
      exp: 'CO poisoning: pulse ox lies. Cherry red is a late/post-mortem finding usually. Treat aggressively with 100% O2; transport for hyperbaric in severe cases. Always think CO with closed-space exposure or smoke.',
      difficulty: 8,
      tags: ['toxicology', 'co-poisoning'],
    },
    {
      id: 'aw-20',
      q: 'You are bagging a difficult airway patient via BVM after failed intubation x2. Audible air leak from sides of mask, abdominal distension, SpO2 dropping to 80%. Most appropriate immediate intervention?',
      choices: [
        { text: 'Insert oropharyngeal airway (OPA), use 2-person BVM technique with E-C clamp grip', exp: 'Correct. Loss of seal + abdominal distension = ineffective ventilation, gas going into stomach. OPA opens the airway, 2-person BVM (one for seal, one to bag) gives the best mask-to-face fit. The fix is technique, not jumping to surgical airway.' },
        { text: 'Cricothyrotomy now', exp: 'Premature. You have not optimized BVM. Cric is for cant intubate cant oxygenate AFTER you have tried adjuncts and proper technique. Skipping basics goes against the airway algorithm.' },
        { text: 'Place a supraglottic airway (LMA, iGel, King)', exp: 'Reasonable backup option, but step 1 is optimizing the BVM you are already attempting. SGA is the next step if 2-person BVM still fails.' },
        { text: 'Give more induction agent', exp: 'Wrong direction. Patient is already paralyzed/sedated. Adding more drug does not improve the mechanical problem of mask seal.' },
      ],
      correct: 0,
      exp: 'Failed intubation algorithm: optimize BVM (OPA/NPA, 2-person, E-C clamp), then SGA, then surgical airway. Most "cant ventilate" problems are fixable with technique. Do not skip to surgical airway prematurely.',
      difficulty: 8,
      tags: ['failed-airway', 'algorithm'],
    },
    {
      id: 'aw-21',
      q: 'Capnography shows a sharp upstroke, plateau, downstroke - but the BASELINE is rising above zero (ETCO2 reading 6 between breaths). Most likely cause?',
      choices: [
        { text: 'Patient is rebreathing exhaled CO2 - check expiratory valve, exhausted CO2 absorber, inadequate fresh gas flow', exp: 'Correct. A baseline above 0 means the patient is breathing in CO2 from the previous breath. Common in faulty BVM expiratory valves, broken vent circuits, or in anesthesia circuits with exhausted CO2 absorber. Patient will become hypercapnic if not corrected.' },
        { text: 'Hyperventilation', exp: 'Hyperventilation lowers ETCO2; it does not change baseline. Wrong waveform interpretation.' },
        { text: 'Pulmonary embolism', exp: 'PE drops ETCO2 (dead space increases) but does not raise baseline.' },
        { text: 'Esophageal intubation', exp: 'Esophageal intubation gives no waveform or a small initial puff. Sustained waveform with elevated baseline is a circuit problem.' },
      ],
      correct: 0,
      exp: 'Capnography baseline above 0 = rebreathing. Check valves, circuit, absorber. The waveform morphology tells you exactly what is wrong if you read it.',
      difficulty: 8,
      tags: ['capnography'],
    },
    {
      id: 'aw-22',
      q: 'A 7 y/o, 25 kg, choking on a hot dog. Conscious, gagging, coughing forcefully, able to speak in single words. Stridor present. What is the BEST initial action?',
      choices: [
        { text: 'Immediate abdominal thrusts (Heimlich)', exp: 'Wrong. Heimlich is for COMPLETE obstruction with no air movement. This child is coughing forcefully and speaking - partial obstruction with effective cough. Aggressive intervention can convert partial to complete obstruction.' },
        { text: 'Encourage coughing, position of comfort, transport with continuous monitoring', exp: 'Correct. Effective cough = best tool the body has. Do not interfere unless it becomes ineffective. If cough weakens or speech stops = transition to abdominal thrusts.' },
        { text: 'Blind finger sweep', exp: 'Contraindicated. Blind sweep can push object deeper or cause complete obstruction. Only remove visible objects.' },
        { text: 'Direct laryngoscopy with Magill forceps', exp: 'Reserved for failed BLS measures or unconscious patient. With effective cough you should not be reaching down their airway.' },
      ],
      correct: 1,
      exp: 'Partial vs complete airway obstruction: effective cough = let them cough. Ineffective cough or unconscious = back blows + chest thrusts (infant) or Heimlich (over 1). The most important assessment is "is air moving?"',
      difficulty: 7,
      tags: ['pediatric', 'obstruction'],
    },
    {
      id: 'aw-23',
      q: 'You intubate a 65 y/o male with massive GI bleed and aspiration. Post-tube SpO2 78% on FiO2 100%, PEEP 5. Bilateral coarse crackles. ABG: pH 7.18, PaCO2 52, PaO2 55. What is the BEST ventilator strategy?',
      choices: [
        { text: 'Increase FiO2 to maximum, increase rate to blow off CO2', exp: 'Already at 100% FiO2. Increasing rate worsens auto-PEEP and barotrauma. The fix is recruitment, not more aggression with rate.' },
        { text: 'ARDS-style: low Vt 6 mL/kg IBW, increase PEEP to 10-15, accept permissive hypercapnia', exp: 'Correct. Aspiration causes ARDS-like physiology. Lung-protective ventilation: low tidal volume (6 mL/kg IBW), higher PEEP to recruit alveoli, accept some hypercapnia (pH > 7.20 OK). Reduces barotrauma and improves outcomes.' },
        { text: 'Vt 10 mL/kg, PEEP 0, FiO2 100%', exp: 'Wrong on every count. High Vt causes volutrauma. PEEP 0 fails to recruit. ARDS needs lung-protective strategy, not the opposite.' },
        { text: 'Switch to BVM at 20/min', exp: 'Going backward. Aggressive manual bagging worsens injury. Stick with vent and optimize settings.' },
      ],
      correct: 1,
      exp: 'Aspiration causes ARDS. ARDSNet protocol: 6 mL/kg IBW Vt, plateau pressure under 30, PEEP titrated to oxygenation, permissive hypercapnia. Reduces mortality versus older high-volume strategies.',
      difficulty: 9,
      tags: ['ards', 'vent-strategy'],
    },
    {
      id: 'aw-24',
      q: 'Pulse oximeter reads 100% on a patient pulled from a house fire. He is altered, lactic acidosis on labs, HR 130, BP 88/52. CO level is 22% but his clinical picture is much sicker than expected. What other airway/respiratory toxin should you consider and how is it treated?',
      choices: [
        { text: 'Methemoglobinemia - methylene blue', exp: 'Methemoglobinemia is a separate issue (causes brown blood, SpO2 caps around 85%). Not the typical fire-exposure killer. Wrong context.' },
        { text: 'Cyanide toxicity (from burning plastics) - hydroxocobalamin (Cyanokit)', exp: 'Correct. Cyanide is released from burning plastics, foam, wool. Causes lactic acidosis and shock out of proportion to CO level. Hydroxocobalamin binds cyanide and forms cyanocobalamin (excreted in urine). Suspect in ANY house fire victim with severe lactic acidosis.' },
        { text: 'Hydrogen sulfide - sodium nitrite', exp: 'H2S exposure is industrial/sewer/manure pit, not typical house fires. Different setting.' },
        { text: 'Chlorine gas - supportive only', exp: 'Chlorine is industrial/swimming pool exposure. Not the typical house fire toxin.' },
      ],
      correct: 1,
      exp: 'House fire trio: thermal burns + CO + cyanide. Cyanide is under-recognized and lethal. Lactate >10 + house fire + altered = give Cyanokit empirically. Do not wait for confirmatory testing.',
      difficulty: 9,
      tags: ['toxicology', 'cyanide'],
    },
    {
      id: 'aw-25',
      q: 'A patient on the vent with peak airway pressure 38 (high), but plateau pressure 18 (normal). What does this tell you about the lung problem?',
      choices: [
        { text: 'Decreased lung compliance - ARDS, pulmonary edema, pneumonia', exp: 'Wrong. Decreased compliance shows up as elevated PLATEAU pressure (the static pressure during inspiratory hold). This patients plateau is normal.' },
        { text: 'Increased airway resistance - bronchospasm, mucus plug, kinked tube, ETT obstruction', exp: 'Correct. The difference between peak and plateau reflects airway resistance. Normal gradient: 5-10 cmH2O. Wide gradient (here: 20) = high resistance. Causes: bronchospasm, mucus plug, secretions, kinked or biting on tube, foreign body. Fix: bronchodilators, suction, check tube.' },
        { text: 'Auto-PEEP', exp: 'Auto-PEEP is detected by checking expiratory flow not returning to zero or by expiratory hold maneuver. Not the primary read from peak vs plateau alone, though high resistance can lead to auto-PEEP.' },
        { text: 'Pneumothorax', exp: 'Pneumothorax raises PLATEAU pressure (compliance issue). Normal plateau argues against it.' },
      ],
      correct: 1,
      exp: 'Peak pressure - plateau pressure = airway resistance. Plateau pressure alone = lung compliance. Wide gap = resistance problem (bronchospasm, mucus, tube). High plateau = compliance problem (ARDS, pneumo, edema). This distinction guides treatment.',
      difficulty: 9,
      tags: ['vent-mechanics'],
    },
  ],
}
