import type { Category } from './types'

export const CARDIOLOGY: Category = {
  id: 'cardiology',
  name: 'Cardiology & Resuscitation',
  short: 'Cardiology',
  desc: 'ACLS, ECG interpretation, ACS, dysrhythmias, post-ROSC care, mechanical complications, cardiogenic shock, pediatric arrest, electrolyte emergencies.',
  color: '#ef4444',
  icon: 'heart',
  flashcards: [
    { id: 'cd-fc-1', front: 'STEMI criteria - three patterns to recognize', back: 'New ST elevation: 1mm in 2 contiguous leads (limb leads or V4-V6); 2mm in V2-V3 in men over 40; 1.5mm in V2-V3 in women; 2.5mm in V2-V3 in men under 40. New LBBB with chest pain in unstable patient = STEMI equivalent (Sgarbossa criteria refines). Posterior MI: ST depression in V1-V3 with tall R waves - get posterior leads.' },
    { id: 'cd-fc-2', front: 'OMI vs STEMI thinking', back: 'STEMI is a paper definition. OMI (Occlusion MI) is the actual problem - a vessel is occluding and lung is dying. About 25% of OMIs do not meet STEMI criteria but still need urgent cath. Watch for: hyperacute T waves, deWinter, Wellens, posterior MI, isolated aVR ST elevation, new LBBB or paced rhythm with chest pain. Trust the clinical picture even if numbers do not hit.' },
    { id: 'cd-fc-3', front: 'Wellens syndrome - recognize and act', back: 'Biphasic or deeply inverted T waves in V2-V3 (sometimes V1-V4) in a patient with recent chest pain that has now resolved. Means LAD critical stenosis. Patient looks fine but is days from a massive anterior MI. Do NOT stress test. Send to cath. Activity restriction until evaluated.' },
    { id: 'cd-fc-4', front: 'Inferior MI - which other vessel to check, what NOT to give', back: 'Inferior MI (II/III/aVF ST elevation) involves the RCA in 80%+. RCA also supplies SA and AV node and (in 80%) the right ventricle. Get RIGHT-sided leads (V4R) - ST elevation = RV infarct. RV infarct = preload-dependent. Avoid NITROGLYCERIN, morphine, beta-blockers (any preload-droppers). Treat low BP with FLUIDS not pressors first.' },
    { id: 'cd-fc-5', front: 'Pulseless arrest algorithm - 4 rhythms, 2 paths', back: 'SHOCKABLE: VF, pulseless VT - defibrillate, CPR, epi, antiarrhythmic (amiodarone 300 mg first dose, then 150). NON-SHOCKABLE: PEA, asystole - CPR, epi, no shock. Both: address H&Ts (Hypoxia, Hypovolemia, H+, Hypo/hyperK, Hypothermia, Tension pneumo, Tamponade, Toxins, Thrombosis, Trauma).' },
    { id: 'cd-fc-6', front: 'Adult defibrillation energy - biphasic', back: 'Biphasic: device-specific, typically 120-200J first shock, then 200J for subsequent. Many manufacturers recommend escalating (120, 150, 200, 360 equivalent). Pad placement: anterolateral standard. Anteroposterior for pacers/AICDs or refractory. Do not delay defibrillation to discuss energy - device defaults work.' },
    { id: 'cd-fc-7', front: 'Cardioversion vs defibrillation', back: 'Defibrillation = unsynchronized, for VF and pulseless VT. Cardioversion = synchronized to R wave, for unstable rhythms WITH a pulse (SVT, A-fib with RVR, A-flutter, stable VT). Energy starts lower for cardioversion (50-100J for narrow regular, 120-200J biphasic for A-fib, 100J for stable VT). Sedate when possible.' },
    { id: 'cd-fc-8', front: 'Adenosine dose and use', back: '6 mg rapid IV push + 20 mL flush, then 12 mg if no response, then 12 mg again. Antecubital or proximal IV. Patient warning: chest tightness, doom feeling, brief flushing - last seconds. Used for: terminate SVT (regular narrow complex), unmask flutter waves (slow conduction temporarily). Does NOT work on A-fib, A-flutter, V-tach with regular rhythm.' },
    { id: 'cd-fc-9', front: 'Unstable bradycardia drug ladder', back: '1) Atropine 1 mg IV every 3-5 min, max 3 mg. Often fails in heart blocks below AV node. 2) Transcutaneous pacing (TCP) - apply pads, set rate 60-80, increase mA until capture. 3) Dopamine 5-20 mcg/kg/min OR epinephrine 2-10 mcg/min infusion. Recognize when atropine will fail and skip to pacing (Mobitz II, complete heart block, post-MI).' },
    { id: 'cd-fc-10', front: 'Stable vs unstable in tachycardia', back: 'UNSTABLE = hypotension, altered mental status, ischemic chest pain, signs of shock, acute heart failure. Treatment: synchronized cardioversion. STABLE = no signs above; treat with drugs (adenosine for SVT, amiodarone or procainamide for VT). Wide-complex tachycardia is VT until proven otherwise - do NOT give adenosine if uncertain about wide-complex origin.' },
    { id: 'cd-fc-11', front: 'Atrial fib with RVR - rate vs rhythm control', back: 'Rate control first: diltiazem 0.25 mg/kg IV (max ~20 mg), repeat at 0.35 mg/kg in 15 min if needed. Or metoprolol 5 mg IV. Rhythm control (cardioversion) only if onset under 48h confirmed (or anticoagulated 3+ weeks) - otherwise stroke risk from atrial thrombus dislodging. Unstable A-fib: cardiovert anyway.' },
    { id: 'cd-fc-12', front: 'Cardiogenic shock - recognize and avoid the trap', back: 'BP low, JVD up, lungs wet, cold extremities, mottled. Pump failure. The TRAP: aggressive fluid bolus drowns them. Give SMALL fluid challenges (250 mL) and reassess. Mainstays: norepinephrine for BP, dobutamine for inotropy, fix the cause (revascularize STEMI, treat tamponade, etc). Mechanical support (IABP, ECMO) in severe.' },
    { id: 'cd-fc-13', front: 'Pulmonary edema - flash vs gradual', back: 'Flash pulmonary edema (sudden, hypertensive): fix BP and preload fast. Nitro paste/IV, BiPAP, lasix only if volume overloaded. Aggressive afterload reduction. Gradual CHF exacerbation: lasix, nitro, possibly BiPAP. Both benefit from upright positioning. NEVER lay these patients flat.' },
    { id: 'cd-fc-14', front: 'Pericardial tamponade - Becks triad and U/S', back: 'Becks triad: hypotension, JVD, muffled heart sounds. Often INCOMPLETE in real life. Pulsus paradoxus over 10 mmHg drop on inspiration. Echo shows effusion + RV diastolic collapse. Treat: IV fluids (preload-dependent), pericardiocentesis. Do NOT intubate before drainage if possible - positive pressure tanks venous return and arrests them.' },
    { id: 'cd-fc-15', front: 'Aortic dissection - pain pattern and exam', back: 'Tearing chest pain radiating to back, often interscapular. BP differential between arms over 20 mmHg. Hypertension common (managed aggressively). Risk: HTN, Marfan, bicuspid valve, cocaine, pregnancy, trauma. Stanford A (ascending) = surgery. Stanford B (descending) = medical. Goal: HR under 60, SBP 100-120. Beta-blocker first (esmolol), THEN vasodilator. Reverse order causes reflex tachycardia and worse propagation.' },
    { id: 'cd-fc-16', front: 'Pulmonary embolism - massive vs submassive', back: 'Massive PE: hypotension OR cardiac arrest. Treat: thrombolytics (alteplase 100 mg IV over 2 hours, or 50 mg push in arrest). Submassive: stable BP but RV strain on echo or biomarkers. Risk-stratify. PE without RV strain or biomarkers = anticoagulate. Massive PE in arrest (suspected): empiric thrombolytics, prolonged CPR up to 60-90 min.' },
    { id: 'cd-fc-17', front: 'Hyperkalemia ECG progression', back: 'Peaked T waves (often early) → prolonged PR → flattened/absent P waves → widening QRS → "sine wave" pattern → VF/asystole. Treatment ladder: 1) calcium (gluconate or chloride) - stabilizes cardiac membrane immediately. 2) shift potassium intracellular (insulin + dextrose, beta-agonist, bicarb). 3) eliminate K+ (lasix, kayexalate, dialysis). Calcium first - buys time.' },
    { id: 'cd-fc-18', front: 'Beta-blocker overdose vs CCB overdose', back: 'Both cause bradycardia + hypotension. CCB OD: hyperglycemia (CCBs block insulin release). BB OD: normal or low glucose. Treatment overlap: high-dose insulin therapy (1 unit/kg bolus, then 1-10 units/kg/hr with dextrose), calcium, glucagon (5-10 mg IV - works for BB OD specifically), pressors. IV lipid emulsion in refractory cases.' },
    { id: 'cd-fc-19', front: 'Tricyclic overdose ECG signs', back: 'Wide QRS over 100 ms, prominent R wave in aVR (over 3 mm), terminal R in aVR. Sodium bicarbonate 1-2 mEq/kg IV bolus narrows QRS by overcoming sodium channel blockade. Repeat as needed. Avoid Class IA, IC antiarrhythmics. Seizures common. Can cause ventricular dysrhythmias and arrest.' },
    { id: 'cd-fc-20', front: 'Wolff-Parkinson-White (WPW) - what NEVER to give', back: 'WPW = accessory pathway. Resting ECG: short PR, delta wave, wide QRS. AVOID AV nodal blockers (adenosine, beta-blockers, calcium channel blockers, digoxin) in WPW with A-fib/A-flutter - blocks normal pathway and accelerates conduction down accessory, can cause VF. Use procainamide or amiodarone. Cardiovert if unstable.' },
    { id: 'cd-fc-21', front: 'Torsades de pointes - recognize and treat', back: 'Polymorphic VT with twisting axis ("twisting of points"). Caused by long QT (drugs: macrolides, fluoroquinolones, antiemetics, methadone, antipsychotics; congenital LQT; electrolyte: low Mg, K, Ca; bradycardia). Treatment: magnesium 2 g IV, correct electrolytes, isoproterenol or pacing for bradycardia-related TDP, defibrillate if pulseless. Sotalol/amiodarone PROLONG QT - wrong choice.' },
    { id: 'cd-fc-22', front: 'Post-ROSC care - first 30 minutes', back: 'Targeted temperature management (32-36°C for 24h). Avoid hyperthermia. Maintain MAP 65+ (often 80-90 in severe). FiO2 to maintain SpO2 92-98% (avoid hyperoxia). Vt 6-8 mL/kg IBW. Check 12-lead - STEMI common. Cath lab if STEMI or high suspicion for cardiac cause. Glucose 140-180. Avoid sedation that masks neuro exam if possible.' },
    { id: 'cd-fc-23', front: 'Pacemaker problems - failure to capture', back: 'Pacing spike present but no QRS following. Causes: low voltage (battery failing), lead displacement, electrolyte abnormality, MI at lead site, drug effect. Failure to sense: pacer firing inappropriately during native rhythm - risk of R-on-T → VF. Pacemaker failure modes: failure to capture, failure to sense, oversensing (inhibits pacing). Magnet over device puts in async mode.' },
    { id: 'cd-fc-24', front: 'AICD/ICD considerations in arrest', back: 'External defib still works, just place pads at least 8 cm from device. CPR is fine. AICD shocks during CPR are not dangerous to rescuers (mild tingle if touching directly). If shocking on its own and patient has rhythm, magnet over device suspends ICD therapy. Tape magnet in place if needed during transport.' },
    { id: 'cd-fc-25', front: 'Anaphylactic shock and the heart', back: 'Vasodilation + capillary leak + bronchospasm + cardiac dysfunction (yes - anaphylaxis can directly affect myocardium = Kounis syndrome). Treat: IM epi 0.3-0.5 mg q5-15 min, IV epi infusion if refractory, aggressive fluids (1-2 L NS bolus), antihistamines and steroids (second-line). Dont forget to maintain airway in parallel.' },
    { id: 'cd-fc-26', front: 'Chest compression metrics that matter', back: 'Rate 100-120/min. Depth: adult 2-2.4 inches (5-6 cm), peds 1/3 AP diameter. Full recoil between compressions. Minimize interruptions (chest compression fraction > 60%, ideally > 80%). Switch compressors every 2 minutes. Higher quality CPR = higher ETCO2 = better outcomes.' },
    { id: 'cd-fc-27', front: 'Pediatric arrest doses to memorize', back: 'Defibrillation: 2 J/kg first, 4 J/kg next, up to 10 J/kg. Epi: 0.01 mg/kg (0.1 mL/kg of 1:10,000) IV/IO every 3-5 min. Amiodarone: 5 mg/kg bolus in arrest. Atropine: 0.02 mg/kg, min 0.1 mg, max 0.5 mg single dose. Adenosine: 0.1 mg/kg first (max 6 mg), 0.2 mg/kg second (max 12 mg).' },
    { id: 'cd-fc-28', front: 'Right heart strain on ECG', back: 'S1Q3T3 pattern (deep S in I, Q in III, inverted T in III) - CLASSIC for PE but only present in 15-20%. New right axis deviation, RBBB, T wave inversion in V1-V4 (anterior precordium showing strain). Sinus tachycardia is the most common ECG finding in PE. Looks like anterior ischemia but is from RV strain.' },
    { id: 'cd-fc-29', front: 'Mechanical complications of MI - first week', back: '1) Free wall rupture - sudden death/PEA, 3-7 days post-MI. 2) VSD (ventricular septal defect) - new harsh systolic murmur with thrill, hemodynamic deterioration, days post-MI. 3) Papillary muscle rupture - acute mitral regurgitation, flash pulmonary edema, often inferior MI affecting posteromedial papillary muscle. All surgical emergencies. New murmur post-MI = think mechanical complication.' },
    { id: 'cd-fc-30', front: 'Cardiac arrest in pregnancy', back: 'CPR with manual leftward uterine displacement (relieves IVC compression). Compressions slightly higher on sternum (uterus pushes diaphragm up). Defib normally - fetal monitor not contraindication. Resuscitative hysterotomy (perimortem C-section) within 4-5 minutes if maternal arrest in over-20-week pregnancy and no ROSC - improves both maternal and fetal survival.' },
  ],
  scenarios: [
    {
      id: 'cd-1',
      q: '52 y/o male, crushing substernal chest pain x 45 min, diaphoretic, BP 78/44, HR 50. ECG: 3mm ST elevation in II, III, aVF; reciprocal depression in I, aVL. You give aspirin 324 mg chewed. What is the next BEST intervention?',
      choices: [
        { text: 'Sublingual nitroglycerin 0.4 mg', exp: 'Wrong move. Inferior STEMI with hypotension is RV-involved until proven otherwise. Nitro will drop preload further and crash BP into asystole. Get right-sided leads first; if RV involved, AVOID nitro.' },
        { text: 'Right-sided 12-lead (V4R), then fluid bolus 250-500 mL NS', exp: 'Correct. Inferior STEMI + hypotension = suspect RV infarct. V4R confirms. RV is preload-dependent - give fluids, NOT nitro. Reassess after each bolus. Activate cath lab.' },
        { text: 'IV morphine 4 mg for pain', exp: 'Morphine drops BP further (vasodilation, mild histamine release). Recent data suggests morphine in ACS may worsen outcomes (slows antiplatelet absorption). Already hypotensive - bad idea.' },
        { text: 'Push metoprolol 5 mg IV for rate control', exp: 'Beta-blockers in HR 50 + hypotension = catastrophe. Beta-blockers in acute MI with hypotension or bradycardia are contraindicated. Will drop BP to arrest level.' },
      ],
      correct: 1,
      exp: 'Inferior STEMI + hypotension = RV infarct until proven otherwise. RV is preload-dependent. Fluids first, NEVER nitro/morphine/beta-blockers. Get V4R to confirm. Cath lab activation.',
      difficulty: 9,
      tags: ['stemi', 'rv-infarct'],
    },
    {
      id: 'cd-2',
      q: 'A 78 y/o female, sudden onset palpitations and chest pressure. ECG: regular wide-complex tachycardia at 180 bpm, QRS 160 ms. AAOx3, BP 92/60, no chest pain at rest, mild dyspnea. What is the BEST next step?',
      choices: [
        { text: 'Adenosine 6 mg rapid IV push', exp: 'Risky. Adenosine in wide-complex tachycardia of uncertain origin can be dangerous - if VT it does nothing; if WPW with A-fib it can cause VF. Wide-complex over 140 ms in elderly: assume VT until proven otherwise.' },
        { text: 'Synchronized cardioversion at 100 J', exp: 'Reasonable for unstable VT but BP 92/60 with mild symptoms is borderline. Many would still try drug therapy first. Cardioversion is the move if she becomes more unstable. Could also be the right answer in some interpretations of "borderline unstable."' },
        { text: 'Amiodarone 150 mg IV over 10 min', exp: 'Correct. Stable wide-complex tachycardia (assume VT): amiodarone 150 mg over 10 min. Also acceptable: procainamide (preferred in some guidelines), lidocaine. Avoid AV nodal blockers in wide-complex of uncertain origin.' },
        { text: 'Vagal maneuvers and IV diltiazem', exp: 'Wrong. Diltiazem in VT can cause cardiovascular collapse. AV nodal blockers in wide-complex tachycardia is the classic field error. Always assume VT until proven otherwise.' },
      ],
      correct: 2,
      exp: 'Wide-complex tachycardia in elderly with prior cardiac history = VT until proven otherwise. Stable: amiodarone or procainamide. Unstable: cardiovert. NEVER diltiazem or adenosine reflexively.',
      difficulty: 8,
      tags: ['vt', 'algorithm'],
    },
    {
      id: 'cd-3',
      q: 'A patient is in pulseless VT. You shock x1 at 200 J biphasic, resume CPR, give epi 1 mg, shock x2 at 200 J, give amiodarone 300 mg, shock x3. Still in VF. What is your NEXT pharmacologic move?',
      choices: [
        { text: 'Repeat amiodarone 300 mg', exp: 'Wrong dose. Second dose of amiodarone is 150 mg, not 300. First is 300, second is 150 if needed.' },
        { text: 'Amiodarone 150 mg IV (second dose)', exp: 'Correct. ACLS amiodarone dosing: first dose 300 mg, second dose 150 mg if persistent VF/pVT. Continue CPR, defibrillate, and consider lidocaine 1-1.5 mg/kg as alternative antiarrhythmic. Also keep looking for and treating reversible causes.' },
        { text: 'Lidocaine 1-1.5 mg/kg IV', exp: 'Acceptable alternative to second amiodarone dose. AHA lists lidocaine as equivalent to amiodarone in arrest. Either is correct, though sequence usually does amiodarone twice before switching.' },
        { text: 'Magnesium 2 g IV', exp: 'Magnesium is reserved for known torsades or hypomagnesemia. Not routine in VF/pVT unless those conditions are present. Wrong reflex.' },
      ],
      correct: 1,
      exp: 'Refractory VF/pVT: amiodarone 300 → 150. Lidocaine equally acceptable. Address H&Ts. Quality CPR + early defib + epi every 3-5 min are the lifesavers, not the antiarrhythmic.',
      difficulty: 7,
      tags: ['acls', 'refractory-vf'],
    },
    {
      id: 'cd-4',
      q: 'A 35 y/o male, weight 80 kg, presents with palpitations and dizziness. ECG: irregular irregular wide-complex tachycardia at 180-220 bpm with varying QRS morphology. History of WPW. BP 96/58, mild chest pain. What is the BEST treatment?',
      choices: [
        { text: 'Adenosine 6 mg IV push', exp: 'Catastrophic in WPW with A-fib. Adenosine blocks AV node, sending all conduction down accessory pathway, can degenerate to VF. NEVER give AV nodal blockers in WPW + A-fib.' },
        { text: 'Diltiazem 0.25 mg/kg IV', exp: 'Same lethal mistake. Calcium channel blockers in WPW + A-fib accelerate accessory pathway conduction. Can cause VF and arrest.' },
        { text: 'Procainamide 20-50 mg/min IV (max 17 mg/kg) or synchronized cardioversion', exp: 'Correct. WPW + A-fib treatment: drugs that block accessory pathway (procainamide, ibutilide) NOT AV node. Cardiovert if unstable. Amiodarone is also acceptable but procainamide is classically preferred.' },
        { text: 'Metoprolol 5 mg IV', exp: 'Beta-blockers also block AV node - same problem. Forces conduction down accessory pathway. Wrong drug class for WPW + A-fib.' },
      ],
      correct: 2,
      exp: 'WPW + A-fib pearls: AVOID adenosine, calcium channel blockers, beta-blockers, digoxin. They block AV node and force conduction down accessory pathway, risking VF. Use procainamide or cardiovert.',
      difficulty: 9,
      tags: ['wpw', 'pharmacology'],
    },
    {
      id: 'cd-5',
      q: 'A 60 y/o post-cardiac arrest with ROSC. BP 78/45, HR 110, SpO2 95% on FiO2 100%. Lactate 8. 12-lead shows 3mm ST elevation in V1-V4. What is the priority intervention sequence?',
      choices: [
        { text: 'TTM at 33°C, transport to hospital', exp: 'Misses the more urgent issue. STEMI post-arrest needs cath lab activation alongside post-arrest care. TTM and cath lab are not mutually exclusive - both happen.' },
        { text: 'Norepinephrine to MAP 65+, FiO2 titrated to SpO2 92-98%, activate cath lab, TTM', exp: 'Correct. Post-ROSC bundle: hemodynamic support (MAP 65+), avoid hyperoxia (titrate FiO2), avoid hypocapnia (target ETCO2 35-45), activate cath lab if STEMI, consider TTM. All concurrent, not sequential.' },
        { text: 'Push 1 L NS bolus then transport', exp: 'Inadequate. Patient needs vasopressors (cardiogenic shock), specific O2 targeting, and cath lab. Bolus alone misses the point.' },
        { text: 'Reload with amiodarone 150 mg, transport', exp: 'No indication. Patient has ROSC. Amiodarone given pre-arrest does not need reloading post-ROSC unless dysrhythmia recurs. Wastes time.' },
      ],
      correct: 1,
      exp: 'Post-ROSC: avoid hyperoxia, MAP 65+, find and treat cause (STEMI = cath lab), TTM. The bundle saves lives. Hyperoxia post-arrest worsens outcomes via reperfusion injury.',
      difficulty: 9,
      tags: ['post-arrest', 'bundle'],
    },
    {
      id: 'cd-6',
      q: 'Inferior STEMI with HR 38, BP 90/60, AAOx3. You consider atropine. The patient is on chronic beta-blocker. What is the MOST appropriate first intervention?',
      choices: [
        { text: 'Atropine 1 mg IV', exp: 'May fail. Inferior MI commonly causes AV block at the AV node level (Mobitz I or complete heart block). Atropine works on the AV node - sometimes effective. But chronic beta-blocker patients often need more aggressive treatment.' },
        { text: 'Transcutaneous pacing (TCP)', exp: 'Correct. In inferior MI with significant bradycardia and chronic beta-blocker use, TCP is reliable. Set rate 60-80, increase mA until capture. Also start dopamine or epinephrine infusion as backup. Atropine can be tried but do not delay pacing.' },
        { text: 'Glucagon 5-10 mg IV', exp: 'Used for beta-blocker overdose, not standard chronic use. Could be considered if all else fails but not first-line for symptomatic bradycardia with chronic BB use.' },
        { text: 'Isoproterenol infusion', exp: 'Generally avoided in MI - increases myocardial O2 demand and can extend infarct. TCP is safer.' },
      ],
      correct: 1,
      exp: 'Inferior MI + bradycardia + chronic BB = atropine often fails. Go to TCP early. Have epi/dopamine drip ready. Cath lab is the definitive fix - this is reperfusion-fixable bradycardia in many cases.',
      difficulty: 8,
      tags: ['bradycardia', 'pacing'],
    },
    {
      id: 'cd-7',
      q: 'A patient post-cardiac arrest with ROSC. ECG shows RBBB and concerning ST changes. The question is whether the ST changes are diagnostic or obscured. What ECG concept helps distinguish?',
      choices: [
        { text: 'Sgarbossa criteria - applies to LBBB or paced rhythm, not RBBB', exp: 'Sgarbossa is for LBBB/paced rhythm STEMI. Concordant ST elevation 1mm, concordant ST depression 1mm in V1-V3, or excessive discordant ST elevation. RBBB is generally easier to read.' },
        { text: 'In RBBB, ST changes in lateral leads (I, V5-V6) are READABLE and not obscured by the conduction delay', exp: 'Correct. Unlike LBBB where ST changes are routinely obscured by abnormal repolarization, RBBB does not significantly distort ST/T in lateral leads. Look at I, aVL, V5, V6 - they read normally. Septal leads V1-V3 are where the bundle changes the QRS most.' },
        { text: 'Use Wellens criteria', exp: 'Wellens is a specific T-wave pattern (biphasic or deep inversion in V2-V3) suggesting LAD critical lesion. Not a method to interpret BBB ST changes.' },
        { text: 'New RBBB always means STEMI', exp: 'Wrong. New RBBB has many causes (PE, MI, infection, structural). Not a STEMI equivalent the way new LBBB sometimes is.' },
      ],
      correct: 1,
      exp: 'RBBB does not obscure lateral ST changes - read them normally. LBBB obscures everything; use Sgarbossa. New LBBB with chest pain in unstable patient = STEMI equivalent. New RBBB is non-specific.',
      difficulty: 9,
      tags: ['ecg', 'bbb'],
    },
    {
      id: 'cd-8',
      q: 'A 68 y/o with hypertensive emergency and severe pulmonary edema. BP 218/124, RR 32, SpO2 84% on NRB, frothy pink sputum. AAOx3. What is the BEST initial intervention sequence?',
      choices: [
        { text: 'Lasix 80 mg IV first, then nitro', exp: 'Wrong order. Lasix takes 30+ min to work and is ineffective in flash pulmonary edema (these patients are not volume-overloaded - they are afterload-overloaded). Nitro and BiPAP/CPAP are first-line.' },
        { text: 'CPAP/BiPAP + nitroglycerin (paste, SL, then IV) + sit upright', exp: 'Correct. Flash pulmonary edema with HTN: aggressive afterload reduction with nitro + positive pressure ventilation. CPAP recruits alveoli and reduces preload. Nitro drops both preload and afterload. Sit upright. Lasix often unnecessary or counterproductive.' },
        { text: 'Morphine 4 mg IV', exp: 'Falling out of favor. Morphine in pulmonary edema may worsen outcomes (sedation, respiratory depression, hypotension). Older textbooks endorsed it; newer evidence does not.' },
        { text: 'Intubate immediately', exp: 'NIV (CPAP/BiPAP) is first-line and avoids intubation in most flash pulmonary edema cases. Reserve intubation for failed NIV or altered mental status.' },
      ],
      correct: 1,
      exp: 'Flash pulmonary edema = afterload problem, not volume. Nitro + CPAP/BiPAP does most of the work. Lasix is overused. Morphine is out. Sit them up.',
      difficulty: 8,
      tags: ['pulmonary-edema', 'hypertensive'],
    },
    {
      id: 'cd-9',
      q: 'A 58 y/o male, history of HTN, sudden tearing chest pain radiating to back. BP 218/124 right arm, 168/92 left arm. AAOx3, mild diaphoresis. Pulses present and equal in legs. What is your immediate management?',
      choices: [
        { text: 'Nitroglycerin SL 0.4 mg', exp: 'Wrong reflex. Pure vasodilator without rate control causes reflex tachycardia, increases shear stress on aorta, worsens dissection propagation. Beta-blocker first, THEN vasodilator if BP still high.' },
        { text: 'Esmolol or labetalol IV first to HR under 60, THEN nitroprusside or nicardipine for BP under 120 SBP', exp: 'Correct. Aortic dissection management: drop HR FIRST (reduces shear stress on aortic wall), then drop BP. Goal HR under 60, SBP 100-120. Beta-blocker before vasodilator. Activate aortic emergency protocol - Stanford A is surgical.' },
        { text: 'Heparin and aspirin', exp: 'Catastrophic. Anticoagulation in dissection accelerates bleeding and rupture. ABSOLUTELY contraindicated. Aortic dissection is the opposite of MI - anticoagulation kills these patients.' },
        { text: 'Lasix 40 mg IV', exp: 'Useless. Diuretics do not address the dissection or BP rapidly enough. Wrong tool.' },
      ],
      correct: 1,
      exp: 'Aortic dissection: HR FIRST (beta-blocker), then BP (vasodilator). Reverse causes reflex tachycardia and worsens dissection. NEVER anticoagulate. Mortality climbs 1% per hour untreated for Stanford A.',
      difficulty: 9,
      tags: ['aortic-dissection', 'pharmacology'],
    },
    {
      id: 'cd-10',
      q: 'A 30 y/o weight 60 kg, polymorphic VT on monitor, no pulse. You shock 200 J biphasic, resume CPR, push epi 1 mg. Rhythm continues. What is the MOST likely contributing factor and treatment?',
      choices: [
        { text: 'Hyperkalemia - give calcium', exp: 'Hyperkalemia causes monomorphic ventricular dysrhythmia, peaked T waves prior, sine wave pattern. Polymorphic VT (especially if QT was prolonged) suggests torsades.' },
        { text: 'Long QT (Torsades de pointes) - give magnesium 2 g IV', exp: 'Correct. Polymorphic VT with twisting axis = torsades. Often drug-induced (antiemetics, macrolides, antipsychotics) or electrolyte (low Mg, K, Ca). Mg 2 g IV bolus is treatment. Correct underlying electrolytes. AVOID amiodarone/sotalol - they prolong QT and worsen TDP.' },
        { text: 'Acidosis - give bicarb', exp: 'Bicarb is not standard for polymorphic VT. Magnesium addresses torsades specifically.' },
        { text: 'Hypoxia - increase FiO2', exp: 'Hypoxia is on the H&T list but does not specifically cause polymorphic VT. Mg is the targeted treatment for torsades.' },
      ],
      correct: 1,
      exp: 'Polymorphic VT = torsades until proven otherwise. Mg 2 g IV. Identify the QT-prolonging cause (drugs, electrolytes). NEVER give amiodarone in TDP - prolongs QT further.',
      difficulty: 9,
      tags: ['torsades', 'magnesium'],
    },
    {
      id: 'cd-11',
      q: 'A 75 y/o with chronic A-fib on warfarin presents with massive epistaxis. BP 88/50, HR 130 (irregular), pale. INR is 6.8 on labs. What is the MOST appropriate field/transport priority?',
      choices: [
        { text: 'Push protamine sulfate', exp: 'Wrong drug. Protamine reverses heparin, NOT warfarin. Warfarin is reversed with vitamin K, FFP, or 4-factor PCC. Protamine does nothing here.' },
        { text: 'IV fluids, packing, transport, vitamin K and 4-factor PCC at hospital', exp: 'Correct. Warfarin reversal options: vitamin K (slow), FFP (works but volume), 4-factor PCC (fast and concentrated, preferred for life-threatening bleed). En route: control bleeding (packing, pressure), fluid resuscitation cautiously (CHF risk). Definitive reversal is hospital-based.' },
        { text: 'Push aspirin and heparin', exp: 'Catastrophic. Patient is bleeding to death. Anticoagulants/antiplatelets make it worse.' },
        { text: 'Cardiovert the A-fib', exp: 'Patient is not unstable from rate - rate is high secondary to bleeding. Cardioverting solves nothing. Treat the cause (hemorrhage).' },
      ],
      correct: 1,
      exp: 'Warfarin reversal: PCC > FFP > vitamin K (for speed). Heparin reversal: protamine. Direct oral anticoagulants (DOACs): andexanet for factor Xa inhibitors, idarucizumab for dabigatran. Know which drug, know which reversal.',
      difficulty: 8,
      tags: ['anticoagulation', 'reversal'],
    },
    {
      id: 'cd-12',
      q: 'A 22 y/o female, healthy, suddenly has palpitations and lightheadedness. ECG: regular narrow-complex tachycardia at 192 bpm. BP 108/68, AAOx3. You attempt vagal maneuvers without success. Best next step:',
      choices: [
        { text: 'Diltiazem 0.25 mg/kg IV', exp: 'Reasonable second-line if adenosine fails, but adenosine is first-line for stable narrow-complex regular tachycardia. Diltiazem has more side effects and longer half-life.' },
        { text: 'Adenosine 6 mg rapid IV push, follow with 20 mL flush', exp: 'Correct. Stable SVT first-line: adenosine. Use proximal IV (antecubital ideal), rapid push immediately followed by 20 mL flush. Warn patient about feeling of doom - lasts seconds. If 6 mg fails, give 12 mg, then 12 mg.' },
        { text: 'Synchronized cardioversion at 100 J', exp: 'Reserved for unstable patients. This patient is stable (good BP, no symptoms beyond palpitations). Drug therapy first.' },
        { text: 'Amiodarone 150 mg IV', exp: 'Wrong tool for SVT. Amiodarone is for wide-complex tachycardia or arrest. Adenosine is the right choice for narrow-complex regular SVT.' },
      ],
      correct: 1,
      exp: 'Stable SVT: vagal first, then adenosine 6/12/12 mg. Use proximal IV. Modified Valsalva maneuver (REVERT trial) is more effective than standard Valsalva - try first if able.',
      difficulty: 6,
      tags: ['svt', 'adenosine'],
    },
    {
      id: 'cd-13',
      q: 'A patient with implanted AICD has been shocked 3 times in the past hour. He is awake, BP 108/64, mild chest discomfort. ECG between shocks shows atrial flutter at 150 (2:1 conduction). The AICD is misinterpreting flutter as VT. Best management?',
      choices: [
        { text: 'Place a magnet over the device to suspend AICD therapy', exp: 'Correct. Magnet over AICD inhibits anti-tachycardia therapy (does not affect pacing). Used when AICD is shocking inappropriately. Tape it in place during transport. Plan for device interrogation and rate control of flutter.' },
        { text: 'Disconnect the AICD by cutting wires', exp: 'Absolutely not. Surgical procedure. Magnet is non-invasive equivalent.' },
        { text: 'Sedate patient and ride out the shocks', exp: 'Inhumane and unnecessary. Magnet stops the shocks immediately.' },
        { text: 'Defibrillate externally to override AICD', exp: 'Pointless and risky. The AICD is functioning; the problem is misinterpretation. Magnet is the answer.' },
      ],
      correct: 0,
      exp: 'Inappropriate AICD shocks: place a magnet on the device. Suspends shock therapy without affecting pacing. Common in A-flutter, A-fib with rapid rate, lead malfunction, sinus tachycardia.',
      difficulty: 8,
      tags: ['aicd', 'magnet'],
    },
    {
      id: 'cd-14',
      q: 'A 6 y/o, 22 kg, in cardiac arrest. CPR ongoing. After 2 minutes CPR rhythm check shows VF. What is the correct first defibrillation energy?',
      choices: [
        { text: '2 J/kg (44 J)', exp: 'Correct. Pediatric defibrillation: 2 J/kg first shock, 4 J/kg subsequent, may go up to 10 J/kg. For 22 kg child first shock = 44 J. Most defibrillators round to nearest available setting (50 J).' },
        { text: '4 J/kg (88 J)', exp: 'Subsequent shock dose, not first.' },
        { text: '10 J/kg (220 J)', exp: 'Maximum dose for refractory VF/pVT in peds. Not first.' },
        { text: 'Adult dose 200 J', exp: 'Wrong for pediatrics under 8 years or under 25 kg. Use weight-based dosing.' },
      ],
      correct: 0,
      exp: 'Pediatric defib energy ladder: 2 → 4 → up to 10 J/kg. Adult dose at puberty/over-25-kg. Memorize this for NREMT.',
      difficulty: 7,
      tags: ['pediatric', 'defibrillation'],
    },
    {
      id: 'cd-15',
      q: 'A 45 y/o male in the field, dilated pupils, agitated, hypertensive (BP 196/118), tachycardic (HR 142), diaphoretic. He admits to using cocaine 30 minutes ago and now has chest pain. ECG: NSR, 1mm ST depression V4-V6. What is the BEST treatment approach?',
      choices: [
        { text: 'Metoprolol 5 mg IV', exp: 'Avoid in cocaine-induced ACS. Beta-blocker alone leaves alpha receptors unopposed → coronary vasoconstriction worsens. Classic teaching: avoid pure beta-blockade in active cocaine intoxication.' },
        { text: 'Benzodiazepines (lorazepam 2-4 mg or midazolam 2-5 mg) + nitroglycerin + aspirin', exp: 'Correct. Cocaine-related chest pain treatment: benzos first (reduce sympathetic surge, lower BP and HR safely), nitro for vasodilation, aspirin for ACS. If beta-blocker needed, use combined alpha-beta (labetalol) or only after alpha blockade.' },
        { text: 'Phentolamine 5 mg IV (pure alpha-blocker)', exp: 'Acceptable second-line for refractory hypertension in cocaine, but benzos are first because they treat the underlying sympathetic storm. Phentolamine is rarely available in field.' },
        { text: 'Push haloperidol 5 mg IM for agitation', exp: 'Avoid haloperidol in cocaine intox - prolongs QT, increases dysrhythmia risk in already high-catecholamine state. Benzos are safer for sympathomimetic agitation.' },
      ],
      correct: 1,
      exp: 'Cocaine cardiotoxicity: benzos first. Avoid pure beta-blockers (unopposed alpha → worse coronary vasospasm). Nitro and aspirin for chest pain. Labetalol acceptable if beta-blockade needed.',
      difficulty: 8,
      tags: ['cocaine', 'pharmacology'],
    },
    {
      id: 'cd-16',
      q: 'A 70 y/o male in cardiac arrest, ETT in place, IV established. CPR ongoing. Capnography showing 8 mmHg with good waveform. After 4 minutes you note a sudden rise in ETCO2 to 38 mmHg. What does this most likely indicate?',
      choices: [
        { text: 'Compressor is fatigued', exp: 'Fatigue typically drops ETCO2, not raises it. The rise is a positive sign.' },
        { text: 'Return of spontaneous circulation (ROSC)', exp: 'Correct. Sudden sustained rise in ETCO2 above 35 indicates ROSC, often 30-60 seconds before pulse is palpable. Continue CPR briefly, check rhythm, check pulse. ETCO2 is the most reliable sign of ROSC during ongoing arrest.' },
        { text: 'Tube migration into esophagus', exp: 'Esophageal migration would drop ETCO2 to near zero with loss of waveform - opposite of what is described.' },
        { text: 'Bicarbonate administration', exp: 'Bicarb would also raise ETCO2, but only after IV push and only briefly. The question implies no recent bicarb. ROSC is the more likely finding.' },
      ],
      correct: 1,
      exp: 'ETCO2 jump from 8 to 38 in arrest = ROSC. Capnography is the most sensitive monitor for ROSC and is faster than checking pulses. Watch the number; trust it.',
      difficulty: 7,
      tags: ['rosc', 'capnography'],
    },
    {
      id: 'cd-17',
      q: 'A 45 y/o construction worker, fell off a 3-story scaffold 30 minutes ago. Now in arrest. CPR ongoing. Rhythm: PEA. Possible reversible causes you should consider FIRST?',
      choices: [
        { text: 'Hypoxia and hypovolemia', exp: 'Correct general categories. In trauma arrest the most likely H&Ts are hypovolemia (blood loss), tension pneumothorax, cardiac tamponade, and hypoxia. Address all of these. Bilateral chest decompression often included empirically.' },
        { text: 'Hypothermia and toxins', exp: 'Less likely in this trauma context. Worth considering but lower priority than hypovolemia and tension pneumo.' },
        { text: 'Hyperkalemia and hypoglycemia', exp: 'Less likely in young trauma patient. These are more relevant in medical arrests with comorbidities.' },
        { text: 'Pulmonary thrombosis', exp: 'Unlikely in acute trauma. PE is more common in immobile/post-op patients, not blunt trauma arrest.' },
      ],
      correct: 0,
      exp: 'Trauma arrest H&Ts: hypoxia, hypovolemia, tension pneumothorax, tamponade. Address rapidly: bilateral chest decompression, blood/fluids, control bleeding. Standard CPR is less effective in hypovolemic arrest - fix the cause.',
      difficulty: 7,
      tags: ['trauma-arrest'],
    },
    {
      id: 'cd-18',
      q: 'A 60 y/o with NSTEMI, BP 100/60, HR 88. You give aspirin and NTG. He suddenly drops BP to 64/38, HR 110, JVD increases, cool extremities, lungs clear. What happened?',
      choices: [
        { text: 'Anaphylaxis to aspirin', exp: 'Possible but anaphylaxis usually presents with skin findings, wheezing, urticaria - not isolated cardiogenic-pattern shock with JVD.' },
        { text: 'Right ventricular infarct extension - preload-dependent, NTG dropped BP', exp: 'Correct. NTG drops preload aggressively. RV infarct is preload-dependent. Suspected RV infarct on initial ECG (or developing) with NTG given = expected hypotension. Treat: stop NTG, fluid bolus, possibly pressors. Should have checked V4R first.' },
        { text: 'Aspirin-induced GI bleed', exp: 'Way too fast. GI bleed from aspirin develops over time, not minutes. Wrong timeline.' },
        { text: 'Pulmonary edema', exp: 'Lungs are CLEAR. JVD with clear lungs argues against pulmonary edema.' },
      ],
      correct: 1,
      exp: 'NSTEMI with NTG-induced hypotension = think RV infarct. Right-sided leads (V4R) before NTG in any inferior or posterior MI. Fluid resuscitation. Avoid further preload-droppers.',
      difficulty: 8,
      tags: ['rv-infarct', 'iatrogenic'],
    },
    {
      id: 'cd-19',
      q: '88 y/o female, AAOx3, c/o palpitations. ECG: irregular irregular tachycardia at 130 with QRS 90 ms. BP 130/70, no chest pain. History: chronic A-fib on apixaban. New symptoms 2 hours ago. Best management?',
      choices: [
        { text: 'Synchronized cardioversion at 100 J', exp: 'Inappropriate. Patient is stable. Cardioversion in chronic A-fib without confirmed onset under 48h or 3+ weeks anticoagulation = stroke risk from atrial thrombus dislodging. Especially in elderly.' },
        { text: 'Rate control with diltiazem 0.25 mg/kg IV (about 17 mg)', exp: 'Correct. Stable A-fib with RVR: rate control is the goal. Diltiazem first-line. Titrate to HR under 110. Patient is anticoagulated (apixaban) and rate-control is the move. Rhythm control is for younger or symptomatic patients with onset under 48h confirmed.' },
        { text: 'Amiodarone 150 mg IV', exp: 'Acceptable but not first-line for rate control in A-fib. Diltiazem or metoprolol are preferred. Amiodarone is more for rhythm control or when rate-control drugs are contraindicated.' },
        { text: 'Adenosine 6 mg', exp: 'Useless. Adenosine does not work on A-fib (atria fibrillating, AV node only conducts some impulses). May briefly slow rate to unmask flutter waves but not therapeutic.' },
      ],
      correct: 1,
      exp: 'Stable A-fib with RVR: rate control with diltiazem or metoprolol. Cardioversion only if unstable or confirmed onset under 48h with anticoagulation. Beta-blockers preferred if heart failure with reduced EF.',
      difficulty: 7,
      tags: ['afib', 'rate-control'],
    },
    {
      id: 'cd-20',
      q: 'A 10 y/o, 30 kg, in cardiac arrest from drowning. CPR ongoing for 8 minutes. Rhythm: asystole. Epi has been given x2. ETT in place, ETCO2 6 mmHg. Best next intervention?',
      choices: [
        { text: 'Push epi 0.3 mg (10x dose)', exp: 'Wrong. Standard pediatric epi is 0.01 mg/kg = 0.3 mg per dose for 30 kg child. NOT 10x dose. High-dose epi was tried historically; outcomes were worse.' },
        { text: 'Reassess CPR quality (depth, recoil, rate, ventilation rate) - ETCO2 of 6 indicates inadequate compressions', exp: 'Correct. Drowning-induced arrest is hypoxia-driven. Quality CPR + ventilation are critical. ETCO2 of 6 means compressions are not generating perfusion. Push deeper, full recoil, switch compressors. Rule out hypothermia, hypoglycemia, electrolytes.' },
        { text: 'Stop resuscitation', exp: 'Premature. Pediatric drowning arrests can have good outcomes even after prolonged downtime, especially in cold water. Continue CPR until rewarmed (if hypothermic) and address reversible causes.' },
        { text: 'Push 1 mEq/kg sodium bicarb', exp: 'Routine bicarb in arrest is not recommended. May consider in known acidosis or hyperkalemia. Not the first move.' },
      ],
      correct: 1,
      exp: 'Drowning arrest: hypoxia is the killer. Quality CPR + ventilation + extended resuscitation often warranted, especially cold-water and pediatric. ETCO2 of 6 = compressions inadequate. Fix that first.',
      difficulty: 8,
      tags: ['pediatric', 'drowning', 'cpr-quality'],
    },
    {
      id: 'cd-21',
      q: 'A 50 y/o with ESRD on hemodialysis, missed last 2 sessions. Now in cardiac arrest. ECG: sine wave pattern. Most likely cause and treatment?',
      choices: [
        { text: 'Hypokalemia - give KCl IV', exp: 'Wrong direction. Sine wave is classic hyperkalemia, not hypo. ESRD without dialysis = K accumulation.' },
        { text: 'Hyperkalemia - calcium gluconate or chloride IV first, then bicarb, insulin/dextrose, transport for emergent dialysis', exp: 'Correct. ESRD + missed dialysis + sine wave = hyperkalemia until proven otherwise. Calcium STABILIZES the membrane (acts in seconds). Then shift K intracellular (insulin/dextrose, beta-agonist, bicarb if acidotic). Definitive: dialysis.' },
        { text: 'Hypocalcemia - push calcium', exp: 'Calcium IS the right move, but the underlying cause is hyperkalemia, not hypocalcemia. Same drug, right reason matters for additional therapies.' },
        { text: 'Acidosis - push bicarb', exp: 'Bicarb is part of treatment but calcium first to stabilize membrane. Bicarb shifts K intracellularly but takes longer to act.' },
      ],
      correct: 1,
      exp: 'Sine wave + ESRD + missed dialysis = hyperkalemia. Treatment ladder: calcium (membrane stabilization, immediate) → shift K intracellular (insulin/dextrose, bicarb, beta-agonist) → eliminate (dialysis, lasix). Calcium FIRST - it buys time.',
      difficulty: 9,
      tags: ['hyperkalemia', 'esrd'],
    },
    {
      id: 'cd-22',
      q: 'A 35 y/o with blunt chest trauma from steering wheel impact, hypotensive (BP 78/48), JVD, muffled heart sounds, narrow pulse pressure. Beck triad. You suspect pericardial tamponade. The best initial intervention en route is:',
      choices: [
        { text: 'Intubate and ventilate aggressively', exp: 'Dangerous. Positive pressure ventilation increases intrathoracic pressure and decreases venous return. In tamponade, this can cause arrest. Avoid intubation pre-drainage if possible.' },
        { text: 'IV fluid bolus 1-2 L crystalloid (or blood) to maintain preload', exp: 'Correct. Tamponade is preload-dependent. Aggressive fluid resuscitation maintains filling pressure to push blood through. Definitive treatment is pericardiocentesis at hospital. En route: fluids, NO positive pressure if avoidable.' },
        { text: 'Norepinephrine infusion to raise BP', exp: 'Pressors do not fix the mechanical compression. Fluids first; pressors as adjunct only.' },
        { text: 'Push furosemide 40 mg', exp: 'Catastrophic. Lasix drops preload further - kills tamponade patients. Opposite of what they need.' },
      ],
      correct: 1,
      exp: 'Tamponade is preload-dependent. Fluids = better filling = better cardiac output. Avoid positive pressure ventilation pre-drainage. Pericardiocentesis is definitive. AVOID anything that drops preload (nitro, lasix, morphine).',
      difficulty: 8,
      tags: ['tamponade', 'trauma'],
    },
    {
      id: 'cd-23',
      q: 'You are managing a vent-dependent patient with pulmonary embolism. BP 80/45, HR 130, SpO2 88% on FiO2 100%, hypoxia worsening. Cardiac echo (POCUS) shows D-shaped LV from RV pressure overload. Best next step?',
      choices: [
        { text: 'Increase PEEP to 15', exp: 'Wrong. High PEEP in RV failure WORSENS RV afterload, can cause RV collapse. PEEP needs to stay modest in RV strain.' },
        { text: 'Cautious fluid bolus 250-500 mL + thrombolytics (alteplase) if no contraindications + norepinephrine for BP', exp: 'Correct. Massive PE with RV strain and shock: thrombolytics (alteplase 100 mg over 2h, or 50 mg push if arresting). Cautious fluids (over-resuscitation worsens RV failure). Norepinephrine first-line vasopressor (avoid drugs that raise PVR like phenylephrine).' },
        { text: 'Aggressive 2 L NS bolus', exp: 'RV is already failing and dilated. Massive fluid worsens RV dilation and shifts septum into LV (the D-shape worsens). Modest fluid only.' },
        { text: 'Heparin alone', exp: 'In MASSIVE PE with shock, anticoagulation alone is too slow. Need to dissolve clot fast - thrombolytics. Heparin for non-massive or as adjunct.' },
      ],
      correct: 1,
      exp: 'Massive PE: cautious fluids, thrombolytics, norepinephrine. Avoid high PEEP and big fluid boluses (worsen RV failure). The classic mistake is over-resuscitating with fluid in RV shock.',
      difficulty: 9,
      tags: ['pe', 'rv-failure'],
    },
    {
      id: 'cd-24',
      q: 'A 72 y/o male with syncope. ECG: 2:1 AV block, narrow QRS, atrial rate 100, ventricular rate 50. BP 92/58. AAOx3 currently. Best management?',
      choices: [
        { text: 'Immediate transcutaneous pacing', exp: 'Premature. Patient is stable currently (AAOx3, BP adequate). Stable 2:1 block with narrow QRS is often Mobitz I (AV nodal) and may respond to atropine. Pacing pads ON, ready, but not pacing yet.' },
        { text: 'Atropine 1 mg trial; place pacing pads as standby; transport monitored', exp: 'Correct. Stable bradycardia: trial atropine first if narrow-complex (suggests AV nodal block, atropine likely to work). Pacer pads on as backup. Transport. If unstable develops, pace.' },
        { text: 'Diltiazem to slow ventricular rate further', exp: 'Wrong direction. Patient already bradycardic. Drugs that slow conduction are contraindicated.' },
        { text: 'Synchronized cardioversion', exp: 'Cardioversion is for tachydysrhythmias. Wrong tool.' },
      ],
      correct: 1,
      exp: 'Stable narrow-complex bradycardia: atropine first, pacing as backup. Mobitz II or wide-complex: skip atropine, go to pacing/dopamine/epi. The narrow QRS predicts atropine response.',
      difficulty: 7,
      tags: ['av-block', 'bradycardia'],
    },
    {
      id: 'cd-25',
      q: 'A 55 y/o with chest pain, ECG shows: 1mm ST elevation aVR, diffuse ST depression I, II, V4-V6, deep T wave inversion. BP 130/80, HR 92, AAOx3. What does this pattern suggest?',
      choices: [
        { text: 'Inferior STEMI', exp: 'Inferior STEMI shows ST elevation in II, III, aVF - not the described pattern. Different anatomic distribution.' },
        { text: 'Left main coronary artery occlusion or 3-vessel disease - high-risk pattern, urgent cath', exp: 'Correct. ST elevation in aVR with diffuse ST depression elsewhere = high-risk pattern suggesting left main, proximal LAD, or 3-vessel disease. Mortality is high. Activate cath lab even though it does not meet classic STEMI criteria. This is an OMI without classic STEMI.' },
        { text: 'Pericarditis', exp: 'Pericarditis shows DIFFUSE ST elevation (not depression), often with PR depression. Different pattern.' },
        { text: 'LBBB normal pattern', exp: 'LBBB has wide QRS over 120 ms with characteristic morphology. Question describes ST/T pattern, not BBB.' },
      ],
      correct: 1,
      exp: 'aVR elevation + diffuse ST depression = left main or 3-vessel disease until proven otherwise. High mortality. Activate cath lab even without 1mm elevation in 2 contiguous leads. This is OMI thinking - vessel is occluding even though paper STEMI criteria not met.',
      difficulty: 9,
      tags: ['omi', 'left-main'],
    },
  ],
}
