import type { Category } from './types'

export const MEDICAL: Category = {
  id: 'medical',
  name: 'Medical Emergencies',
  short: 'Medical',
  desc: 'Sepsis, DKA, stroke, seizure, anaphylaxis, GI bleed, toxicology, electrolyte derangements, environmental emergencies, endocrine crises.',
  color: '#10b981',
  icon: 'cross',
  flashcards: [
    { id: 'me-fc-1', front: 'Sepsis 1-hour bundle', back: 'Within 1 hour of recognition: 1) Lactate, 2) Blood cultures BEFORE antibiotics, 3) Broad-spectrum antibiotics, 4) 30 mL/kg crystalloid for hypotension or lactate over 4, 5) Vasopressors if MAP under 65 after fluids. Surviving Sepsis. Every hour delay in antibiotics = ~7% increase in mortality.' },
    { id: 'me-fc-2', front: 'qSOFA criteria for sepsis screening', back: '2 of 3: RR over 22, altered mental status (GCS under 15), SBP under 100. Used outside ICU as early screen. NOT a diagnostic tool. Full SOFA score is the formal definition. Any qSOFA positive = high suspicion, get lactate and full workup.' },
    { id: 'me-fc-3', front: 'Septic shock vasopressor of choice and dose', back: 'Norepinephrine first-line. Start 0.05-0.1 mcg/kg/min, titrate to MAP 65 or higher. Vasopressin 0.03 U/min added if needing more than 0.25 mcg/kg/min norepi. Epinephrine added third. Dopamine fallen out of favor - more arrhythmias and worse outcomes than norepi.' },
    { id: 'me-fc-4', front: 'DKA diagnostic triad', back: 'Hyperglycemia (over 250 typically, but can be euglycemic in SGLT2 use, pregnancy, alcohol), anion gap metabolic acidosis (gap over 12, pH under 7.3), ketonemia/ketonuria (beta-hydroxybutyrate elevated). Bicarb under 18. Calculate anion gap: Na - (Cl + HCO3). Normal 8-12.' },
    { id: 'me-fc-5', front: 'DKA management - first hour priorities', back: '1) IV NS bolus 15-20 mL/kg (most patients are 100 mL/kg dehydrated). 2) Check potassium FIRST before insulin. K under 3.3: hold insulin, replace K. K 3.3-5.2: give insulin and add K to fluids. K over 5.2: insulin alone, monitor. 3) Insulin drip 0.1 U/kg/hr after K addressed. 4) Bicarb only if pH under 6.9. 5) Find the trigger (infection, MI, missed dose).' },
    { id: 'me-fc-6', front: 'HHS vs DKA - which is which', back: 'DKA: type 1 typically, glucose over 250 (often 400-600), ketones positive, acidosis present, faster onset (hours-days). HHS: type 2, older, glucose over 600 (often over 1000), minimal/no ketones, no acidosis, severe dehydration, slower onset (days-weeks), higher mortality (10-20% vs DKA 1-5%). HHS patients are PROFOUNDLY volume depleted (8-10L deficit).' },
    { id: 'me-fc-7', front: 'Cushings response NOT triad - different concept', back: 'Cushings response is the PHYSIOLOGY: massive sympathetic surge in response to brainstem ischemia. Cushings TRIAD is the clinical finding: HTN + bradycardia + irregular respirations. Triad signals herniation imminent. Same name, different scope. Both = late and ominous.' },
    { id: 'me-fc-8', front: 'Stroke window for tPA and thrombectomy', back: 'tPA (alteplase or tenecteplase): 0-4.5 hours from last known well. Newer evidence supports up to 9 hours with imaging selection. Thrombectomy: up to 24 hours for large vessel occlusion with imaging selection (penumbra still salvageable). NIHSS over 6 typically indicates LVO. Time is brain - every minute, 1.9 million neurons die.' },
    { id: 'me-fc-9', front: 'Stroke BP management - lower vs leave alone', back: 'Ischemic stroke (no tPA): permissive HTN up to 220/120. Lowering BP worsens penumbra perfusion. Ischemic with tPA: lower to under 185/110 before, under 180/105 after. Hemorrhagic stroke: lower SBP to 140 (target 130-140 in ICH per INTERACT trials). Goal differs sharply by stroke type - get the CT first.' },
    { id: 'me-fc-10', front: 'Status epilepticus - definition and first-line', back: 'Continuous seizure over 5 minutes OR recurrent without recovery between. First-line: IM midazolam 10 mg or IV lorazepam 4 mg (or 0.1 mg/kg). Repeat in 5-10 min. Second-line: levetiracetam 60 mg/kg or fosphenytoin 20 mg/kg or valproate 40 mg/kg. Refractory (still seizing after 2 agents): intubation, propofol or midazolam infusion. Pyridoxine for INH overdose seizures. Glucose if hypoglycemic.' },
    { id: 'me-fc-11', front: 'Anaphylaxis - first drug, dose, route', back: 'Epinephrine IM, NOT IV. Adult: 0.3-0.5 mg of 1:1000 IM lateral thigh. Peds: 0.01 mg/kg, max 0.3 mg. Repeat every 5-15 minutes. IV epi only for refractory shock or arrest, lower concentration (1:10,000), higher arrhythmia risk. Antihistamines, steroids, albuterol are SECOND line - they do NOT save lives in anaphylaxis. Epi is the only thing that does.' },
    { id: 'me-fc-12', front: 'Anaphylaxis biphasic reaction', back: '5-20% of cases recur 4-72 hours later (most within 12). Even if symptoms resolve, observe for 4-6+ hours. Patient education: epi auto-injector, allergy avoidance, when to seek care, follow-up with allergist. Beta-blockers blunt response to epi - may need glucagon 1-5 mg IV in those patients.' },
    { id: 'me-fc-13', front: 'Acetaminophen overdose - N-acetylcysteine timing', back: 'NAC most effective within 8 hours of ingestion. Still beneficial up to 24+ hours. Loading 150 mg/kg over 60 min, then 50 mg/kg over 4 hours, then 100 mg/kg over 16 hours (IV protocol). Use Rumack-Matthew nomogram for 4-hour level - anything above treatment line gets NAC. King College Criteria for liver transplant evaluation.' },
    { id: 'me-fc-14', front: 'Tylenol toxicity - phases', back: 'Phase 1 (0-24h): nausea, vomiting, asymptomatic. Phase 2 (24-72h): RUQ pain, AST/ALT rising. Phase 3 (72-96h): peak hepatotoxicity, coagulopathy, encephalopathy. Phase 4 (recovery or death): 5-10 days. Patients can look normal early - get the level. Even unintentional chronic overdose (over 4g/day in chronic etoh users) can cause fulminant hepatic failure.' },
    { id: 'me-fc-15', front: 'Tricyclic antidepressant overdose - recognition and treatment', back: 'Anticholinergic toxidrome (hot, dry, dilated pupils, hallucinating) + cardiotoxic (wide QRS over 100, R wave in aVR over 3 mm) + seizure-prone. Treatment: sodium bicarbonate IV 1-2 mEq/kg if QRS over 100, target pH 7.5. Bicarb narrows QRS by overcoming Na+ channel blockade. Seizure: benzos (avoid phenytoin - also Na+ blocker). Hypotension: norepi (avoid epi - TCA blocks alpha, can cause beta-only response). Lipid emulsion for refractory.' },
    { id: 'me-fc-16', front: 'Beta-blocker vs calcium-channel blocker overdose', back: 'Both cause bradycardia and hypotension. Treatment overlaps. High-dose insulin (1 U/kg bolus then 1-10 U/kg/hr with D50 infusion) is mainstay for both - improves myocardial glucose use. Glucagon 5-10 mg IV bolus then drip for beta-blocker (bypasses beta receptor). Calcium 1-3g IV for CCB. Lipid emulsion for severe. Pacemaker if refractory bradycardia.' },
    { id: 'me-fc-17', front: 'Opioid overdose - naloxone dose and pitfalls', back: 'Initial: 0.04-0.1 mg IV in chronic users (avoid precipitated withdrawal), 0.4-2 mg in opioid-naive or critical respiratory depression. Repeat every 2-3 minutes. IM/IN works if no IV. Drip if requiring repeat doses. Half-life shorter than most opioids (especially methadone, fentanyl, sustained-release) - observe 4-6+ hours. Recurrent respiratory depression is common and lethal.' },
    { id: 'me-fc-18', front: 'Salicylate toxicity - recognition and treatment', back: 'Mixed acid-base: respiratory ALKALOSIS (early, from direct stimulation of resp center) + metabolic ACIDOSIS (later, from uncoupling of oxidative phosphorylation). Tinnitus, fever, AMS, hyperventilation. Treatment: alkalinize urine with bicarb (target urine pH over 7.5) to enhance excretion. Hemodialysis for severe (level over 100, AMS, pulmonary edema, refractory acidosis, renal failure). Avoid intubation - apnea worsens acidosis fast.' },
    { id: 'me-fc-19', front: 'Hyperkalemia treatment ladder', back: '1) Calcium gluconate or chloride - stabilize myocardium (does not lower K+, but prevents arrhythmia). 2) Insulin 10 U + D50 - drives K+ into cells, lasts 2-6 hours. 3) Beta-2 agonist (albuterol 10-20 mg neb) - drives K+ in, lasts hours. 4) Bicarb - only useful if acidotic. 5) Lasix - eliminates K+ if kidneys work. 6) Kayexalate - slow, controversial, often skipped. 7) Dialysis - definitive for renal failure. ECG changes drive urgency: peaked T, wide QRS, sine wave.' },
    { id: 'me-fc-20', front: 'Hyponatremia - symptomatic treatment', back: 'Severe symptoms (seizure, coma): 3% saline 100-150 mL bolus, repeat up to 3 times until symptoms abate. Goal: raise Na 4-6 mEq/L acutely to relieve cerebral edema. Then SLOW: max 8 mEq/L per 24 hours, 18 per 48 hours. Faster correction risks osmotic demyelination syndrome (locked-in syndrome, often fatal). Chronic hyponatremia is more dangerous to correct fast than acute.' },
    { id: 'me-fc-21', front: 'Hypoglycemia treatment by route', back: 'Conscious able to swallow: 15-20 g oral carb (juice, glucose tabs), recheck 15 min. Unconscious or NPO with IV: 25 g D50 (50 mL of 50%) or 12.5 g D25 in peds. Unconscious without IV: glucagon 1 mg IM (works only if glycogen stores intact - fails in alcoholics, malnourished). After correction, give complex carbs to prevent rebound. Always recheck. Sulfonylurea OD recurs - admit and dextrose drip.' },
    { id: 'me-fc-22', front: 'Heat stroke - recognize and treat', back: 'Core temp over 40C + altered mental status. Two types: classic (elderly in heat wave) and exertional (young athletes, military). Treatment: rapid cooling to 39C - ice water immersion is most effective (athletes), evaporative cooling (mist + fan) for elderly. Cold IV fluids. Stop cooling at 39C (avoid overshoot). Antipyretics dont work (this is not fever - its hyperthermia from environmental load). Mortality high if not cooled in first 30-60 minutes.' },
    { id: 'me-fc-23', front: 'Hypothermia rewarming methods', back: 'Mild (32-35C): passive - blankets, warm room. Moderate (28-32C): active external - Bair Hugger, forced air warmers. Severe (under 28C) or hemodynamic instability: active core - warm IV fluids, warm humidified O2, peritoneal/bladder lavage with warm saline. Cardiac arrest with severe hypothermia: ECMO/cardiopulmonary bypass is gold standard - survivors with intact neurology have been documented at temps below 14C.' },
    { id: 'me-fc-24', front: 'GI bleed initial management', back: 'Two large-bore IVs, T+C, CBC, coags, lactate. Resuscitate with blood, not crystalloid (worsens coagulopathy). Hgb under 7 transfuse (under 8 in CAD). Reverse anticoagulation. Octreotide 50 mcg bolus then drip for variceal. PPI drip 80 mg bolus then 8 mg/hr for ulcer. Antibiotics (ceftriaxone 1g) for cirrhotic with GI bleed. Endoscopy within 24 hours, sooner for instability.' },
    { id: 'me-fc-25', front: 'Subarachnoid hemorrhage - recognize', back: 'Sudden severe (thunderclap) headache, often described as worst headache of life. Reaches maximum intensity within minutes. Signs: meningismus, photophobia, focal deficits, decreased LOC. Sentinel headache may precede rupture. CT is sensitive within 6 hours (over 95%) - after that, may need LP looking for xanthochromia or RBCs not clearing across tubes. Nimodipine for vasospasm prevention. Aneurysm coiling/clipping urgently.' },
    { id: 'me-fc-26', front: 'Bacterial meningitis - empiric antibiotics', back: 'Adult under 50: ceftriaxone 2g IV + vancomycin (covers resistant pneumococcus). Over 50 or immunocompromised: add ampicillin (Listeria coverage). Dexamethasone 10 mg IV BEFORE or with first antibiotic dose - reduces mortality and neuro sequelae in pneumococcal. Get LP - but DO NOT delay antibiotics. CT first if focal deficit, papilledema, AMS, immunocompromise (rule out mass before LP).' },
    { id: 'me-fc-27', front: 'Carbon monoxide poisoning - when to use hyperbaric', back: 'Hyperbaric O2 indications: LOC at any time, neuro deficit, lactate over 7, COHb over 25%, pregnancy with COHb over 15%, severe acidosis, age over 35 with COHb over 20%, ischemic ECG changes. Hyperbaric reduces delayed neuropsychiatric sequelae (DNS) from 30% to 10%. 100% O2 by NRB until then; half-life 320 min on RA, 80 min on 100% O2, 23 min on hyperbaric.' },
    { id: 'me-fc-28', front: 'Adrenal crisis - recognize and treat', back: 'Hypotension refractory to fluids and pressors + hyperkalemia + hyponatremia + hypoglycemia in a patient with known adrenal insufficiency or chronic steroid use. Treatment: hydrocortisone 100 mg IV bolus, then 50 mg every 6 hours. Aggressive volume resuscitation. Treat the precipitant (infection, MI, surgery). Stress-dose steroids for any patient on chronic steroids undergoing illness or surgery - they cant make their own.' },
    { id: 'me-fc-29', front: 'Thyroid storm - recognize and treat', back: 'Severe thyrotoxicosis: fever 40+, tachycardia 140+, AFib common, AMS, GI upset, heart failure, shock. Triggers: surgery, infection, iodine load, missed meds, trauma. Treatment order: 1) Beta-blocker (propranolol 60-80 mg or esmolol drip - controls symptoms). 2) Thionamide (PTU or methimazole - blocks new synthesis). 3) Iodine 1 hour AFTER thionamide (Wolff-Chaikoff effect - blocks release). Order matters: iodine before thionamide can worsen storm. 4) Steroids (hydrocortisone - blocks T4 to T3 conversion). 5) Cool, hydrate, treat trigger.' },
    { id: 'me-fc-30', front: 'Myxedema coma - recognize and treat', back: 'Severe hypothyroidism: hypothermia, bradycardia, hypotension, hypoventilation (CO2 retention), hyponatremia, AMS or coma. Triggers: cold exposure, infection, surgery in an undertreated hypothyroid patient. Treatment: IV levothyroxine 200-500 mcg loading then 50-100 daily, hydrocortisone 100 mg before T4 (concurrent adrenal insufficiency assumed until ruled out - giving T4 alone can precipitate adrenal crisis), passive rewarming, supportive care. Mortality 20-50%.' },
  ],
  scenarios: [
    {
      id: 'me-1',
      q: '52-year-old male, T 39.2C, HR 122, BP 84/52, RR 26, SpO2 92% on RA, lactate 4.8, WBC 18.2 with bandemia. CXR shows right lower lobe pneumonia. Hes been hypotensive for the last 30 minutes. Most appropriate FIRST steps within the next hour?',
      choices: [
        { text: 'Antibiotics within 1 hour, blood cultures BEFORE antibiotics, 30 mL/kg LR bolus, lactate trend', exp: 'Correct. Surviving Sepsis 1-hour bundle: lactate, blood cultures (before abx, dont delay abx for them), broad-spectrum antibiotics, 30 mL/kg crystalloid for hypotension or lactate over 4. Start vasopressors if MAP under 65 after fluids. Every hour delay in antibiotics increases mortality by 7-8%.' },
        { text: 'Wait for blood cultures to result before starting antibiotics', exp: 'Wrong. Abx within 1 hour of recognition. Cultures are drawn beforehand if it doesnt delay treatment, but treatment is the priority.' },
        { text: 'CT scan to rule out other sources before treating', exp: 'CXR identifies the source. CT delays treatment. Time-sensitive infection.' },
        { text: 'Start vasopressors immediately for the hypotension', exp: 'Vasopressors are added if MAP doesnt respond to crystalloid bolus. Initial step is fluid resuscitation, not vasopressors first. They follow.' },
      ],
      correct: 0,
      exp: 'Septic shock 1-hour bundle: lactate, blood cultures BEFORE antibiotics (dont delay if drawing them takes time), antibiotics, 30 mL/kg crystalloid, vasopressors if MAP under 65 after fluids. Norepinephrine first-line. Goal MAP 65 or higher.',
      difficulty: 8,
      tags: ['sepsis', 'bundle'],
    },
    {
      id: 'me-2',
      q: '24-year-old type 1 diabetic, glucose 580, pH 7.04, anion gap 28, K+ 6.2, bicarb 8. Mental status declining. After NS bolus, what is the order of next steps?',
      choices: [
        { text: 'Insulin drip immediately at 0.1 U/kg/hr, then K+ replacement once K drops', exp: 'Wrong sequence. Patient has hyperkalemia now but driving insulin in will rapidly drop K+ - by the time you notice, they may have arrhythmia. Address potassium first if abnormal at either extreme.' },
        { text: 'Bicarbonate to correct the acidosis, then insulin', exp: 'Bicarb in DKA only used if pH under 6.9. Routine bicarb doesnt improve outcomes and can worsen intracellular acidosis and cause paradoxical CSF acidosis.' },
        { text: 'Insulin drip and add K+ to fluids monitoring closely (insulin will drive K+ into cells)', exp: 'Correct. K+ 6.2 is initially elevated due to acidosis-driven shift out of cells. As acidosis corrects with insulin and fluids, K+ shifts back in and serum K+ drops fast. Standard approach: K+ over 5.2 = give insulin alone, monitor. K+ 3.3-5.2 = give insulin and add 20-40 mEq K to each L of fluid. K+ under 3.3 = HOLD insulin, replace K+ first to prevent arrhythmia.' },
        { text: 'Hold insulin until K+ normalizes on its own', exp: 'Doesnt fix the underlying problem. Insulin is what stops ketogenesis. Holding it makes the patient worse.' },
      ],
      correct: 2,
      exp: 'DKA potassium management: K+ falls fast as acidosis corrects and insulin drives it intracellularly. Pre-treatment K+ over 5.2: insulin and monitor. K+ 3.3-5.2: insulin plus add K+ to fluids. K+ under 3.3: hold insulin, replace K+ first. Cant give insulin without K+ on board - arrhythmia risk.',
      difficulty: 9,
      tags: ['dka', 'electrolytes'],
    },
    {
      id: 'me-3',
      q: '67-year-old male with sudden right-sided hemiparesis and aphasia 2 hours ago. NIHSS 14. BP 192/108. Non-contrast CT negative for hemorrhage. CTA shows left M1 occlusion. tPA criteria met. What is correct?',
      choices: [
        { text: 'Lower BP to under 140/90 before tPA', exp: 'Too aggressive. Pre-tPA BP target is under 185/110. Going to 140 may worsen penumbra perfusion and delay treatment. Each 15-minute delay in tPA increases mortality.' },
        { text: 'Lower BP to under 185/110 before tPA, then administer tPA, then thrombectomy', exp: 'Correct. Pre-tPA BP must be under 185/110 (post-tPA under 180/105). Labetalol or nicardipine. Once BP at target, give tPA. Large vessel occlusion (M1) on CTA also gets thrombectomy - DAWN/DEFUSE trials show benefit up to 24 hours with imaging selection. Both interventions are complementary.' },
        { text: 'Skip tPA, go directly to thrombectomy', exp: 'Modern protocols give both - tPA before or during transfer to thrombectomy center if eligible. Skipping tPA loses opportunity unless tPA contraindicated.' },
        { text: 'Permissive HTN up to 220/120, no BP lowering', exp: 'That is the strategy for ischemic stroke patients NOT receiving tPA. With tPA, must lower to under 185/110 to reduce hemorrhage risk.' },
      ],
      correct: 1,
      exp: 'Stroke BP management depends on intervention: 1) No tPA, ischemic: permissive HTN up to 220/120 (preserves penumbra). 2) Pre-tPA: under 185/110. 3) Post-tPA: under 180/105 for 24h. 4) Hemorrhagic stroke: target SBP 130-140. Large vessel occlusion = candidate for both tPA and thrombectomy.',
      difficulty: 9,
      tags: ['stroke', 'tpa'],
    },
    {
      id: 'me-4',
      q: '32-year-old female stung by bee. Now: stridor, lip/tongue swelling, hives, SBP 78, HR 132, wheezing. What is the correct first action and dose?',
      choices: [
        { text: 'Diphenhydramine 50 mg IV and methylprednisolone 125 mg IV', exp: 'Antihistamines and steroids are SECOND line in anaphylaxis. They do not save lives in the acute moment. Epi is the only thing that does.' },
        { text: 'Epinephrine 0.3-0.5 mg IM in the lateral thigh, repeat every 5-15 minutes if no response', exp: 'Correct. IM epi (1:1000, 0.3-0.5 mg) lateral thigh is the first and only life-saving intervention in anaphylaxis. Lateral thigh has best absorption. Repeat in 5-15 min if no response. Albuterol for bronchospasm, fluids for hypotension, antihistamines and steroids as adjuncts AFTER epi.' },
        { text: 'Epinephrine 1 mg IV push of 1:10,000', exp: 'IV epi is reserved for refractory shock or arrest. The 1 mg ACLS dose is far too high for awake anaphylaxis - can cause arrhythmia, MI, hypertensive crisis. IM is preferred initially.' },
        { text: 'High-flow O2, IV access, observe for 30 minutes', exp: 'Patient is dying. Observation kills. Epi now.' },
      ],
      correct: 1,
      exp: 'Anaphylaxis: epinephrine IM (NOT IV initially) lateral thigh, 0.3-0.5 mg of 1:1000, repeat q 5-15 min. Antihistamines and steroids are adjuncts. Biphasic reactions occur in 5-20% - observe at least 4-6 hours. Patients on beta-blockers may need glucagon.',
      difficulty: 7,
      tags: ['anaphylaxis'],
    },
    {
      id: 'me-5',
      q: '29-year-old known epileptic in a generalized tonic-clonic seizure for 12 minutes. IV access, glucose 96. Two doses of IV lorazepam 4 mg given without breaking the seizure. Next step?',
      choices: [
        { text: 'Third dose of lorazepam', exp: 'After two doses of benzo without resolution = refractory. Adding more benzo without escalating leads to respiratory depression and continued seizing.' },
        { text: 'Levetiracetam 60 mg/kg IV', exp: 'Correct. Status epilepticus algorithm: First-line benzo (max 2 doses). Second-line: levetiracetam 60 mg/kg, fosphenytoin 20 mg PE/kg, OR valproate 40 mg/kg. ESETT trial showed all three roughly equivalent. Third-line (refractory after 2 agents): intubate, propofol or midazolam infusion, EEG monitoring.' },
        { text: 'Phenobarbital 20 mg/kg IV bolus', exp: 'Phenobarbital is reserved for refractory cases (third-line after benzo + a second agent). Causes profound respiratory depression - usually requires intubation.' },
        { text: 'Neuromuscular blockade and intubation', exp: 'Paralysis stops physical movement but does NOT stop the brain from seizing. Patient continues to have neuronal damage. Intubation may be needed if airway compromised but paralytic alone is wrong move.' },
      ],
      correct: 1,
      exp: 'Status epilepticus pathway: 0-5 min: benzo (lorazepam 4 mg, midazolam 10 mg IM). 5-20 min: repeat benzo if needed. 20-40 min: second-line antiepileptic (keppra, fosphenytoin, valproate). 40+ min: refractory - intubate, infusion of propofol or midazolam, EEG. Glucose, electrolytes, tox screen, head CT to find cause.',
      difficulty: 8,
      tags: ['status-epilepticus'],
    },
    {
      id: 'me-6',
      q: '27-year-old, ingested unknown quantity of acetaminophen 6 hours ago, reportedly to harm self. Asymptomatic on arrival. AST 32, ALT 28, INR 1.0. 4-hour-equivalent acetaminophen level pending. Correct approach?',
      choices: [
        { text: 'Activated charcoal only - too late for NAC', exp: 'Charcoal at 6 hours has limited utility. NAC effectiveness extends well beyond 8 hours - never consider it too late based on time alone.' },
        { text: 'Discharge - patient is asymptomatic with normal labs', exp: 'Asymptomatic phase 1 is normal in acetaminophen toxicity. Liver damage develops at 24-72 hours. Discharging here is malpractice.' },
        { text: 'Start NAC empirically while awaiting level. Use Rumack-Matthew nomogram to plot the 4-hour-equivalent - if above treatment line, continue full course', exp: 'Correct. Acetaminophen has 4 phases: 1 (0-24h, asymptomatic), 2 (24-72h, AST rising, RUQ pain), 3 (72-96h, peak hepatotoxicity), 4 (recovery or death). Get a 4-hour-equivalent level (level drawn at or after 4 hours from ingestion). Plot on Rumack-Matthew. Above treatment line = full NAC course (150 mg/kg loading, 50 mg/kg over 4h, 100 mg/kg over 16h). NAC most effective within 8 hours, still beneficial up to 24+ hours.' },
        { text: 'Give NAC only if AST elevated', exp: 'AST may be normal in phase 1. Waiting until AST is elevated means waiting until liver damage has occurred. NAC is decided on level and time, not transaminases.' },
      ],
      correct: 2,
      exp: 'Acetaminophen toxicity: phase 1 asymptomatic for 24h. Get 4-hour-equivalent level, plot on Rumack-Matthew. Above treatment line = full NAC. NAC works best within 8h, still helps up to 24+. Late presenters with hepatic failure: continue NAC, evaluate for transplant per Kings College Criteria.',
      difficulty: 8,
      tags: ['toxicology', 'acetaminophen'],
    },
    {
      id: 'me-7',
      q: 'Tricyclic overdose. Patient seizing, then hypotensive, ECG shows wide QRS at 142 ms, HR 108, R wave in aVR 4 mm, BP 78/40. Most appropriate management?',
      choices: [
        { text: 'Sodium bicarbonate IV 1-2 mEq/kg bolus, target serum pH 7.5; benzodiazepines for seizure', exp: 'Correct. TCA toxicity: anticholinergic + cardiotoxic (Na+ channel blockade widens QRS, R in aVR over 3 mm) + seizure-prone. Bicarb overcomes Na+ blockade - narrows QRS. Target serum pH 7.45-7.55. Benzos for seizure (avoid phenytoin - also Na+ blocker, worsens cardiac toxicity). Norepinephrine for refractory hypotension (avoid epi - TCA blocks alpha, can paradoxically worsen). Lipid emulsion for cardiac arrest.' },
        { text: 'Phenytoin loading 20 mg/kg for seizure prophylaxis', exp: 'Phenytoin is a Na+ channel blocker - exactly what made TCA toxic. Worsens cardiac toxicity. Avoid in TCA OD.' },
        { text: 'Defibrillate the wide QRS', exp: 'Patient has a perfusing rhythm (BP 78/40, HR 108). Defibrillation is for VF/pulseless VT. Wrong intervention.' },
        { text: 'Push 1 amp epinephrine for hypotension', exp: 'Avoid epi in TCA OD - alpha blockade may give beta-only effect with paradoxical worsening. Norepi preferred. Bolus epi has no role in awake hypotension.' },
      ],
      correct: 0,
      exp: 'TCA overdose: bicarb is the antidote for cardiotoxicity. Wide QRS over 100 = give bicarb. Target pH 7.45-7.55. Avoid phenytoin (Na+ blocker), avoid epi (use norepi). Lipid emulsion for refractory cardiac toxicity. Seizure: benzos. Anticholinergic toxidrome: hot, dry, dilated, hallucinations.',
      difficulty: 9,
      tags: ['toxicology', 'tca'],
    },
    {
      id: 'me-8',
      q: 'Type 2 diabetic on metoprolol overdose intentionally. HR 38, BP 70/40, glucose 180, awake but lethargic. After atropine 1 mg without effect, what is the next intervention?',
      choices: [
        { text: 'Calcium chloride 1 g IV', exp: 'Calcium is more useful in CCB overdose than beta-blocker overdose. May have some effect but not the highest-yield first move.' },
        { text: 'Glucagon 5-10 mg IV bolus, then drip 2-5 mg/hr', exp: 'Correct. Glucagon bypasses the beta-receptor by activating adenylate cyclase directly through its own G-protein receptor. Increases cAMP, drives chronotropy and inotropy. Onset 5-10 minutes. Causes nausea/vomiting commonly. Bridge to high-dose insulin (1 U/kg bolus then 1-10 U/kg/hr with D50) for severe poisoning. Lipid emulsion for refractory.' },
        { text: 'Pacing immediately', exp: 'Pacing may be needed for refractory bradycardia but pharmacologic options not yet exhausted. Glucagon is the mechanism-specific antidote.' },
        { text: 'Norepinephrine drip', exp: 'Norepi useful but glucagon is mechanism-specific for beta-blocker. Higher yield first.' },
      ],
      correct: 1,
      exp: 'Beta-blocker overdose: atropine first, often fails. Glucagon is the mechanism-specific antidote (bypasses beta receptor). High-dose insulin (1 U/kg bolus then drip with dextrose) is mainstay for severe BB or CCB overdose. Lipid emulsion rescue for refractory. Pacing if drugs fail.',
      difficulty: 8,
      tags: ['toxicology', 'beta-blocker'],
    },
    {
      id: 'me-9',
      q: 'Found unconscious, RR 4, pinpoint pupils, suspected opioid overdose. IV access not immediately available. Best initial naloxone dose and route?',
      choices: [
        { text: 'IV 2 mg push as soon as access obtained', exp: 'Wait for IV access wastes time. IM/IN works. Also full 2 mg in chronic users precipitates withdrawal - start lower if known chronic use.' },
        { text: 'IM 0.4 mg or IN 4 mg now while establishing access', exp: 'Correct. With life-threatening respiratory depression, give naloxone immediately by any route - IM lateral thigh 0.4 mg or IN 4 mg work fast. IV access while youre at it. Subsequent doses can titrate. Goal is restoring breathing, not full reversal - full reversal precipitates withdrawal in chronic users (sympathetic surge, vomiting, agitation, pulmonary edema rare).' },
        { text: 'IM 2 mg', exp: 'Higher initial doses precipitate severe withdrawal, especially in chronic users. Start lower, titrate up.' },
        { text: 'BVM only and watch - naloxone may worsen the situation', exp: 'Naloxone is the antidote. Withholding it for someone with respiratory depression who needs the airway open is wrong.' },
      ],
      correct: 1,
      exp: 'Opioid overdose: naloxone IM 0.4 mg or IN 4 mg first while establishing IV access. Goal is breathing, not full reversal. In chronic users, lower doses (0.04-0.1 mg IV) titrated up avoids precipitated withdrawal. Half-life is shorter than most opioids (especially methadone, fentanyl) - observe 4-6 hours, drip if recurrent depression.',
      difficulty: 7,
      tags: ['toxicology', 'opioid'],
    },
    {
      id: 'me-10',
      q: '38-year-old with chronic kidney disease misses dialysis. K+ 7.4, ECG shows peaked T waves and QRS widening to 130 ms, HR 56. Hes alert. Most appropriate IMMEDIATE intervention?',
      choices: [
        { text: 'Calcium gluconate 1-2 g IV over 5-10 min', exp: 'Correct. Calcium does NOT lower K+ but stabilizes the myocardium - antagonizes the depolarizing effect of K+ at the cell membrane. Onset within minutes, effect lasts 30-60 minutes. Buys time for definitive K+-lowering therapy. ECG changes (peaked T, wide QRS, sine wave) drive urgency. Calcium chloride if central access (more concentrated), gluconate peripheral.' },
        { text: 'Insulin 10 U + D50 first', exp: 'Insulin and dextrose drive K+ into cells but takes 15-30 min to start dropping serum K+. With ECG changes, calcium first to prevent arrhythmia, then insulin/dextrose to actually lower K+.' },
        { text: 'Sodium polystyrene sulfonate (Kayexalate)', exp: 'Slow onset (hours), only lowers K+ modestly, controversial efficacy and bowel necrosis risk. Not for emergent hyperkalemia.' },
        { text: 'Bicarbonate 50 mEq IV', exp: 'Bicarb only useful in hyperkalemia with concurrent acidosis. Routine bicarb doesnt drive K+ in efficiently. Calcium first.' },
      ],
      correct: 0,
      exp: 'Hyperkalemia treatment ladder by mechanism: 1) Stabilize myocardium = calcium (does not lower K+). 2) Drive K+ into cells = insulin/dextrose, beta-2 agonist, bicarb if acidotic. 3) Eliminate K+ = lasix (if kidneys work), kayexalate (slow), DIALYSIS (definitive in renal failure). ECG changes drive urgency - calcium first.',
      difficulty: 8,
      tags: ['hyperkalemia'],
    },
    {
      id: 'me-11',
      q: '74-year-old marathon runner collapses at mile 22. Core temp 41.8C, AMS, HR 134, BP 88/52, RR 28. What is the FASTEST cooling method?',
      choices: [
        { text: 'Ice packs to neck, axilla, groin', exp: 'Helpful adjunct but slow. Cooling rate roughly 0.05C/min with packs alone.' },
        { text: 'Cold water/ice immersion (whole body in tub of ice water)', exp: 'Correct. Ice water immersion is the fastest method (cooling rate 0.15-0.35 C/min). Best for exertional heat stroke in young/healthy. Stop at 39C to avoid overshoot. Continuous monitoring required. Less feasible for elderly classic heat stroke (frail patients) - evaporative cooling (mist + fan) is preferred there.' },
        { text: 'Cold IV saline 2L bolus', exp: 'Cold IV fluids are an adjunct but cool too slowly to be the primary method.' },
        { text: 'Acetaminophen 1 g and tepid sponge baths', exp: 'Antipyretics dont work in heat stroke (this isnt fever from a hypothalamic setpoint, its environmental hyperthermia). Tepid water cools too slowly.' },
      ],
      correct: 1,
      exp: 'Heat stroke cooling methods (fastest to slowest): ice water immersion (best for exertional, young healthy), evaporative (mist + fan, best for elderly classic), cooling blanket, ice packs, cold IV fluids. Goal: 39C in 30 minutes or less. Stop cooling at 39C (avoid overshoot). Antipyretics dont work - this is hyperthermia, not fever.',
      difficulty: 8,
      tags: ['heat-stroke'],
    },
    {
      id: 'me-12',
      q: '63-year-old male presents with hematemesis and melena. BP 88/54, HR 124, Hgb 6.2, INR 1.8 (on warfarin), known cirrhosis. Most appropriate management bundle?',
      choices: [
        { text: '2L NS bolus, hold blood until type and cross', exp: 'Wrong. Active GI bleed with cirrhosis: blood, not crystalloid (worsens dilutional coagulopathy and ascites). Type O-neg or O-pos uncrossmatched if needed urgently.' },
        { text: 'PRBC, FFP/PCC for warfarin reversal, octreotide drip, ceftriaxone 1g, PPI drip, urgent endoscopy', exp: 'Correct. Cirrhotic with GI bleed: PRBC for Hgb under 7. FFP or PCC + vitamin K to reverse warfarin. Octreotide 50 mcg bolus then 50 mcg/hr - variceal bleeding suspected (cirrhosis). Antibiotics (ceftriaxone 1g) reduce mortality in cirrhotic GI bleed (prevents SBP and death). PPI drip for ulcer disease until source identified. Endoscopy within 12-24h, sooner for instability.' },
        { text: 'Massive crystalloid resuscitation, transfuse only after Hgb under 5', exp: 'Restrictive transfusion for stable patients but this patient has Hgb 6.2 and is hemodynamically unstable. Transfuse now.' },
        { text: 'No blood products until endoscopy is complete', exp: 'Cant safely scope an unstable hypotensive patient. Resuscitate first, then scope.' },
      ],
      correct: 1,
      exp: 'GI bleed management bundle: blood not crystalloid, reverse anticoagulation, PPI drip for upper UGIB, octreotide for variceal, antibiotics (ceftriaxone) for cirrhotic (reduces mortality), endoscopy within 24h. Hgb threshold 7 (8 in CAD). Two large-bore IVs.',
      difficulty: 8,
      tags: ['gi-bleed'],
    },
    {
      id: 'me-13',
      q: '46-year-old female with sudden severe headache that started 3 hours ago - said it was "worst of my life" and reached peak intensity within seconds. CT non-contrast is read as normal. What is the next appropriate step?',
      choices: [
        { text: 'Discharge home with migraine prescription', exp: 'Thunderclap headache without imaging confirmation of cause requires further workup. Subarachnoid hemorrhage can be missed on CT, especially after 6 hours.' },
        { text: 'CT angiogram of the head and neck looking for aneurysm', exp: 'Reasonable next step but doesnt rule out small bleed. With high suspicion (thunderclap, worst-of-life), LP is often required to truly rule out SAH.' },
        { text: 'Lumbar puncture looking for xanthochromia and RBCs that dont clear across tubes', exp: 'Correct. CT sensitivity for SAH drops below 95% after 6 hours from onset. Patient at 3 hours - CT highly sensitive but missed SAH still possible. Classic teaching: thunderclap + negative CT = LP. Findings: xanthochromia (yellow CSF from heme breakdown, takes 12 hours to develop), RBCs that DONT clear from tube 1 to tube 4 (consistent count = bleed; clearing count = traumatic tap).' },
        { text: 'MRI of the brain', exp: 'MRI is sensitive for SAH but not as quick or readily available. LP remains the standard followup after negative CT for thunderclap headache.' },
      ],
      correct: 2,
      exp: 'Thunderclap headache workup: CT first (sensitive 95%+ within 6h, drops after). If negative, LP for xanthochromia and persistent RBCs. CT angio for aneurysm characterization. Sentinel headaches may precede aneurysmal rupture. Nimodipine to prevent vasospasm. Coiling/clipping urgently for confirmed aneurysm.',
      difficulty: 8,
      tags: ['sah', 'headache'],
    },
    {
      id: 'me-14',
      q: '55-year-old presents with fever 39, neck stiffness, photophobia, AMS. CT shows no mass effect. Antibiotics started after blood cultures. What is the role and timing of dexamethasone?',
      choices: [
        { text: 'Give dexamethasone only after pathogen is identified', exp: 'Wrong. Steroids must be given BEFORE or concurrent with first antibiotic dose to be effective. Waiting for cultures (24-48h) loses the window.' },
        { text: 'Give dexamethasone 10 mg IV before or with first antibiotic dose', exp: 'Correct. Dexamethasone reduces mortality and neurologic sequelae in pneumococcal meningitis when given BEFORE or with first antibiotic dose. The mechanism: reducing the inflammatory response that occurs as bacteria lyse and release antigens. Timing is critical - given after antibiotics, the inflammatory cascade has already started. Continue 10 mg q6h for 4 days if pneumococcus confirmed.' },
        { text: 'Skip dexamethasone - only useful in viral meningitis', exp: 'Wrong indication. Dexamethasone is not used in viral meningitis. It IS used in bacterial (especially pneumococcal).' },
        { text: 'Dexamethasone is contraindicated in any meningitis', exp: 'False. Established benefit in pneumococcal bacterial meningitis if given on time.' },
      ],
      correct: 1,
      exp: 'Bacterial meningitis: dexamethasone 10 mg IV BEFORE or with first antibiotic dose reduces mortality and neuro sequelae in pneumococcal. After antibiotics, the inflammatory cascade has started and steroids do nothing. Empiric antibiotics: ceftriaxone + vancomycin; add ampicillin if over 50 or immunocompromised (Listeria).',
      difficulty: 7,
      tags: ['meningitis', 'steroids'],
    },
    {
      id: 'me-15',
      q: '78-year-old with chronic adrenal insufficiency on hydrocortisone 20 mg/day, develops pneumonia and is admitted. He misses his AM dose. Now: BP 78/52 refractory to 2L NS, HR 116, K+ 5.8, Na+ 128, glucose 60. Most likely diagnosis?',
      choices: [
        { text: 'Septic shock from pneumonia, treat with aggressive fluids and pressors', exp: 'Sepsis is part of the picture (pneumonia is the trigger) but the hyperkalemia, hyponatremia, and hypoglycemia in a known adrenal insufficient patient point to adrenal crisis specifically.' },
        { text: 'Adrenal crisis triggered by pneumonia and missed dose; give hydrocortisone 100 mg IV bolus', exp: 'Correct. Refractory hypotension + hyperK + hyponatremia + hypoglycemia in adrenal insufficient patient = adrenal crisis. Triggers: missed dose, infection, surgery, trauma. Treatment: hydrocortisone 100 mg IV bolus, then 50 mg q6h. Aggressive fluids. Treat the precipitant. Stress dose for any stressor in chronic steroid users - they cant make their own cortisol response.' },
        { text: 'Cardiogenic shock from MI', exp: 'Possible but the electrolyte pattern is classic for adrenal crisis. Get an ECG and trop but treat the most likely diagnosis empirically.' },
        { text: 'Hypoglycemia primary; give D50 and observe', exp: 'D50 doesnt fix the underlying adrenal crisis. Glucose will fall again without cortisol replacement.' },
      ],
      correct: 1,
      exp: 'Adrenal crisis: refractory hypotension + hyperK + hypoNa + hypoglycemia in adrenal-insufficient patient. Treatment: hydrocortisone 100 mg IV bolus then 50 mg q6h. Fluids, treat precipitant. Stress-dose steroids: any patient on chronic steroids (over 5 mg prednisone for over 3 weeks) needs stress dose for illness/surgery - they cant mount their own response.',
      difficulty: 9,
      tags: ['adrenal-crisis'],
    },
    {
      id: 'me-16',
      q: '32-year-old with Graves disease ran out of methimazole, now febrile 40.2, HR 168 in atrial fibrillation, BP 110/68, agitated, vomiting. Treatment ORDER:',
      choices: [
        { text: 'Iodine first, then thionamide, then beta-blocker', exp: 'Wrong order. Iodine before thionamide can WORSEN storm - it provides substrate for thyroid synthesis if thionamide hasnt yet blocked the synthesis pathway. Order matters.' },
        { text: 'Beta-blocker (propranolol or esmolol), then thionamide (PTU/methimazole), then iodine 1 hour after thionamide, then steroids', exp: 'Correct. Thyroid storm management ORDER: 1) Beta-blocker (propranolol 60-80 mg PO/IV or esmolol drip) - symptom control. 2) Thionamide (PTU 200-400 mg q4h or methimazole) - blocks new synthesis. 3) Iodine (potassium iodide or Lugol solution) - but at least 1 HOUR AFTER thionamide (Wolff-Chaikoff effect). Iodine before thionamide gives substrate for more hormone. 4) Hydrocortisone 100 mg q8h - blocks T4 to T3 conversion. 5) Cool, hydrate, treat trigger.' },
        { text: 'Steroids, then beta-blocker, then thionamide', exp: 'Steroids are useful but not the first-line symptom control or hormone-blocking step. Beta-blocker first for cardiac symptoms and adrenergic surge.' },
        { text: 'Antipyretics and IV fluids only - let storm self-limit', exp: 'Thyroid storm is high-mortality without treatment. Self-limiting only after exhaustion of thyroid stores. Active treatment is required.' },
      ],
      correct: 1,
      exp: 'Thyroid storm order: beta-blocker → thionamide → iodine (1 hour after thionamide) → steroids. Iodine before thionamide is dangerous - provides substrate for more hormone synthesis. Wolff-Chaikoff effect is the temporary block of release once iodine is given. Treat the trigger (infection, MI, surgery, missed meds). Mortality 10-30%.',
      difficulty: 9,
      tags: ['thyroid-storm'],
    },
    {
      id: 'me-17',
      q: '45-year-old with severe hyponatremia (Na+ 118) and seizures. Started 3% saline. The risk you must avoid is osmotic demyelination. Goal correction rate?',
      choices: [
        { text: 'No more than 20 mEq/L per 24 hours', exp: 'Too fast. Causes ODS especially in chronic hyponatremia. Maximum 8 (some say 10) per 24 hours.' },
        { text: 'No more than 8 mEq/L per 24 hours, no more than 18 per 48 hours', exp: 'Correct. Severe symptomatic hyponatremia: 3% saline 100-150 mL boluses to relieve cerebral edema (raise Na 4-6 mEq acutely). Then SLOW. Max 8 mEq/24h, 18 mEq/48h. Faster causes osmotic demyelination syndrome (ODS, formerly central pontine myelinolysis) - locked-in syndrome, often fatal. Chronic hyponatremia is more dangerous to overcorrect than acute.' },
        { text: '4 mEq per hour until normalization', exp: 'Way too fast. Would correct 96 mEq in 24 hours. Lethal demyelination.' },
        { text: 'Match the rate of the underlying water excess; no specific limit', exp: 'Wrong. Strict ceiling required to prevent ODS regardless of underlying mechanism.' },
      ],
      correct: 1,
      exp: 'Hyponatremia correction: severe symptomatic (seizure, coma) gets 3% saline 100-150 mL boluses to raise Na 4-6 mEq acutely (relieves edema). Then slow: max 8 mEq/24h, 18/48h. Overcorrection causes osmotic demyelination syndrome - locked-in, often fatal. If overcorrecting, give D5W or DDAVP to bring Na back down.',
      difficulty: 8,
      tags: ['hyponatremia', 'electrolytes'],
    },
    {
      id: 'me-18',
      q: '71-year-old in long-term care found unresponsive in cool room. T 28.5C, HR 38, BP 78/52, RR 8. Pulse weak, J wave (Osborn) on ECG. Most accurate management point?',
      choices: [
        { text: 'Standard ACLS if arrest occurs', exp: 'Below 30C, drugs and defibrillation are largely ineffective. Standard ACLS does not apply. Continue CPR while rewarming.' },
        { text: 'Active core rewarming; gentle handling to avoid triggering V-fib; hold pacing decisions until temp over 30C', exp: 'Correct. Severe hypothermia (under 28C is severe, under 30C dangerous). Active core rewarming: warm IV fluids, warm humidified O2, peritoneal/bladder lavage with warm saline, ECMO/CPB for arrest. Gentle handling - rough movement can trigger V-fib in cold heart. Pacing rarely works at this temp; rewarm first. If arrest: CPR, withhold drugs and limit shocks until 30C.' },
        { text: 'Aggressive surface rewarming with hot packs and ambulation', exp: 'Surface-only rewarming is for mild hypothermia. Severe needs core rewarming. Ambulation is contraindicated - afterdrop risk.' },
        { text: 'Atropine for the bradycardia', exp: 'Bradycardia in hypothermia is due to slow conduction in cold tissue, not vagal tone. Atropine doesnt fix it. Rewarming does.' },
      ],
      correct: 1,
      exp: 'Severe hypothermia: active core rewarming (warm IVF, warm humidified O2, peritoneal/bladder lavage, ECMO for arrest). Below 30C, drugs and defibrillation largely ineffective. Gentle handling - V-fib risk. Pulse check 60 seconds before declaring asystole. "Not dead until warm and dead" - neuro-intact survival reported below 14C with ECMO.',
      difficulty: 8,
      tags: ['hypothermia'],
    },
    {
      id: 'me-19',
      q: 'Cocaine-induced chest pain. ECG with ST elevations in II, III, aVF. BP 168/95, HR 124. What is contraindicated initially?',
      choices: [
        { text: 'Beta-blockers (specifically pure beta agents like metoprolol)', exp: 'Correct. Cocaine causes alpha-adrenergic vasoconstriction. Pure beta-blockade (metoprolol) leaves alpha unopposed - vasoconstriction worsens, BP rises further, coronary spasm worsens. Use benzos (lorazepam) for sympathetic surge, nitroglycerin and CCB for coronary vasodilation, aspirin for thrombus, heparin/PCI for true STEMI. Some experts use carvedilol or labetalol (mixed alpha/beta) safely; pure beta is the danger.' },
        { text: 'Aspirin', exp: 'Aspirin is appropriate for STEMI even with cocaine. Antiplatelet effect helps thrombus.' },
        { text: 'Nitroglycerin', exp: 'Nitro is helpful for cocaine-induced coronary spasm - vasodilator effect counters cocaines vasoconstriction.' },
        { text: 'Benzodiazepines', exp: 'Benzos are first-line for cocaine sympathetic surge. Reduce HR, BP, anxiety. Helpful, not contraindicated.' },
      ],
      correct: 0,
      exp: 'Cocaine chest pain: avoid pure beta-blockers (unopposed alpha = worsened vasoconstriction). Use benzos for sympathetic surge, nitro and CCBs for vasospasm, aspirin and heparin for thrombus. PCI for true STEMI. Carvedilol/labetalol (mixed) generally safe but pure beta is the classic teaching point.',
      difficulty: 8,
      tags: ['cocaine', 'chest-pain'],
    },
    {
      id: 'me-20',
      q: 'CO poisoning, COHb 32%, lethargic but responsive, mild metabolic acidosis. 100% O2 on NRB initiated. What additional therapy reduces delayed neuropsychiatric sequelae?',
      choices: [
        { text: 'Hyperbaric oxygen', exp: 'Correct. HBO indications: LOC, neuro deficit, COHb over 25%, pregnancy with COHb over 15%, severe acidosis, age over 35 with COHb over 20%, ischemic ECG. HBO reduces delayed neuropsychiatric sequelae (DNS) from 30% to 10%. Half-life of CO: 320 min on RA, 80 min on 100% O2, 23 min on hyperbaric.' },
        { text: 'Methylene blue', exp: 'Methylene blue treats methemoglobinemia, not CO. Wrong toxin.' },
        { text: 'Continuous albuterol', exp: 'Albuterol does nothing for CO. CO binds hemoglobin tighter than O2 - needs displacement (via high O2 concentrations) and time.' },
        { text: 'IV bicarbonate to correct the acidosis', exp: 'Acidosis from CO is a downstream effect of tissue hypoxia. Bicarb doesnt fix the cause.' },
      ],
      correct: 0,
      exp: 'CO poisoning: high-flow O2 via NRB. HBO indications: LOC, neuro deficit, COHb over 25%, pregnancy with COHb over 15%, severe acidosis, age over 35 with COHb over 20%, ischemic ECG. HBO reduces delayed neuropsychiatric sequelae (memory, mood, cognition issues 2-4 weeks post-exposure) from 30% to 10%.',
      difficulty: 7,
      tags: ['co-poisoning'],
    },
    {
      id: 'me-21',
      q: '40-year-old male recovering from intentional aspirin overdose (level 95 mg/dL on arrival). pH 7.18, becoming somnolent, RR dropping from 32 to 10, intubation team is at bedside. Most accurate caution?',
      choices: [
        { text: 'Standard RSI with rocuronium and propofol - proceed normally', exp: 'Wrong. Salicylate-poisoned patients are using respiratory alkalosis to compensate for severe metabolic acidosis. Apnea during RSI eliminates the compensation. pH crashes. Cardiac arrest can result.' },
        { text: 'Avoid intubation if at all possible; if intubating, hyperventilate deliberately to maintain compensation, prepare bicarb push, dialysis ready', exp: 'Correct. Salicylate uses respiratory alkalosis (RR 30+) to offset severe metabolic acidosis. Intubating and ventilating at "normal" rate eliminates compensation - pH crashes, cardiac arrest. If intubation unavoidable: minimize apnea, ventilate aggressively to mimic patients prior minute ventilation, push bicarb, set up emergent dialysis. Salicylate level over 100 with AMS, pulmonary edema, refractory acidosis, or renal failure = dialysis.' },
        { text: 'Permissive hypercapnia post-intubation', exp: 'Permissive hypercapnia in salicylate is suicidal. Acidemia drives more salicylate into CNS, worsens toxicity, can cause arrest.' },
        { text: 'Sedation only, no paralysis, allow patient to assist breathing', exp: 'Sedation in this state may eliminate compensation. Worsens acidosis.' },
      ],
      correct: 1,
      exp: 'Salicylate intubation: avoid if possible, very dangerous. Apnea during RSI eliminates compensatory hyperventilation, pH crashes, arrest. If intubation unavoidable: aggressive hyperventilation, bicarb on board, emergent dialysis. Alkalinize urine for excretion (target urine pH over 7.5). Dialysis for level over 100 with severe symptoms, AMS, pulmonary edema, refractory acidosis, renal failure.',
      difficulty: 9,
      tags: ['salicylate', 'intubation'],
    },
    {
      id: 'me-22',
      q: 'Diabetic patient on glipizide (sulfonylurea) presents with hypoglycemia (glucose 38), responds to D50. 30 minutes later, glucose 48 again. Best disposition?',
      choices: [
        { text: 'Discharge with instructions to eat a meal', exp: 'Sulfonylurea half-life is long (glipizide ~12 hours). Recurrent hypoglycemia is the rule. Discharging is dangerous.' },
        { text: 'Admit, dextrose drip, octreotide consideration', exp: 'Correct. Sulfonylurea-induced hypoglycemia recurs for many hours due to long half-life and active metabolites. Single dextrose bolus drives more insulin release (sulfonylureas stimulate beta cells), causing rebound hypoglycemia. Admit, D5W or D10W drip, octreotide can suppress insulin release in refractory cases (50 mcg SQ q8h).' },
        { text: 'Glucagon IM and discharge', exp: 'Glucagon doesnt fix the underlying problem of ongoing insulin release. Patient will become hypoglycemic again.' },
        { text: 'Repeat D50 boluses every 30 minutes as outpatient', exp: 'Sulfonylurea hypoglycemia is an admission. Outpatient management is unsafe.' },
      ],
      correct: 1,
      exp: 'Sulfonylurea hypoglycemia: ALWAYS admit. Long half-life, active metabolites, recurrent hypoglycemia for hours. Dextrose drip until off the drug. Octreotide for refractory (suppresses insulin release at beta cell). Insulin overdose is shorter-acting; sulfonylureas keep going.',
      difficulty: 7,
      tags: ['hypoglycemia', 'sulfonylurea'],
    },
    {
      id: 'me-23',
      q: 'Severe asthma exacerbation, post-arrest, intubated. Vent shows rising peak pressures, BP dropping. ETCO2 climbing. Disconnect from ventilator and you hear a loud rush of air, BP improves. Diagnosis?',
      choices: [
        { text: 'Tension pneumothorax', exp: 'Tension pneumo doesnt resolve by simply disconnecting the vent - would still need decompression. Hearing air rush from disconnect points elsewhere.' },
        { text: 'Auto-PEEP (breath stacking)', exp: 'Correct. Severe asthma/COPD with mechanical ventilation: insufficient time to fully exhale before next breath. Air stacks. Lungs hyperinflate. Pressure rises. Venous return drops. BP falls. Can cause PEA arrest. Treatment: DISCONNECT from vent, push on chest to force exhalation, then ventilate slowly (6-8/min) with long expiratory time (1:4 or 1:5 I:E ratio). Permissive hypercapnia is OK here (hypercapnia preferred over barotrauma).' },
        { text: 'Mucus plug', exp: 'Mucus plug raises peak pressure and resistance but doesnt produce the disconnect-and-rush-of-air pattern characteristic of breath stacking.' },
        { text: 'ETT migration into right main bronchus', exp: 'Mainstem intubation causes asymmetric breath sounds and high pressures but disconnecting wouldnt produce a rush of air.' },
      ],
      correct: 1,
      exp: 'Auto-PEEP in obstructive lung disease on the vent: exhalation too slow, air stacks, hyperinflation, pressure rises, venous return drops, BP falls, PEA. Disconnect, push on chest, slow rate (6-8), long expiratory time (1:4-1:5 I:E), permissive hypercapnia. Avoid extubation until bronchospasm resolved.',
      difficulty: 9,
      tags: ['auto-peep', 'asthma'],
    },
    {
      id: 'me-24',
      q: 'Diving emergency - diver had sudden onset right arm weakness, slurred speech, and chest pain immediately upon surfacing from a 60-foot dive. Most likely diagnosis and treatment?',
      choices: [
        { text: 'Decompression sickness - high-flow O2 and hyperbaric chamber', exp: 'Decompression sickness ("the bends") presents 30 min - 24 hours after surfacing, joint pain, fatigue, neurologic. The IMMEDIATE post-surfacing onset of stroke-like symptoms is more consistent with arterial gas embolism.' },
        { text: 'Arterial gas embolism - left lateral decubitus, high-flow O2, EMERGENT hyperbaric oxygen therapy', exp: 'Correct. Arterial gas embolism (AGE): sudden symptoms IMMEDIATELY upon or within minutes of surfacing. Air enters arterial circulation through pulmonary barotrauma (breath-holding while ascending). Symptoms depend on where embolism lodges: stroke-like, chest pain, shock. Treatment: 100% O2 (washes out nitrogen, accelerates absorption), left lateral decubitus head-down (Trendelenburg) to keep emboli from cerebral circulation, EMERGENT hyperbaric for definitive treatment. Even severe AGE can fully recover with prompt HBO.' },
        { text: 'Stroke - tPA', exp: 'Diving context with immediate onset = AGE until proven otherwise. tPA in suspected AGE could worsen if there is a primary pulmonary barotrauma component.' },
        { text: 'Cardiac arrest from cold water immersion - ACLS', exp: 'Patient is symptomatic, not arrested. AGE is the more likely diagnosis.' },
      ],
      correct: 1,
      exp: 'Arterial gas embolism: sudden symptoms immediately or within minutes of surfacing. Pulmonary barotrauma from breath-holding ascent. Treat with 100% O2, left lateral decubitus, emergent HBO. Decompression sickness has delayed onset (30 min - 24h), joint pain, neurologic. Both treated with HBO. Time-critical.',
      difficulty: 9,
      tags: ['diving', 'age'],
    },
    {
      id: 'me-25',
      q: 'Suspected botulism in 4 patients from a shared meal of home-canned green beans. Initial findings: descending bilateral cranial nerve weakness, diplopia, dysphagia, dysarthria. Mental status preserved, no fever. Most appropriate management?',
      choices: [
        { text: 'IV antibiotics (penicillin) and discharge', exp: 'Antibiotics treat WOUND botulism but not foodborne. Discharge with descending paralysis is dangerous - respiratory failure can develop in hours.' },
        { text: 'Botulism antitoxin from CDC, ICU admission, monitor for respiratory failure (FVC, NIF), early intubation if declining', exp: 'Correct. Foodborne botulism: descending bilateral symmetric paralysis from cranial nerves down. Mental status spared (toxin doesnt cross BBB). No fever (its a toxin, not infection). Treatment: equine-derived heptavalent antitoxin (BAT) from CDC - most effective if given early, even before lab confirmation. ICU monitoring with serial spirometry (FVC, NIF). Intubate when FVC under 20 mL/kg, NIF less negative than -20, or clinical decline. Antitoxin neutralizes circulating toxin only - already-bound toxin must wear off (months for nerve terminal regeneration).' },
        { text: 'Plasmapheresis to remove circulating toxin', exp: 'Plasmapheresis is not standard. Antitoxin binds circulating toxin directly.' },
        { text: 'Steroids to reduce inflammation', exp: 'Botulism is a toxin-mediated paralysis, not inflammatory. Steroids dont help.' },
      ],
      correct: 1,
      exp: 'Foodborne botulism: descending symmetric paralysis from cranial nerves down. Mental status spared. No fever. Treatment: heptavalent botulism antitoxin (BAT) from CDC. ICU, serial pulmonary function monitoring, intubation before respiratory failure. Antitoxin only neutralizes circulating toxin - bound toxin requires nerve terminal regeneration (months).',
      difficulty: 9,
      tags: ['botulism', 'paralysis'],
    },
  ],
}
