import type { Category } from './types'

export const OBPEDS: Category = {
  id: 'obpeds',
  name: 'OB, Pediatrics & Special Populations',
  short: 'OB/Peds',
  desc: 'Obstetric emergencies, neonatal resuscitation, pediatric assessment, geriatric considerations, age-specific dosing and physiology.',
  color: '#ec4899',
  icon: 'cross',
  flashcards: [
    { id: 'op-fc-1', front: 'APGAR score components and timing', back: 'Appearance (color), Pulse (HR), Grimace (reflex irritability), Activity (muscle tone), Respiration. Each 0-2, total 0-10. Assessed at 1 min and 5 min. Score under 7 at 5 min repeat every 5 min until 20 min. APGAR does NOT drive resuscitation decisions - HR and respiratory effort do. Treat the baby, not the score.' },
    { id: 'op-fc-2', front: 'Neonatal resuscitation HR thresholds', back: 'Above 100: routine care, dry, warm, stimulate. 60-100: PPV at 40-60 breaths/min, recheck in 30 sec. Below 60: continue PPV + chest compressions at 3:1 ratio (90 compressions + 30 breaths/min = 120 events/min). Below 60 after 30 sec of coordinated CPR: epi 0.01-0.03 mg/kg IV/IO (ETT 0.05-0.1 mg/kg only if no access).' },
    { id: 'op-fc-3', front: 'Newborn vs infant CPR ratio difference', back: 'Newborn (first 28 days, especially in delivery room): 3:1 (compressions:breaths) because the problem is almost always asphyxia/hypoxia. Infant after newborn period: 30:2 single rescuer, 15:2 two rescuer. The 3:1 emphasizes ventilation because newborn arrest is respiratory in origin, not cardiac.' },
    { id: 'op-fc-4', front: 'Pediatric vital signs by age (rough rules)', back: 'HR: newborn 100-160, 1y 100-150, 3y 90-140, 6y 80-120, 10y 70-110, teen 60-100. RR: newborn 30-60, 1y 25-40, 3y 20-30, 6y 18-25, 10y 14-22. SBP minimum: 70 + (2 x age in years) for ages 1-10. Below this = hypotension. Newborn SBP minimum ~60. Tachycardia is the FIRST sign of shock in peds; hypotension is a LATE, pre-arrest finding.' },
    { id: 'op-fc-5', front: 'Pediatric Glasgow Coma Scale modifications', back: 'Verbal in pre-verbal child: 5 = coos/babbles, 4 = irritable cry, 3 = cries to pain, 2 = moans to pain, 1 = none. Motor: same as adult above 1y. AVPU is faster and arguably better in field peds. Any decrease in mental status in a child is highly significant - kids compensate well until they crash.' },
    { id: 'op-fc-6', front: 'Pediatric airway anatomy - what is different', back: 'Larger occiput (head flexes forward - put towel UNDER shoulders, not head, to align). Larger tongue relative to mouth. Higher, more anterior larynx (C3-C4 vs C5-C6 in adult). Floppy U-shaped epiglottis (use straight Miller blade in infants). Cricoid is narrowest point (under 8y) - cuffed tubes once standard but still common. Trachea is short - easy to right-mainstem.' },
    { id: 'op-fc-7', front: 'Age cutoffs for IO access landmarks', back: 'Proximal tibia: all ages. Distal femur: under 12y typically. Proximal humerus: any age but adult use most common. Distal tibia: any age. EZ-IO needle sizes: pink 15mm (3-39 kg), blue 25mm (over 40 kg), yellow 45mm (excess tissue or humerus). Confirm placement: needle stands without support, marrow aspirate, flush flows without resistance.' },
    { id: 'op-fc-8', front: 'Epi pediatric dosing - anaphylaxis vs arrest', back: 'Anaphylaxis IM: 0.01 mg/kg of 1 mg/mL (1:1000), max 0.3 mg child / 0.5 mg adult, lateral thigh. Arrest IV/IO: 0.01 mg/kg of 0.1 mg/mL (1:10,000) every 3-5 min. ETT route (last resort): 0.1 mg/kg of 1:1000. The concentration changes between routes - this is where errors happen. Always state both dose AND concentration.' },
    { id: 'op-fc-9', front: 'Pediatric defibrillation energy', back: 'First shock: 2 J/kg. Subsequent shocks: 4 J/kg, may escalate to 10 J/kg or adult dose, whichever is lower. Synchronized cardioversion: 0.5-1 J/kg first, then 2 J/kg. Adult AED with peds pads acceptable down to 1 year if peds dose attenuator unavailable. Under 1y: manual defib preferred; AED if its all you have.' },
    { id: 'op-fc-10', front: 'PALS bradycardia algorithm trigger', back: 'HR under 60 with poor perfusion in child = start CPR. This is unique to peds - adults with HR 50 and poor perfusion get atropine/pacing. In peds, bradycardia almost always = hypoxia. Fix the airway/oxygenation FIRST. If HR still under 60 with CPR ongoing: epi 0.01 mg/kg. Atropine only for vagal-mediated brady or AV block (rare).' },
    { id: 'op-fc-11', front: 'Pediatric assessment triangle (PAT)', back: 'Three sides: Appearance (mental status, tone, look/gaze, speech/cry), Work of Breathing (positioning, retractions, abnormal sounds, nasal flaring), Circulation to Skin (pallor, mottling, cyanosis). Abnormal in any side = sick kid. Used in first 30 seconds without touching the patient. Drives initial impression and treatment urgency.' },
    { id: 'op-fc-12', front: 'Croup vs epiglottitis vs bacterial tracheitis', back: 'Croup: viral, 6mo-3yr, barking cough, gradual, child looks ok between coughs, low fever. Tx: dex + racemic epi if stridor at rest. Epiglottitis: bacterial, sudden, high fever, drooling, no cough, tripod, toxic. NEVER agitate or look at throat. Bacterial tracheitis: viral prodrome then bacterial superinfection, high fever, toxic, copious purulent secretions, stridor not relieved by epi. All three can need surgical airway.' },
    { id: 'op-fc-13', front: 'SIDS vs ALTE vs BRUE', back: 'SIDS: sudden death in infant under 1y, unexplained after investigation. ALTE (apparent life-threatening event): old term, replaced by BRUE. BRUE (brief resolved unexplained event): under 1y, lasted under 1 min, resolved, with apnea, color change, tone change, or altered responsiveness. Lower-risk BRUE may be discharged with reassurance and follow-up; higher-risk gets admission.' },
    { id: 'op-fc-14', front: 'Child abuse red flags', back: 'Inconsistent or changing history, history not matching injury (mechanism implausible for development), delay in seeking care, injuries in multiple stages of healing, patterned bruises (loop, hand, belt buckle), bruises on torso/ear/neck under 4y, fractures in non-ambulating infant, posterior rib fractures, retinal hemorrhages (shaken baby). Mandatory reporter - not your job to investigate, your job to report.' },
    { id: 'op-fc-15', front: 'Eclampsia management', back: 'Magnesium sulfate 4-6 g IV over 15-20 min, then 1-2 g/hr. Treats AND prevents seizures in pre-eclampsia. Watch for mag toxicity: loss of DTRs (first sign), respiratory depression, then cardiac. Antidote: calcium gluconate 1 g IV. Definitive treatment of eclampsia is delivery. Control BP with labetalol or hydralazine if SBP over 160. Do NOT give a benzo unless mag fails.' },
    { id: 'op-fc-16', front: 'Postpartum hemorrhage causes - the 4 Ts', back: 'Tone (uterine atony - most common, 70%): treat with fundal massage + oxytocin 10 U IM or 20-40 U/L IV. Trauma (lacerations, episiotomy, rupture): direct repair. Tissue (retained products): manual removal, may need OR. Thrombin (coagulopathy): blood products, TXA 1 g IV. PPH = over 500 mL vaginal or over 1000 mL C-section. Massive transfusion if continuing.' },
    { id: 'op-fc-17', front: 'Cord prolapse management', back: 'Visible cord at introitus = OB emergency. DO NOT push cord back in (causes vasospasm). Place mom in knee-chest or extreme Trendelenburg. Examiner inserts gloved hand to elevate presenting part off the cord. Cover cord with warm saline-soaked gauze. Rapid transport to OR for emergent C-section. Monitor cord pulsations - that is fetal life.' },
    { id: 'op-fc-18', front: 'Shoulder dystocia maneuvers (HELPERR mnemonic)', back: 'Help (call for it). Evaluate for episiotomy. Legs (McRoberts - flex thighs to abdomen). Pressure (suprapubic, NEVER fundal - fundal worsens it). Enter (rotational maneuvers). Remove posterior arm. Roll over (Gaskin maneuver, hands and knees). McRoberts + suprapubic pressure resolves 50%+ of cases. Time-critical: brachial plexus injury and asphyxia within minutes.' },
    { id: 'op-fc-19', front: 'Newborn meconium aspiration management', back: 'OLD teaching: routine intubation and tracheal suctioning of meconium-stained babies. CURRENT (NRP 2015+): if vigorous (good tone, breathing/crying, HR over 100) - routine care. If non-vigorous (poor tone, apneic, HR under 100) - start PPV; intubate and suction only if PPV is ineffective and obstruction suspected. Do not routinely suction the trachea.' },
    { id: 'op-fc-20', front: 'Ectopic pregnancy presentation and management', back: 'Classic triad: amenorrhea + abdominal pain + vaginal bleeding (only ~50%). Ruptured ectopic = surgical emergency: severe abdominal pain, hypotension, tachycardia, peritoneal signs, possible referred shoulder pain (Kehr sign - diaphragmatic blood). Any positive pregnancy test with abdominal pain or syncope = ectopic until proven otherwise. Two large-bore IVs, fluid, blood, OR.' },
    { id: 'op-fc-21', front: 'Placenta previa vs abruption - distinguish', back: 'Previa: PAINLESS bright red bleeding, often after intercourse or out of nowhere. NEVER do a vaginal exam - can cause catastrophic hemorrhage. Abruption: PAINFUL, dark blood (or none if concealed), rigid/tender uterus, fetal distress, often with trauma, cocaine, hypertension, smoking. Both are obstetric emergencies. Both go to OR for stabilization or delivery.' },
    { id: 'op-fc-22', front: 'Geriatric trauma - why they crash without warning', back: 'Beta-blockers blunt tachycardic response - normal HR can mean shock. Anticoagulants turn small bleeds into big ones. Decreased physiologic reserve - cannot compensate for blood loss like a young patient. Atypical presentations: minor falls cause major fractures (osteoporosis); subdural hematomas from minor head bumps. Lower threshold for transport to trauma center.' },
    { id: 'op-fc-23', front: 'Fall from standing in 80yo - how to think about it', back: 'Mechanism is misleading. Standing falls in elderly cause: hip fractures, c-spine injuries, subdural hematomas (especially on anticoagulants), pelvic fractures with major hemorrhage. Always c-spine. Always blood-thinner check. Always full assessment. The history matters: did they trip (mechanical) or did they pass out (cardiac, neuro, syncope workup)? Big difference.' },
    { id: 'op-fc-24', front: 'Pediatric burn - TBSA estimation', back: 'Adult Rule of 9s does not apply to peds - head is proportionally bigger, legs smaller. Use Lund-Browder chart for accuracy, or palmar method (pts palm including fingers = 1% TBSA) for scattered burns. Parkland for peds: 3-4 mL/kg/% TBSA in first 24 hours, half in first 8 hours. ADD maintenance fluids (D5LR). Use weight-based, not adult math.' },
    { id: 'op-fc-25', front: 'Pediatric maintenance fluid rate (4-2-1 rule)', back: 'First 10 kg: 4 mL/kg/hr. Next 10 kg: 2 mL/kg/hr. Each additional kg: 1 mL/kg/hr. Example: 25 kg child = 40 + 20 + 5 = 65 mL/hr. For boluses in shock: 20 mL/kg isotonic crystalloid, reassess, repeat up to 60 mL/kg. After 60 mL/kg without response, consider blood and pressors. Septic shock peds may need 40-60 mL/kg early.' },
    { id: 'op-fc-26', front: 'Febrile seizure characteristics and red flags', back: 'Simple febrile seizure: 6mo-5yr, generalized, under 15 min, one episode in 24hr, normal neuro exam after. Reassurance, rule out source. Complex: focal, over 15 min, recurrent within 24hr, abnormal neuro exam - needs workup (LP if under 12 months, CT if focal). Status epilepticus = over 5 min or two seizures without recovery. Treat actively seizing kid as status - do not wait.' },
    { id: 'op-fc-27', front: 'Pediatric DKA - why slow down', back: 'Cerebral edema is the killer in peds DKA - happens hours into treatment, not at presentation. Risk factors: aggressive fluid bolus, rapid sodium drop, bicarb administration, young age, severe acidosis. Rules: bolus only if shock (10 mL/kg, max 20 over first hour), then maintenance. Insulin 0.05-0.1 U/kg/hr AFTER fluids started. NO bicarb. Watch for headache, altered mental status, bradycardia + hypertension (Cushing).' },
    { id: 'op-fc-28', front: 'Geriatric medication considerations', back: 'Polypharmacy is normal - get the bottle list. Anticoagulants (warfarin, DOACs) turn falls into ICH/internal hemorrhage. Beta-blockers blunt shock response. Diuretics + dehydration = baseline volume depleted. Anticholinergics cause delirium. Decreased renal/hepatic clearance - drug doses often need reduction. Beers Criteria identifies high-risk drugs in elderly.' },
    { id: 'op-fc-29', front: 'Bariatric airway and access challenges', back: 'Airway: ramp the patient (shoulders/head elevated to align ear with sternal notch - CRITICAL for view). Apneic oxygenation mandatory. Faster desaturation due to lower FRC and higher metabolic demand. Drug dosing: lean body weight for most induction agents; succinylcholine uses total body weight. IV access: ultrasound often needed; IO is your friend.' },
    { id: 'op-fc-30', front: 'Pregnant trauma patient - top priorities', back: 'Best fetal resuscitation = good maternal resuscitation. After 20 weeks: left lateral tilt or manual uterine displacement to relieve IVC compression. RhoGAM if Rh-negative and any abdominal trauma. Higher fluid requirement - pregnant patients have 30-50% expanded blood volume so they hide blood loss. Perimortem C-section at 4 minutes of arrest in viable pregnancy (24+ weeks) - for the mom, not just the baby.' },
  ],
  scenarios: [
    {
      id: 'op-1',
      q: 'A 32-week pregnant woman in MVC, restrained driver. BP 100/60, HR 118, RR 24. Abdomen tender, fundus palpable above umbilicus. Bright red vaginal bleeding. What is the MOST appropriate immediate action besides standard trauma care?',
      choices: [
        { text: 'Vaginal exam to assess source of bleeding', exp: 'Wrong and dangerous. Never do a vaginal exam in a pregnant trauma patient with bleeding until placenta previa is ruled out (typically by ultrasound). Vaginal exam in previa can cause catastrophic hemorrhage. Bleeding workup in pregnancy is OB-driven.' },
        { text: 'Place patient in left lateral decubitus position or perform manual left uterine displacement', exp: 'Correct. After 20 weeks, the gravid uterus compresses the IVC in supine position, dropping cardiac output by up to 30%. Left lateral tilt or manual displacement of the uterus to the patient left restores venous return. This is one of the highest-yield maternal interventions in trauma.' },
        { text: 'Administer tocolytics to stop possible labor', exp: 'Wrong. Tocolytics in trauma can mask the maternal/fetal status and may worsen outcomes. The priority is maternal stabilization. OB makes tocolytic decisions in-hospital, not pre-hospital.' },
        { text: 'Withhold IV fluids until vital signs trend down further', exp: 'Wrong. Pregnant patients have expanded blood volume (30-50%) and HIDE blood loss. By the time BP drops they have lost 30%+ of volume. HR 118 in this patient is already a shock signal. Aggressive resuscitation is needed for both mom and baby.' },
      ],
      correct: 1,
      exp: 'Best fetal resuscitation IS good maternal resuscitation. Left lateral tilt addresses IVC compression, the most common reversible cause of hemodynamic compromise in late pregnancy. Painful bleeding + tender uterus + trauma = abruption.',
      difficulty: 8,
      tags: ['ob-trauma', 'positioning'],
    },
    {
      id: 'op-2',
      q: 'A 6-month-old presents lethargic, mottled, cap refill 5 seconds, HR 195, RR 60, palpating only central pulses. Mom says 2 days of vomiting and diarrhea. Weight 7 kg. What is your INITIAL fluid bolus?',
      choices: [
        { text: '10 mL/kg of 0.9% NS over 60 min = 70 mL', exp: 'Wrong. Both the volume and the rate are inadequate for compensated shock progressing to decompensation. PALS calls for 20 mL/kg pushed in over 5-10 minutes for fluid-responsive shock.' },
        { text: '20 mL/kg of 0.9% NS over 5-10 min = 140 mL, reassess, repeat up to 60 mL/kg', exp: 'Correct. Standard PALS pediatric shock bolus is 20 mL/kg of isotonic crystalloid pushed (not slow infused), reassess after each, can repeat up to 60 mL/kg. After 60 mL/kg without improvement, blood and pressors enter the picture. Distinct from neonatal (10 mL/kg) and DKA (slow approach).' },
        { text: 'D5W 20 mL/kg over 20 min', exp: 'Wrong solution. D5W is hypotonic relative to plasma and unsuitable for resuscitation - it shifts free water into cells and worsens hemodynamics. Use isotonic crystalloid (NS or LR) for shock.' },
        { text: '40 mL/kg of NS over 20 min as a single push', exp: 'Wrong approach. Bolus 20 mL/kg, then REASSESS before the next bolus. Stacking 40 mL/kg without reassessment risks fluid overload, especially in pediatric DKA, cardiogenic shock, or severe anemia where the pathology differs from simple hypovolemia.' },
      ],
      correct: 1,
      exp: 'Pediatric shock = 20 mL/kg isotonic, fast push, reassess, repeat up to 60 mL/kg. Tachycardia + delayed cap refill + lethargy + central-only pulses = decompensated shock. Treat aggressively.',
      difficulty: 7,
      tags: ['peds-shock', 'fluids'],
    },
    {
      id: 'op-3',
      q: 'Term newborn delivered in the field. After drying and stimulation: not breathing, HR 80, peripheral cyanosis. You start PPV at 40 breaths/min with room air. After 30 seconds of effective PPV, HR is 50. What is your NEXT step?',
      choices: [
        { text: 'Continue PPV and add chest compressions at 3:1 ratio', exp: 'Correct. NRP algorithm: HR under 60 after 30 sec of effective PPV = start chest compressions at 3:1 ratio (90 compressions + 30 breaths/min, totaling 120 events/min). Increase FiO2 to 100% at this point. Reassess HR every 60 seconds.' },
        { text: 'Push epinephrine 0.01 mg/kg IV', exp: 'Wrong sequence. Epi comes AFTER 30+ seconds of coordinated PPV + chest compressions if HR remains under 60. Going to epi before compressions skips the algorithm.' },
        { text: 'Intubate immediately', exp: 'Not the immediate next step. PPV is effective if chest is rising. NRP allows time on bag-mask before intubation. If PPV ineffective, optimize MR SOPA (Mask, Reposition, Suction, Open mouth, Pressure increase, Airway) before intubating.' },
        { text: 'Switch to 30:2 CPR ratio', exp: 'Wrong ratio for newborn. 30:2 is for adults and beyond newborn period in peds with single rescuer. Newborns use 3:1 because their arrests are almost universally asphyxial - ventilation matters more.' },
      ],
      correct: 0,
      exp: 'NRP HR thresholds: above 100 = routine, 60-100 = PPV, under 60 = PPV + compressions. The 3:1 ratio reflects that newborn arrest is respiratory not cardiac.',
      difficulty: 7,
      tags: ['neonatal', 'resuscitation'],
    },
    {
      id: 'op-4',
      q: 'A 28-week pregnant patient calls EMS for severe headache and visual changes. BP 188/118, HR 92. She has 4+ pitting edema in her legs and brisk reflexes. While transporting, she has a generalized tonic-clonic seizure. What is the FIRST-LINE drug?',
      choices: [
        { text: 'Lorazepam 2 mg IV', exp: 'Wrong first line. Benzos can stop the seizure short-term but do not address the underlying eclamptic process. Mag is both anticonvulsant and prevents recurrence in eclampsia. Benzos are reserved for status if mag fails.' },
        { text: 'Magnesium sulfate 4-6 g IV over 15-20 min, then infusion 1-2 g/hr', exp: 'Correct. Magnesium is FIRST line for eclamptic seizure - it stops AND prevents recurrence. The mechanism is unclear but it works specifically in this physiology. Watch for toxicity: loss of DTRs (first sign), respiratory depression, then cardiac. Antidote: calcium gluconate 1 g IV.' },
        { text: 'Phenytoin 20 mg/kg IV load', exp: 'Wrong drug for this etiology. Phenytoin has been studied head-to-head with mag in eclampsia and is INFERIOR. It does not address the eclamptic pathophysiology and adds cardiac/hemodynamic risk.' },
        { text: 'Hydralazine 10 mg IV', exp: 'Wrong priority. The seizure must be controlled first. After mag is loaded, BP control with labetalol or hydralazine is appropriate for SBP over 160. Lowering BP without seizure control does not help and may worsen placental perfusion.' },
      ],
      correct: 1,
      exp: 'Eclamptic seizure = mag first, BP control second, definitive treatment is delivery. Pre-eclampsia warning signs: HTN, edema, headache, visual changes, brisk reflexes. Catch it before the seizure if you can.',
      difficulty: 7,
      tags: ['ob-emergency', 'eclampsia'],
    },
    {
      id: 'op-5',
      q: 'A 4-year-old, 18 kg, in cardiac arrest. ETT in place, IO access. After 2 minutes of CPR, rhythm check shows VF. You defibrillate at 2 J/kg = 36 J. Persistent VF. CPR resumes. What is your NEXT defibrillation dose?',
      choices: [
        { text: '36 J again (same dose)', exp: 'Wrong. PALS specifies escalation after first shock. Second shock is 4 J/kg, which doubles the energy delivered.' },
        { text: '4 J/kg = 72 J', exp: 'Correct. PALS pediatric defibrillation: first shock 2 J/kg, subsequent shocks 4 J/kg, may escalate up to 10 J/kg or adult dose, whichever is lower. Escalation reflects evidence that higher energy improves shock conversion in refractory VF.' },
        { text: '10 J/kg = 180 J', exp: 'Premature jump. Ten J/kg is the upper ceiling, considered after multiple unsuccessful shocks at 4 J/kg, not as the second shock.' },
        { text: 'Adult dose 200 J biphasic', exp: 'Wrong principle. Pediatric defibrillation is weight-based until you exceed adult equivalent. At 18 kg, the standardized peds dose (4 J/kg = 72 J) is appropriate. Adult biphasic doses (120-200 J) would be acceptable only when peds calculation exceeds them.' },
      ],
      correct: 1,
      exp: 'Pediatric defib: 2 J/kg first, 4 J/kg subsequent, up to 10 J/kg or adult dose. Memorize the escalation; under stress this is where errors happen.',
      difficulty: 7,
      tags: ['peds-arrest', 'defibrillation'],
    },
    {
      id: 'op-6',
      q: 'A 2-year-old with abrupt onset stridor, drooling, refuses to lie down, fever 104, no cough, looks toxic, sitting in tripod position. SpO2 89% RA. Mom says symptoms started 4 hours ago. What is the SAFEST initial action?',
      choices: [
        { text: 'Visualize the throat with a tongue blade to assess swelling', exp: 'Wrong and potentially fatal. Examining the throat in suspected epiglottitis can trigger laryngospasm and complete airway obstruction. NEVER look in the throat. NEVER lie them down. NEVER agitate.' },
        { text: 'Keep child calm in mom arms, sitting upright, blow-by O2, expedite transport, alert receiving facility for OR setup', exp: 'Correct. Suspected epiglottitis: minimize stimulation, mom holds them, sit upright (their position of comfort), blow-by O2 (do not force a mask), transport rapidly to facility prepared for controlled airway in OR with anesthesia and ENT. IVs and procedures wait until they have an airway.' },
        { text: 'Insert IV and start dexamethasone for airway swelling', exp: 'Wrong priority. IV insertion will agitate the child and may precipitate complete airway obstruction. The airway is the priority, and that is established in the OR. Dex/racemic epi is for croup not epiglottitis.' },
        { text: 'Attempt intubation in the back of the truck', exp: 'Wrong setting and timing. Field intubation of epiglottitis is high-risk - distorted anatomy, swollen tissues, easy to make worse. Unless the airway is closing in front of you, transport to controlled environment.' },
      ],
      correct: 1,
      exp: 'Epiglottitis = hands off until you are at the OR. Minimize anything that agitates the kid. The disease has become rare since Hib vaccine but still happens, and missing it kills in minutes.',
      difficulty: 7,
      tags: ['peds-airway', 'epiglottitis'],
    },
    {
      id: 'op-7',
      q: 'You arrive at a scene where a baby was just delivered in the bathroom. Crowning was visible 30 sec before delivery. Cord is around the neck once, loose. Baby is term, blue, limp, not breathing, HR 90. You have completed warming, drying, and stimulation. What is next?',
      choices: [
        { text: 'Suction the airway with bulb syringe', exp: 'Wrong unless obvious obstruction. Routine suctioning is no longer recommended in vigorous OR non-vigorous newborns unless there is obstruction to PPV. It causes vagal bradycardia and delays effective ventilation.' },
        { text: 'Begin PPV at 40-60 breaths/min with room air', exp: 'Correct. NRP: a non-vigorous newborn (apneic + HR under 100) gets PPV at 40-60/min. Start with room air (21% FiO2) for term newborns; titrate up based on SpO2 targets and HR response. The cord nuchal loop has already been resolved.' },
        { text: 'Start chest compressions immediately', exp: 'Wrong threshold. HR 90 is between 60 and 100 - that means PPV, not compressions. Compressions begin if HR stays under 60 after 30 seconds of effective PPV.' },
        { text: 'Push 0.01 mg/kg epinephrine IO', exp: 'Skips the algorithm. Epi comes only after 30+ seconds of coordinated PPV + chest compressions if HR remains under 60. PPV is the first intervention.' },
      ],
      correct: 1,
      exp: 'Newborn HR thresholds: over 100 routine, 60-100 PPV, under 60 PPV + compressions. Apnea + HR 90 = ventilation problem. Get air in.',
      difficulty: 6,
      tags: ['neonatal', 'NRP'],
    },
    {
      id: 'op-8',
      q: 'A 9-month-old, 8 kg, in PEA arrest. CPR underway, IO placed. Per PALS, what is the appropriate epi dose and concentration via IO?',
      choices: [
        { text: '0.01 mg/kg of 1 mg/mL (1:1000) = 0.08 mg', exp: 'Wrong concentration. The 1:1000 (1 mg/mL) concentration is for IM use in anaphylaxis. Pushing it IV/IO would deliver 10x the intended dose and is a known fatal error.' },
        { text: '0.01 mg/kg of 0.1 mg/mL (1:10,000) = 0.08 mg', exp: 'Correct. IV/IO arrest dose is 0.01 mg/kg of 0.1 mg/mL (1:10,000) every 3-5 minutes. For 8 kg = 0.08 mg = 0.8 mL. Always state both dose AND concentration to avoid the 1:1000 vs 1:10,000 mix-up.' },
        { text: '0.1 mg/kg of 0.1 mg/mL (1:10,000) = 0.8 mg', exp: 'Wrong dose multiplier. IV/IO dose is 0.01 mg/kg, not 0.1 mg/kg. The 0.1 mg/kg dose is the ETT dose (last resort, 1:1000 down the tube), which has been de-emphasized due to poor absorption.' },
        { text: '1 mg IV push (adult dose)', exp: 'Wrong concept. Pediatric dosing is weight-based, never adult dose for an infant. The 1 mg adult dose would be 100x overdose for this 8 kg baby.' },
      ],
      correct: 1,
      exp: 'Peds arrest epi: 0.01 mg/kg of 1:10,000 IV/IO every 3-5 min. Always say both dose AND concentration. Concentration confusion kills kids.',
      difficulty: 8,
      tags: ['peds-arrest', 'med-math'],
    },
    {
      id: 'op-9',
      q: 'A 78yo F on warfarin (INR yesterday 2.8) trips on a rug, hits her head on coffee table. No LOC. Now 4 hours later her family calls because she is "not herself" - confused, slow speech, mild left arm weakness. BP 168/92, HR 58, GCS 13. What is the PRIMARY concern?',
      choices: [
        { text: 'Acute ischemic stroke needing TPA evaluation', exp: 'Possible but not the LEADING concern given the hit-and-blood-thinner mechanism. Even small head impacts on anticoagulants commonly produce delayed intracranial bleeding. Imaging will sort this out.' },
        { text: 'Subdural or other intracranial hemorrhage from head trauma on anticoagulation', exp: 'Correct. Elderly + anticoagulants + head impact + delayed neurologic decline = ICH (subdural especially) until proven otherwise. The "lucid interval" is classic. HR 58 + HTN + altered mental status raises Cushing reflex concern. Reverse anticoagulation (4-factor PCC, vitamin K) and transport to neurosurgery-capable center.' },
        { text: 'TIA, will resolve on its own', exp: 'Dangerous assumption in this context. Even if it were a TIA, anticoagulated head trauma demands imaging. "Will resolve" is not a plan.' },
        { text: 'Hypoglycemia', exp: 'Worth checking but not the lead diagnosis. Always check glucose in altered mental status, but the trauma + anticoagulation history must drive imaging and reversal pathway.' },
      ],
      correct: 1,
      exp: 'Old + on blood thinners + head impact + late neurologic change = ICH until proven otherwise. The fall mechanism gets discounted because it sounds minor - that is the mistake. Always check glucose; always image; always consider reversal.',
      difficulty: 7,
      tags: ['geriatric', 'head-injury'],
    },
    {
      id: 'op-10',
      q: 'A G4P3 woman at 39 weeks calls 911 with strong contractions every 2 min. On exam, you see the umbilical cord protruding from the introitus, with weak pulsations. What is the MOST appropriate intervention?',
      choices: [
        { text: 'Gently push the cord back into the vagina', exp: 'Wrong and harmful. Pushing the cord back causes vasospasm and worsens fetal hypoxia. Manage cord prolapse by relieving pressure on it, not by replacing it.' },
        { text: 'Place patient in knee-chest or extreme Trendelenburg, gloved hand into vagina to lift presenting part off the cord, cover cord with warm saline gauze, expedite transport for emergent C-section', exp: 'Correct. Cord prolapse is one of the few absolute pre-hospital obstetric emergencies. The goal is to relieve compression on the cord. Knee-chest position uses gravity. Inserting a hand to elevate the presenting part directly takes pressure off. Cover the cord with warm saline gauze (not dry gauze - drying causes vasospasm). Transport rapidly to OR.' },
        { text: 'Encourage pushing to deliver the baby vaginally as quickly as possible', exp: 'Wrong. Vaginal delivery with prolapsed cord crushes the cord and asphyxiates the fetus. Definitive treatment is C-section. Delaying delivery while taking pressure off the cord IS the play.' },
        { text: 'Clamp and cut the cord to prevent further pulsation', exp: 'Catastrophic. Cutting the cord disconnects the fetus from oxygen entirely. The cord supplies fetal oxygenation until the baby is out and breathing - clamping it before delivery is fatal to the baby.' },
      ],
      correct: 1,
      exp: 'Cord prolapse = relieve cord compression, do NOT push it back, do NOT cut it. Transport for C-section. The hand-elevating-presenting-part technique stays in place all the way to the OR.',
      difficulty: 7,
      tags: ['ob-emergency', 'cord-prolapse'],
    },
    {
      id: 'op-11',
      q: 'A 5-year-old, 20 kg, found seizing for the past 8 minutes. No history of seizures. Temp 104.2°F. IV access not yet obtained. What is the BEST first medication and route?',
      choices: [
        { text: 'Lorazepam 0.1 mg/kg IV = 2 mg IV', exp: 'Right drug class but wrong route for a kid without IV access mid-seizure. IV access during active seizure wastes time. Use IM or intranasal route until IV is in place.' },
        { text: 'Midazolam 0.2 mg/kg IM or IN = 4 mg IM/IN', exp: 'Correct. Midazolam IM (or intranasal at 0.2 mg/kg) works in 5-10 minutes without needing IV access. RAMPART trial showed IM mid is non-inferior to IV lorazepam. For ongoing peds seizure without IV, this is the move. Continue trying for IV/IO simultaneously.' },
        { text: 'Phenobarbital 20 mg/kg IV = 400 mg', exp: 'Wrong drug for first-line. Phenobarbital is third-line in pediatric status (after benzo failure and second-line agent like fosphenytoin or levetiracetam). Also requires IV access this patient does not have yet.' },
        { text: 'Wait for IV access before giving any medication', exp: 'Wrong. Status epilepticus = active seizing over 5 min OR two seizures without recovery between. Eight minutes seizing is status. Treat with available route immediately. Each minute of seizure increases neurologic injury.' },
      ],
      correct: 1,
      exp: 'Pediatric status, no IV: midazolam IM/IN is first line. Treat fast, do not wait for access. Status = brain injury accumulating every minute.',
      difficulty: 7,
      tags: ['peds-seizure', 'status'],
    },
    {
      id: 'op-12',
      q: 'A primigravid 17-year-old at 36 weeks delivers a vigorous baby in the field. After delivery of the placenta you note continuous bright red bleeding from the vagina. Uterine fundus feels boggy and is at the umbilicus. EBL is now ~800 mL. What is the FIRST intervention?',
      choices: [
        { text: 'Aggressive bimanual fundal massage', exp: 'Correct. Postpartum hemorrhage causes are the 4 Ts. Tone (atony) is the most common (70%). Boggy fundus = atony. First intervention is fundal massage to stimulate contraction. Most atony resolves with vigorous massage. Add oxytocin 10 U IM or 20-40 U/L IV simultaneously.' },
        { text: 'Tranexamic acid 1 g IV', exp: 'Reasonable adjunct (WOMAN trial supports TXA early in PPH) but not the FIRST intervention. Mechanical (massage) and oxytocin come first. TXA is added if bleeding continues.' },
        { text: 'Pack the uterus with gauze', exp: 'Field-impractical and not first-line. Uterine packing or balloon tamponade are inpatient interventions for refractory atony or trauma source. Massage first.' },
        { text: 'IV crystalloid bolus only, transport without massage', exp: 'Treats the hemodynamics but ignores the source. Bleeding continues until tone is restored. Volume + massage + oxytocin together.' },
      ],
      correct: 0,
      exp: 'Boggy uterus + bleeding = atony. 4 Ts: Tone, Trauma, Tissue, Thrombin. Massage + oxytocin first. TXA as adjunct. Volume in parallel.',
      difficulty: 7,
      tags: ['ob-emergency', 'pph'],
    },
    {
      id: 'op-13',
      q: 'A 10-month-old with a 3-day history of fever, vomiting and diarrhea. Now lethargic. Sunken fontanelle, dry mucous membranes, no tears, cap refill 4 sec, HR 180, RR 50, SBP 70. Weight 8 kg. What is the BEST initial fluid?',
      choices: [
        { text: '0.9% NS 20 mL/kg over 5-10 min = 160 mL', exp: 'Correct. Decompensated dehydration/shock in peds = 20 mL/kg isotonic crystalloid pushed over 5-10 minutes, reassess, repeat. NS or LR are both fine. Avoid hypotonic fluids in initial resuscitation. Reassess after each bolus.' },
        { text: 'D5 0.45% NS 20 mL/kg over 60 min', exp: 'Wrong fluid choice. Hypotonic dextrose-containing fluids belong in maintenance, not in shock resuscitation. Hypotonic fluids in shock can cause hyponatremia and worsen cerebral edema risk.' },
        { text: 'Lactated Ringers 60 mL/kg as a single bolus over 10 min', exp: 'Wrong volume per push. The dose is 20 mL/kg per bolus with reassessment between. Stacking 60 mL/kg without reassessment risks fluid overload, particularly in occult cardiogenic shock or DKA.' },
        { text: 'Oral rehydration only - patient is too unstable for IV', exp: 'Wrong reasoning. Decompensated shock requires IV/IO. Oral rehydration is for mild-moderate dehydration in alert kids who can drink. This patient is lethargic with poor perfusion.' },
      ],
      correct: 0,
      exp: 'Pediatric shock: 20 mL/kg isotonic, fast push, reassess, repeat up to 60 mL/kg. Iso first, dextrose later for maintenance. Volume status first, then sugar.',
      difficulty: 6,
      tags: ['peds-shock', 'dehydration'],
    },
    {
      id: 'op-14',
      q: 'During a difficult delivery, the head delivers but the shoulders do not advance with the next contraction. Turtle sign present. What is the FIRST maneuver?',
      choices: [
        { text: 'Apply firm fundal pressure', exp: 'Wrong and harmful. Fundal pressure WORSENS shoulder dystocia by impacting the anterior shoulder further against the symphysis. Suprapubic pressure is the correct adjacent maneuver, NOT fundal.' },
        { text: 'McRoberts maneuver - sharply flex maternal thighs to abdomen', exp: 'Correct. McRoberts is the first maneuver in HELPERR mnemonic and resolves 40-50% of shoulder dystocias alone. Combined with suprapubic pressure, it resolves over 50%. It rotates the symphysis cephalad and frees the impacted shoulder.' },
        { text: 'Cut a generous episiotomy and pull harder on the head', exp: 'Wrong. Episiotomy is part of HELPERR but is no longer routinely recommended (it does not relieve the bony obstruction). Excess traction on the head causes brachial plexus injury - the most feared complication.' },
        { text: 'Push the head back in (Zavanelli maneuver) and proceed to C-section', exp: 'Wrong sequence. Zavanelli is the LAST resort if all other maneuvers fail. McRoberts and suprapubic come first.' },
      ],
      correct: 1,
      exp: 'HELPERR: Help, Episiotomy assessment, Legs (McRoberts), Pressure (suprapubic, never fundal), Enter, Remove posterior arm, Roll. McRoberts first and almost always works with suprapubic.',
      difficulty: 7,
      tags: ['ob-emergency', 'shoulder-dystocia'],
    },
    {
      id: 'op-15',
      q: 'An 84yo F nursing home patient. Caregiver reports increased confusion over 24 hours, no fever. BP 96/58, HR 108, RR 22, SpO2 94%. Glucose 102. UA shows pyuria. What is the most likely cause and best management?',
      choices: [
        { text: 'Worsening dementia, no acute treatment needed', exp: 'Wrong. Acute change in mental status is NOT progression of dementia - it is delirium and demands a workup. Attributing acute change to dementia is a common, dangerous error.' },
        { text: 'Urosepsis, likely with relative hypotension (her usual BP is higher) - fluids, antibiotics urgent, transport', exp: 'Correct. Elderly often present atypically - UTI in geriatrics often manifests as confusion alone, no fever, no dysuria. Tachycardia + relative hypotension (compared to her baseline, often 140s/80s) + pyuria = urosepsis. Early fluids and antibiotics save lives. Geriatric "afebrile sepsis" is real - they often cannot mount a fever.' },
        { text: 'Likely TIA, monitor and transport non-emergent', exp: 'Possible differential but does not fit the global confusion picture and pyuria finding. Geriatric "altered" with infectious source much more common. Even if TIA, the workup is urgent.' },
        { text: 'Hypoglycemia - give D50', exp: 'Glucose is 102, normal. D50 is contraindicated in non-hypoglycemic patients (causes hyperglycemia, can worsen ischemic injury in stroke).' },
      ],
      correct: 1,
      exp: 'Geriatric infection often presents as confusion without fever. Compare BP to BASELINE (their 96/58 may be 50 mmHg below their usual). Treat early. Atypical presentations are the rule, not the exception.',
      difficulty: 7,
      tags: ['geriatric', 'sepsis'],
    },
    {
      id: 'op-16',
      q: 'A 3-week-old presents with projectile non-bilious vomiting after feeds for 3 days, weight loss, and a palpable "olive" mass in the right upper quadrant. What is the most likely diagnosis and the expected acid-base disturbance?',
      choices: [
        { text: 'Pyloric stenosis with hypochloremic, hypokalemic metabolic alkalosis', exp: 'Correct. Classic presentation of hypertrophic pyloric stenosis: 3-6 week old, projectile non-bilious vomiting (because obstruction is BEFORE the bile duct entry into duodenum), weight loss, hungry after vomiting. Loss of HCl in vomitus = hypochloremic metabolic alkalosis. Compensatory K and H shifts cause hypokalemia and paradoxic aciduria. Surgery is curative (pyloromyotomy).' },
        { text: 'Duodenal atresia with metabolic acidosis', exp: 'Wrong age and wrong vomit. Duodenal atresia presents in the first day or two of life with bilious vomiting (obstruction is past the bile duct). Acidosis is not characteristic.' },
        { text: 'Necrotizing enterocolitis with metabolic acidosis', exp: 'Wrong demographic. NEC primarily affects premature infants in the NICU, not term 3-week-olds at home. Presents with abdominal distention, bloody stools, sepsis.' },
        { text: 'Intussusception with mixed acid-base picture', exp: 'Wrong age and presentation. Intussusception peaks 3-12 months, classic triad of intermittent severe abdominal pain (drawing knees up), currant jelly stools, palpable sausage-shaped mass. Not projectile vomiting at 3 weeks.' },
      ],
      correct: 0,
      exp: 'Pyloric stenosis: 3-6 weeks old, projectile non-bilious, hungry, olive mass, hypochloremic hypokalemic metabolic alkalosis. The acid-base story comes from losing stomach acid in the vomitus.',
      difficulty: 8,
      tags: ['peds-gi', 'pyloric-stenosis'],
    },
    {
      id: 'op-17',
      q: 'A 5-year-old with sickle cell disease presents febrile (102), tachypneic (RR 38), with a new infiltrate on chest x-ray and SpO2 89%. What is this and what is the immediate priority?',
      choices: [
        { text: 'Acute chest syndrome - high-flow O2, pain control, antibiotics, fluid (cautiously), transfusion considered, possible exchange transfusion', exp: 'Correct. ACS is the leading cause of death in sickle cell. Triad: fever, respiratory symptoms, new pulmonary infiltrate. Causes: infection, fat emboli from bone infarct, atelectasis. Treatment: O2, broad-spectrum abx (cefotaxime + azithro), incentive spirometry/positive pressure, simple or exchange transfusion based on severity. Watch BP, do NOT over-transfuse fluids - pulmonary edema risk.' },
        { text: 'Simple pneumonia - outpatient antibiotics and discharge', exp: 'Wrong management for sickle cell + new pulmonary infiltrate. ACS is a sickle cell emergency, not a simple pneumonia. They look the same on CXR but the management and disposition differ dramatically.' },
        { text: 'Asthma exacerbation - albuterol and steroids', exp: 'Wrong differential lead. While asthma can coexist, the picture here (fever, infiltrate, SpO2 drop in a sickle cell kid) is ACS until proven otherwise.' },
        { text: 'Pulmonary embolism - anticoagulation and CT', exp: 'Possible adult-style differential but not the immediate first thought in a sickle cell kid with fever and infiltrate. ACS umbrella covers most of these.' },
      ],
      correct: 0,
      exp: 'ACS = fever + respiratory + new infiltrate in sickle cell. Leading cause of death in sickle cell. Treat aggressively. Be cautious with fluids - pulmonary edema is real here.',
      difficulty: 8,
      tags: ['peds-hematology', 'sickle-cell'],
    },
    {
      id: 'op-18',
      q: 'A 2-month-old presents with intermittent inconsolable crying drawing knees to chest, started 6 hours ago, now passing dark red mucousy stool. Abdomen has a vague RUQ mass. What is the most likely diagnosis and the key concern if untreated?',
      choices: [
        { text: 'Intussusception - bowel telescopes, can lead to ischemia, perforation, peritonitis, death', exp: 'Correct. Classic presentation: 3 months to 3 years (peak 6-12 months), intermittent severe abdominal pain (knees to chest), currant jelly stools (mucus + blood), palpable sausage-shaped mass. Diagnosis: ultrasound (target sign). Treatment: air or contrast enema reduction (60-90% successful), surgery if reduction fails or perforation suspected. Untreated = ischemia, perf, death within 24-48 hours.' },
        { text: 'Constipation', exp: 'Wrong. Constipation does not cause currant jelly stools or intermittent severe pain with knee-drawing. The mass is also against constipation alone.' },
        { text: 'Colic', exp: 'Wrong demographic and presentation. Colic is unexplained crying typically peaking at 6 weeks, not associated with bloody stools, masses, or stool changes.' },
        { text: 'Volvulus', exp: 'Volvulus also presents acutely but typically has bilious emesis as the lead symptom (not currant jelly stool), and is more typical in newborns/early infancy with malrotation. Worth considering, but intussusception fits this picture better.' },
      ],
      correct: 0,
      exp: 'Intussusception classic: 3mo-3yr, intermittent crying drawing legs up, currant jelly stool, sausage mass. Time-critical - bowel ischemia within 24-48 hours.',
      difficulty: 7,
      tags: ['peds-gi', 'intussusception'],
    },
    {
      id: 'op-19',
      q: 'A 25yo G2P1 woman at 38 weeks calls 911 with sudden severe abdominal pain, dark vaginal bleeding ~200 mL, rigid tender uterus. BP 88/58, HR 130. Fetal movement decreased. What is the most likely diagnosis and the priority?',
      choices: [
        { text: 'Placenta previa - keep her flat, do vaginal exam to assess', exp: 'Wrong on both counts. Previa is PAINLESS, BRIGHT red bleeding. Painful + dark + rigid uterus = abruption. NEVER do vaginal exams in third-trimester bleeding pre-hospital regardless.' },
        { text: 'Placental abruption - large-bore IV access, fluid, blood activation, left lateral tilt, rapid transport for emergent C-section', exp: 'Correct. Painful, dark blood, rigid tender uterus, hemodynamic instability, possibly concealed hemorrhage = abruption. This is an obstetric emergency for both mom and baby. Two large-bore IVs, fluid, activate massive transfusion at receiving facility, left lateral tilt to address IVC compression, expedite for delivery.' },
        { text: 'Uterine rupture - emergent laparotomy', exp: 'Possible especially with prior C-section. Presents similarly. Differentiation often requires imaging or surgery. The pre-hospital management is identical: IVs, fluid, blood, rapid transport. So while uterine rupture is on the differential, abruption is statistically more likely without surgical history.' },
        { text: 'Normal labor - observe', exp: 'Wrong. Severe pain, bleeding, hypotension, tachycardia, decreased fetal movement is not normal labor. This is decompensating obstetric hemorrhage.' },
      ],
      correct: 1,
      exp: 'Placenta abruption: painful, dark, rigid uterus, fetal distress, often concealed bleeding. Previa: painless, bright red. Both go to OR. Mom and baby both at risk.',
      difficulty: 7,
      tags: ['ob-emergency', 'abruption'],
    },
    {
      id: 'op-20',
      q: 'An 18-month-old, 12 kg, ingested an unknown number of grandma blood pressure pills 30 minutes ago. Now bradycardic (HR 60), BP 70/40, blood glucose 38. What overdose pattern fits, and what is the SECOND-LINE treatment after standard ACLS approaches?',
      choices: [
        { text: 'Beta-blocker overdose - high-dose insulin/euglycemia therapy', exp: 'Correct. Bradycardia + hypotension + HYPOGLYCEMIA strongly suggests beta-blocker (propranolol classically causes hypoglycemia in kids). Calcium channel blocker overdose causes HYPERglycemia (insulin secretion is calcium-dependent). After atropine, glucagon, calcium, and pressors, high-dose insulin (1 U/kg bolus then 0.5-1 U/kg/hr) with dextrose infusion is the next major step.' },
        { text: 'Calcium channel blocker overdose - same approach', exp: 'Almost. CCB overdose presents similarly but with HYPERglycemia from blocked insulin release. Hypoglycemia here points more strongly toward beta-blocker. Treatment principles overlap but the metabolic clue is the differentiator.' },
        { text: 'Digoxin overdose - Digibind', exp: 'Possible if pill identification fits. Digoxin overdose: nausea, vomiting, brady, hyperkalemia, classic "scooped" ST depression. Digibind is specific. Hypoglycemia is not characteristic of dig.' },
        { text: 'Clonidine overdose - naloxone', exp: 'Clonidine causes brady, hypotension, miosis, mental status changes - sometimes responds to naloxone in high doses. Hypoglycemia is not typical. Not the best fit.' },
      ],
      correct: 0,
      exp: 'Beta-blocker = brady + hypotension + HYPOglycemia. CCB = brady + hypotension + HYPERglycemia. Both treated with calcium, glucagon, pressors, high-dose insulin therapy. Lipid emulsion is rescue.',
      difficulty: 9,
      tags: ['peds-tox', 'beta-blocker'],
    },
    {
      id: 'op-21',
      q: 'A 15-year-old with new-onset diabetes presents in DKA: pH 7.10, glucose 580, ketones large, K 5.8, somnolent. Weight 50 kg. What is your initial fluid strategy?',
      choices: [
        { text: 'Bolus 40 mL/kg over 30 minutes, then start insulin and bicarb', exp: 'Wrong on multiple counts. Aggressive bolus + bicarb in pediatric DKA increases cerebral edema risk - the leading cause of death. No bicarb. No aggressive bolus unless in shock. NS at maintenance + replacement after a more measured initial bolus.' },
        { text: 'NS 10 mL/kg over 1 hour ONLY if shock present, otherwise start with 1.5x maintenance NS, then insulin 0.05-0.1 U/kg/hr after fluid started, NEVER bolus insulin', exp: 'Correct. Pediatric DKA management is deliberately slow to prevent cerebral edema: gentle hydration (no aggressive boluses unless shocked), insulin started AFTER fluids initiated, no bolus insulin (bolus drops glucose too fast and worsens edema risk), no bicarb. Watch for headache + altered mental status + bradycardia + hypertension = cerebral edema.' },
        { text: 'D5W 20 mL/kg/hr to flush ketones', exp: 'Wrong fluid. D5W is hypotonic and worsens cellular swelling. Free water shifts in is exactly what we are trying to avoid in cerebral edema.' },
        { text: 'Bolus insulin 0.1 U/kg followed by drip', exp: 'Wrong. Bolus insulin is contraindicated in pediatric DKA. The drop in glucose and osmolarity is too fast and increases cerebral edema risk. Insulin drip only.' },
      ],
      correct: 1,
      exp: 'Peds DKA = slow and steady. Cerebral edema is the killer. No aggressive bolus, no bicarb, no bolus insulin. Watch for the warning signs: headache, AMS, brady + HTN.',
      difficulty: 9,
      tags: ['peds-endocrine', 'DKA'],
    },
    {
      id: 'op-22',
      q: 'A 75yo M with COPD on home O2 has a fall, hits his chest on a railing. SpO2 88% on his usual 2L NC, BP 92/58, RR 28, asymmetric chest expansion with crepitus on the left. He is confused. What is your initial action?',
      choices: [
        { text: 'Increase his O2 to 6L NC and titrate to SpO2 88-92%, prepare for needle decompression of the left chest if signs progress, IV fluid carefully, rapid trauma transport', exp: 'Correct. Multi-layered geriatric trauma with possible pneumothorax. Hypoxia worse than baseline + asymmetric chest + crepitus + hypotension = high suspicion for pneumothorax (possibly tension developing). Treat hypoxia (do not withhold O2 from a confused hypoxic patient because of CO2 retention concerns), prepare for decompression, fluid carefully (cautious in cardiac/respiratory comorbid), expedite transport.' },
        { text: 'Withhold supplemental O2 to avoid suppressing his hypoxic drive', exp: 'Wrong. The hypoxic drive theory is overhyped. Real risks of high O2 in COPD are V/Q mismatch and atelectasis. NEVER withhold O2 from a hypoxic patient. Titrate to 88-92%. Hypoxia kills faster than hypercapnia.' },
        { text: 'Position supine with head down to improve perfusion', exp: 'Wrong for a respiratory compromised patient. Supine reduces lung expansion. Head-down can worsen ventilation. Position of comfort, often semi-Fowler, is better.' },
        { text: 'Bolus 2 L crystalloid quickly', exp: 'Wrong volume for an elderly cardiopulmonary-compromised patient. Risk of fluid overload and worsening respiratory status. Use small boluses (250-500 mL) and reassess.' },
      ],
      correct: 0,
      exp: 'Geriatric chest trauma: hypoxic + asymmetric + crepitus = think pneumothorax. Give O2 (88-92% target). Cautious fluids. Fast transport. The "don T give O2 to COPD" rule is wrong in a hypoxic, decompensating patient.',
      difficulty: 8,
      tags: ['geriatric', 'chest-trauma'],
    },
    {
      id: 'op-23',
      q: 'A pregnant patient at 35 weeks arrests in the back of the ambulance. CPR started immediately, IV access obtained. After 4 minutes of CPR with no ROSC, what time-sensitive intervention should happen?',
      choices: [
        { text: 'Continue CPR and standard ACLS only - pregnancy does not change the algorithm', exp: 'Wrong. Pregnancy after 20 weeks has unique considerations: IVC compression, perimortem C-section consideration, modified airway management. Standard ACLS is NOT the whole answer.' },
        { text: 'Manual left uterine displacement throughout CPR; if no ROSC by 4 min, perimortem C-section at 5 min for both maternal AND fetal benefit (improves maternal venous return)', exp: 'Correct. After 20 weeks, the gravid uterus compresses the IVC during CPR, severely limiting compression effectiveness. Manual left displacement is non-negotiable. If no ROSC by 4 minutes of high-quality CPR, perimortem C-section by 5 minutes improves MOM survival by relieving IVC obstruction and increasing venous return - even if the fetus is not viable. The "4-minute rule" exists for the mother first.' },
        { text: 'Defer all interventions until in-hospital', exp: 'Wrong if you have the capability and training. Manual uterine displacement is field-doable. Perimortem C-section in the field is rare but appropriate decisions need to be considered.' },
        { text: 'Stop CPR if no ROSC at 5 minutes since further efforts are futile', exp: 'Catastrophically wrong. The 4-minute rule says perimortem C-section AT 4-5 min, NOT termination. Maternal CPR continues throughout and after delivery.' },
      ],
      correct: 1,
      exp: 'Maternal arrest after 20 weeks: manual left uterine displacement is mandatory throughout CPR. Perimortem C-section by 5 min benefits the MOTHER first by relieving IVC compression. Best fetal resuscitation IS good maternal resuscitation.',
      difficulty: 9,
      tags: ['ob-emergency', 'arrest'],
    },
    {
      id: 'op-24',
      q: 'A 90yo F nursing home patient with advanced dementia has a clearly documented MOLST/POLST stating "Do Not Resuscitate, Comfort Measures Only." She becomes unresponsive. Family arrives and demands "do everything." What is the appropriate course?',
      choices: [
        { text: 'Honor the family request and start full resuscitation', exp: 'Wrong. The MOLST/POLST is a legally binding physician order signed when the patient had capacity (or by legal surrogate). It overrides family present-day preferences UNLESS the document is being formally rescinded by the legal decision-maker through proper channels.' },
        { text: 'Honor the MOLST/POLST per its terms; provide comfort, communicate respectfully with family, contact medical control or hospice if available', exp: 'Correct. Pre-existing valid orders (POLST/MOLST/DNR) supersede family wishes at the bedside in an arrest. This is hard emotionally but legally clear. Document carefully. Offer family support, explain the decision, contact hospice/palliative resources, contact medical control if uncertainty exists about validity.' },
        { text: 'Start CPR until medical control gives an order to stop', exp: 'Wrong. A valid POLST IS the order. Starting CPR against a valid order is medically and legally incorrect.' },
        { text: 'Refuse to treat the patient at all', exp: 'Wrong on the other extreme. Comfort measures are still TREATMENT - positioning, pain control, suctioning if indicated for comfort, family support. Comfort care is not abandonment.' },
      ],
      correct: 1,
      exp: 'Valid POLST/MOLST/DNR is a physician order - it overrides family preferences in the moment. The job is to honor it, communicate compassionately, and provide comfort. Document everything.',
      difficulty: 7,
      tags: ['geriatric', 'end-of-life'],
    },
    {
      id: 'op-25',
      q: 'A 4-year-old, 16 kg, suspected of ingesting an unknown number of acetaminophen tablets 2 hours ago. He is alert, vomiting once, normal vitals. What is the MOST important early action?',
      choices: [
        { text: 'Activated charcoal 1 g/kg PO if alert and able to protect airway', exp: 'Reasonable but not THE most important. Charcoal helps if given within ~1-2 hours of ingestion in alert patients. He is at the outside edge of usefulness. The key for acetaminophen is timing the level and N-acetylcysteine decision.' },
        { text: 'Get a 4-hour post-ingestion acetaminophen level and consult poison control / use Rumack-Matthew nomogram to decide on N-acetylcysteine', exp: 'Correct. Acetaminophen toxicity is silent for the first 24 hours then causes hepatic failure. The Rumack-Matthew nomogram uses the 4-hour post-ingestion level (NOT earlier) to predict toxicity and need for NAC. NAC is most effective within 8 hours of ingestion. Get the level at 4 hours, plot, treat if above the line.' },
        { text: 'Forced vomiting with ipecac', exp: 'Wrong and obsolete. Ipecac is no longer recommended in any setting because of risks (aspiration, prolonged emesis interfering with charcoal/NAC, no proven outcome benefit).' },
        { text: 'Wait 24 hours and bring back for liver function tests', exp: 'Catastrophic delay. NAC effectiveness drops sharply after 8 hours. Waiting 24 hours risks irreversible hepatic failure. The window is now.' },
      ],
      correct: 1,
      exp: 'Acetaminophen tox: silent first 24h, then liver fails. The 4-hour level on Rumack-Matthew nomogram drives NAC decision. NAC is near-100% effective within 8 hours. Time matters more than charcoal.',
      difficulty: 8,
      tags: ['peds-tox', 'acetaminophen'],
    },
  ],
}
