import type { Category } from './types'

export const TRAUMA: Category = {
  id: 'trauma',
  name: 'Trauma & Shock',
  short: 'Trauma',
  desc: 'Hemorrhagic shock, head injury, spinal trauma, chest and abdominal trauma, burns, crush injury, pediatric trauma, damage control resuscitation.',
  color: '#f59e0b',
  icon: 'shield',
  flashcards: [
    { id: 'tr-fc-1', front: 'Class I to IV hemorrhagic shock - blood loss and clinical signs', back: 'Class I: under 15% loss (under 750 mL), HR under 100, BP normal, mental status normal. Class II: 15-30% (750-1500 mL), HR 100-120, BP normal but narrow pulse pressure, anxious. Class III: 30-40% (1500-2000 mL), HR 120-140, BP drops, confused. Class IV: over 40% (over 2000 mL), HR over 140, BP very low, lethargic. BP only drops at Class III - by then already 1.5L down. Tachycardia and narrow pulse pressure are EARLY signs.' },
    { id: 'tr-fc-2', front: 'Permissive hypotension target and when NOT to use it', back: 'Target SBP 80-90 in penetrating trauma without head injury. Aggressive fluids before bleeding controlled dilute clotting factors, raise BP, and pop the soft clot off the hole - patient bleeds more. EXCEPTIONS: TBI (target SBP at least 110 to maintain CPP), pediatric (kids dont tolerate hypotension well), elderly with chronic HTN (their floor is higher). Goal: enough perfusion to think, not enough to bleed.' },
    { id: 'tr-fc-3', front: 'Lethal triad of trauma', back: 'Hypothermia + acidosis + coagulopathy. Each makes the others worse and all together kill bleeding patients. Cold blood doesnt clot. Acidosis inhibits clotting cascade. Coagulopathy from dilution and consumption. Damage control resuscitation reverses all three: warm everything, blood products instead of crystalloid, limit crystalloid, get to OR fast. Crystalloid worsens all three.' },
    { id: 'tr-fc-4', front: 'Massive transfusion protocol ratios', back: '1:1:1 ratio of PRBCs : FFP : platelets. Mimics whole blood. Activated when expected to need over 10 units PRBCs in 24h, or 4 units in 1h with ongoing bleeding. ABC score 2+ (penetrating mechanism, SBP under 90, HR over 120, positive FAST). Add TXA within 3 hours: 1g over 10 min, then 1g over 8 hours. Calcium replacement after every 2-4 units (citrate in stored blood binds calcium).' },
    { id: 'tr-fc-5', front: 'Cushings triad - what it means and what to do', back: 'Hypertension + bradycardia + irregular respirations = increased ICP, often herniation imminent. Late and ominous sign. Brain is being squeezed. Actions: head of bed 30 degrees, intubate with goal ETCO2 35 (NOT lower - chronic hyperventilation causes ischemia), 3% saline bolus or mannitol, prevent hypotension at all costs (single SBP under 90 doubles TBI mortality), neurosurgery NOW.' },
    { id: 'tr-fc-6', front: 'GCS scoring - eye, verbal, motor', back: 'Eye: 4 spontaneous, 3 to voice, 2 to pain, 1 none. Verbal: 5 oriented, 4 confused, 3 inappropriate words, 2 sounds, 1 none. Motor: 6 obeys, 5 localizes, 4 withdraws, 3 flexion (decorticate), 2 extension (decerebrate), 1 none. GCS 8 or under = intubate. Drop of 2+ points = significant deterioration. Best motor is most predictive of outcome.' },
    { id: 'tr-fc-7', front: 'Beck triad - cardiac tamponade', back: 'Hypotension + JVD + muffled heart sounds. Penetrating chest trauma between nipples is highest risk. Pulsus paradoxus (BP drops over 10 mmHg with inspiration) supports it. FAST shows pericardial fluid. Treatment: pericardiocentesis as a bridge, definitive is OR pericardial window or thoracotomy. Never volume-load a tamponade dry - give some fluid until cleared, but the fix is removing the fluid.' },
    { id: 'tr-fc-8', front: 'Tension pneumothorax - emergency decompression', back: 'Adult: 14g 8 cm catheter at 4th-5th ICS anterior axillary line OR 2nd ICS midclavicular (newer evidence prefers lateral due to thicker chest wall medially and risk of cardiac injury). Pediatric: 5 cm needle, 2nd ICS midclavicular. Always over the rib (avoid the neurovascular bundle on the inferior edge). Definitive is chest tube. Tracheal deviation is LATE - decompress on suspicion.' },
    { id: 'tr-fc-9', front: 'Flail chest - physiology and management', back: '3+ adjacent ribs broken in 2+ places creates a free segment that moves paradoxically with breathing. The real killer is underlying pulmonary contusion, not the mechanics. Pain prevents deep breaths, atelectasis develops, hypoxia worsens. Treatment: pain control (regional blocks, opioids), pulmonary toilet, CPAP/BiPAP early, intubate if respiratory failure. Stabilization devices and sandbags are obsolete.' },
    { id: 'tr-fc-10', front: 'Pulmonary contusion timeline', back: 'Bruise to lung tissue from blunt impact. Initial CXR may be normal. Symptoms peak 24-72 hours after injury. Hypoxia, infiltrates appear gradually. Avoid over-resuscitation (worsens edema), use blood products if shocked, restrictive fluids otherwise. CPAP early, intubate if PaO2/FiO2 falls below 300. High mortality if combined with ARDS.' },
    { id: 'tr-fc-11', front: 'Burn percentage - Rule of Nines (adult)', back: 'Head 9%, each arm 9%, anterior trunk 18%, posterior trunk 18%, each leg 18%, perineum 1%. Pediatrics differ (head is 18% in infant). Palm of patient (not provider) is approximately 1%. Only count partial-thickness (2nd) and full-thickness (3rd) burns - superficial (1st degree, sunburn-type) does NOT count toward TBSA for fluid resuscitation.' },
    { id: 'tr-fc-12', front: 'Parkland formula', back: '4 mL x kg x %TBSA (2nd and 3rd degree only) of LR over 24h. Half in first 8 hours from time of BURN (not time of presentation), other half over next 16. Titrate to urine output 0.5 mL/kg/hr adult, 1 mL/kg/hr peds. Modified Brooke uses 2 mL/kg/%TBSA. Over-resuscitation causes abdominal compartment syndrome and pulmonary edema. Under-resuscitation causes shock and AKI.' },
    { id: 'tr-fc-13', front: 'Inhalation injury - three components', back: '1) Upper airway thermal injury - soot in nares, singed hairs, hoarseness, stridor. Will swell over hours. Intubate EARLY before swelling closes the airway. 2) Carbon monoxide - high-dose 100% O2 for at least 4-6 hours, hyperbaric for severe (LOC, neuro deficits, lactate over 7, pregnant). 3) Cyanide - from burning plastics. Hydroxocobalamin 5g IV. Suspect with severe lactic acidosis out of proportion to burns.' },
    { id: 'tr-fc-14', front: 'Compartment syndrome - 5 Ps and key vitals', back: 'Pain (out of proportion, worse with passive stretch - earliest and most reliable), Pallor, Paresthesia, Paralysis (late), Pulselessness (very late, by then limb is dying). Pressure over 30 mmHg or within 30 of DBP requires fasciotomy. Common in tibia fractures, crush injuries, burns, reperfusion. Pulselessness comes too late - dont wait for it.' },
    { id: 'tr-fc-15', front: 'Crush syndrome - three killers after extrication', back: '1) Hyperkalemia (rhabdo releases K+ from muscle) - peaked T waves, V-fib. Calcium gluconate, insulin/D50, beta-agonist, dialysis. 2) Hypovolemia (third spacing into damaged muscle) - aggressive crystalloid BEFORE extrication if possible. 3) Acute kidney injury (myoglobin clogs tubules) - alkalinize urine with bicarb if pH under 7.2 with normalized K, target urine pH over 6.5, urine output over 200 mL/hr. Patient was stable until you let them out - now hes crashing.' },
    { id: 'tr-fc-16', front: 'Spinal cord injury levels and what they mean', back: 'C3-C5 keeps the diaphragm alive (phrenic nerve). Above C3 = no breathing. C5 = arm flexion preserved. C7 = elbow extension. T1 = hand intact. Below T6 = can have autonomic dysreflexia. Sacral sparing (perianal sensation, rectal tone) preserved = incomplete injury, better prognosis. Anterior cord syndrome: motor and pain loss but proprioception preserved. Central cord: weak arms more than legs.' },
    { id: 'tr-fc-17', front: 'Neurogenic shock vs spinal shock - different things', back: 'Neurogenic shock: hemodynamic. Loss of sympathetic tone below injury (T6 and above). Hypotension + bradycardia + warm flushed skin. Lasts days to weeks. Treatment: fluids, then vasopressors (norepi or phenylephrine). Spinal shock: neurologic. Flaccid paralysis and areflexia below injury immediately after trauma. Lasts hours to days. Returning bulbocavernosus reflex marks end of spinal shock.' },
    { id: 'tr-fc-18', front: 'Autonomic dysreflexia - recognize and treat', back: 'Patient with chronic spinal cord injury at T6 or above. Triggered by noxious stimulus below injury level (full bladder is most common, also fecal impaction, pressure ulcer, ingrown nail). Massive sympathetic surge below injury, vagal response above. Severe HTN, bradycardia, headache, flushing above injury, pale below. SIT THE PATIENT UP first (orthostatic drop helps). Find and fix the trigger. Can cause hemorrhagic stroke if untreated.' },
    { id: 'tr-fc-19', front: 'Pelvic fracture - hemorrhage management', back: 'Open-book fractures can hold 2-3 liters. Apply pelvic binder at the level of greater trochanters (not iliac crests - common error). Reduces volume and tamponades venous bleeding. Arterial bleeders need IR embolization or REBOA. Massive transfusion protocol on. Avoid log rolling. FAST may miss retroperitoneal bleed - high suspicion based on mechanism and hemodynamic instability.' },
    { id: 'tr-fc-20', front: 'FAST exam - 4 windows and what they show', back: 'Right upper quadrant (Morison pouch, hepatorenal recess) - most sensitive, fluid collects here first. Left upper quadrant (splenorenal). Pelvis (rectovesical/rectouterine). Subxiphoid (pericardium). Detects free fluid (blood) but misses retroperitoneal bleeds and hollow viscus injury. Negative FAST in unstable patient does NOT rule out abdominal hemorrhage - go to OR or CT based on mechanism.' },
    { id: 'tr-fc-21', front: 'Pediatric trauma differences - what changes', back: 'Larger head proportionally - flexion injuries common, place blanket UNDER torso to keep neck neutral on board. Compliant chest wall - significant pulmonary contusion possible without rib fractures. Hypotension is LATE - kids compensate longer then crash hard. Splenic injury common in blunt trauma. Surface area to mass ratio higher - hypothermia fast. Drug doses by weight or Broselow tape - never eyeball.' },
    { id: 'tr-fc-22', front: 'Geriatric trauma differences - what changes', back: 'Lower physiologic reserve. Beta blockers blunt tachycardia (heart rate is unreliable). Anticoagulation increases bleeding risk dramatically - ground level falls cause subdural hematomas. Reverse warfarin with PCC (faster than FFP), reverse DOACs with andexanet or idarucizumab. Lower threshold for trauma activation, CT head, admit. Frailty is a predictor of bad outcomes - do not under-triage.' },
    { id: 'tr-fc-23', front: 'TXA - when, dose, mechanism', back: 'Tranexamic acid blocks plasminogen activation, prevents clot breakdown. CRASH-2 trial: give within 3 hours of trauma, mortality benefit. After 3 hours, may worsen outcomes (paradoxically increases mortality). Dose: 1g over 10 min, then 1g over 8 hours. Useful in trauma, postpartum hemorrhage, GI bleed. Not for VTE-prone patients without good reason. Cheap, easy, saves lives if given on time.' },
    { id: 'tr-fc-24', front: 'Damage control resuscitation pillars', back: '1) Permissive hypotension (target SBP 80-90 except TBI). 2) Hemostatic resuscitation (1:1:1 blood products, minimal crystalloid). 3) Damage control surgery (abbreviated OR - stop bleeding and contamination, leave abdomen open, ICU for warming/correcting acidosis/coagulopathy, return for definitive repair later). Old-school crystalloid resuscitation killed people. New approach saves lives.' },
    { id: 'tr-fc-25', front: 'Penetrating neck trauma - Zone I, II, III', back: 'Zone I: clavicles to cricoid (thoracic outlet). High-risk vascular, hard to access surgically - angiography/CT. Zone II: cricoid to angle of mandible. Most common, easiest to explore surgically, most amenable to direct exploration. Zone III: angle of mandible to skull base. Vascular injuries managed with IR. Hard signs (expanding hematoma, bruit, active bleed, airway compromise) = OR. Soft signs = CT angio.' },
    { id: 'tr-fc-26', front: 'Aortic dissection vs aortic transection (traumatic)', back: 'Traumatic transection: deceleration injury (high-speed MVC, fall from height). Tear at aortic isthmus (just past left subclavian where ligamentum arteriosum tethers aorta). Widened mediastinum on CXR, left apical cap. CT angio confirms. Endovascular repair preferred. Mortality very high if missed. Different mechanism from dissection (intimal tear with false lumen, often spontaneous in HTN).' },
    { id: 'tr-fc-27', front: 'Open globe injury - do not touch', back: 'Eye-shield only (Fox shield or paper cup). NO pressure, NO drops, NO probing. Elevate head of bed 30 degrees. NPO for OR. Antiemetics to prevent Valsalva. Tetanus, broad-spectrum antibiotics. Removing impaled objects from eye = vitreous extrusion = blindness. Visual acuity check at presentation has medicolegal importance.' },
    { id: 'tr-fc-28', front: 'Hypothermia in trauma - temperature thresholds', back: 'Mild: 32-35C. Moderate: 28-32C. Severe: under 28C. Below 30C: defibrillation may not work, drugs may not work - extracorporeal rewarming preferred. Below 32C: J wave (Osborn wave) on ECG. Coagulopathy worsens at every degree below 36C. Active rewarming for trauma: warm blankets, warmed IV fluids and blood, warm room, Bair Hugger. Wet clothes off. Core temp from esophageal probe most accurate.' },
    { id: 'tr-fc-29', front: 'Pediatric C-spine clearance differences', back: 'Most pediatric C-spine injuries are upper cervical (C1-C3) due to proportionally larger head and weaker neck muscles. Pseudosubluxation at C2-C3 is common normal finding. SCIWORA (spinal cord injury without radiographic abnormality) - kids can have cord injury with normal X-ray and CT. MRI if symptoms despite normal imaging. NEXUS and Canadian C-spine rules less validated in young kids.' },
    { id: 'tr-fc-30', front: 'Fat embolism syndrome - recognize after long bone fracture', back: 'Onset 24-72h after long-bone fracture (especially femur). Triad: hypoxia + petechiae (axilla, conjunctiva) + altered mental status. Often misdiagnosed as PE. Treatment is supportive - oxygen, ventilation, hemodynamic support. Early fracture stabilization reduces incidence. No specific antidote. Mortality 5-15%.' },
  ],
  scenarios: [
    {
      id: 'tr-1',
      q: '24-year-old male with GSW to the right thigh. BP 92/68, HR 128, RR 24, alert but anxious. Bright red blood pulsing from the wound, soaked through his pants. You are 18 minutes from the trauma center. After applying direct pressure you are still seeing significant ongoing hemorrhage. Next move?',
      choices: [
        { text: 'Pack the wound with hemostatic gauze and apply firm direct pressure for 3 minutes', exp: 'Useful for wounds NOT amenable to tourniquet (junctional, neck, axilla). Extremity arterial bleed should get a tourniquet first if direct pressure is failing. This is delay.' },
        { text: 'Apply a CAT tourniquet 2-3 inches proximal to the wound, tighten until bleeding stops, mark time', exp: 'Correct. Extremity arterial hemorrhage failing direct pressure = tourniquet. Place high and tight on the affected limb (over single bone - humerus or femur - not joints). Tighten until bleeding stops AND distal pulse is gone. Mark the time. CAT can stay on safely for 2 hours, longer if necessary.' },
        { text: 'Start two large-bore IVs and give 2L NS wide open', exp: 'Aggressive crystalloid in penetrating trauma without head injury dilutes clotting factors, raises BP, blows clot off the wound, increases bleeding. Permissive hypotension target SBP 80-90 here.' },
        { text: 'Elevate the leg above the heart and apply ice pack', exp: 'Elevation has minimal effect on arterial bleeding. Ice does nothing for active hemorrhage. This is wasted time while patient bleeds out.' },
      ],
      correct: 1,
      exp: 'Stop the bleeding first. In extremity arterial hemorrhage failing direct pressure, the tourniquet is the highest-priority intervention. Permissive hypotension supports the clot you create. Crystalloid is the enemy. TXA within 3 hours.',
      difficulty: 8,
      tags: ['hemorrhage-control', 'tourniquet'],
    },
    {
      id: 'tr-2',
      q: '32-year-old female restrained driver in a high-speed MVC. Initial vitals: BP 142/88, HR 58, GCS 7 (E1 V2 M4). Pupil R 6mm sluggish, L 3mm reactive. Posturing right side. Most appropriate ventilation strategy after intubation?',
      choices: [
        { text: 'Hyperventilate to ETCO2 25-30 to reduce ICP', exp: 'Aggressive prophylactic hyperventilation causes cerebral vasoconstriction and ischemia. Worsens secondary brain injury. Only used as a brief bridge (minutes) for impending herniation, then return to normocapnia.' },
        { text: 'Target ETCO2 35-40 mmHg, maintain SpO2 over 94%', exp: 'Correct. Normocapnia preserves cerebral blood flow. Hypercapnia vasodilates and raises ICP, hypocapnia vasoconstricts and causes ischemia - both are bad. Avoid hypoxia (single episode of SpO2 under 90 doubles TBI mortality) and hypotension.' },
        { text: 'Permissive hypercapnia, ETCO2 50-55', exp: 'Useful in ARDS or severe asthma with auto-PEEP. In TBI, hypercapnia raises ICP. Wrong context entirely.' },
        { text: 'PEEP 15, FiO2 100%, target ETCO2 30', exp: 'High PEEP can raise ICP through reduced venous return from the head. Hyperventilation as above is harmful. Wrong on multiple fronts.' },
      ],
      correct: 1,
      exp: 'TBI ventilation principles: avoid hypoxia, avoid hypotension (single SBP under 90 doubles mortality), maintain normocapnia (ETCO2 35-40). The blown right pupil with posturing is uncal herniation - this patient also needs hypertonic saline or mannitol and emergent neurosurgery. Cushings triad here too: HTN, bradycardia, abnormal breathing.',
      difficulty: 9,
      tags: ['tbi', 'ventilation'],
    },
    {
      id: 'tr-3',
      q: 'Construction worker trapped under collapsed wall for 4 hours. Right leg pinned. Once youre on scene, what is the highest-priority intervention BEFORE extrication?',
      choices: [
        { text: 'IV fluids running before release of pressure', exp: 'Correct. Crush injury releases massive K+, myoglobin, lactate the moment pressure comes off. Patient who looks fine while pinned crashes within minutes of extrication. Preload with NS, monitor for hyperkalemia (peaked T waves, V-fib), have calcium gluconate, insulin/D50, bicarb ready. Some protocols include sodium bicarbonate in IV bag prophylactically.' },
        { text: 'Immediate extrication with manpower, fluids after', exp: 'Wrong. Free the limb without preparation and the patient arrests from acute hyperkalemia and hypovolemia within minutes. The wall is keeping them alive, paradoxically.' },
        { text: 'Tourniquet the limb before release', exp: 'Tourniquet may delay reperfusion injury but does not address the systemic effects when eventually released. Reasonable for short transport with definitive care close, but fluids first regardless.' },
        { text: 'Push 1 amp of bicarb and extricate', exp: 'Bicarb has a role for hyperkalemia after extrication, but giving it without IV access in place to flush the system and continued fluid is incomplete preparation.' },
      ],
      correct: 0,
      exp: 'Crush syndrome is a setup. While compressed, K+ is locally trapped. Release reperfuses dead muscle systemically - hyperkalemia, hypovolemia (third spacing), AKI from myoglobin. Aggressive IV fluids BEFORE extrication, monitor ECG, treat hyperkalemia preemptively. Patient who looks fine pinned can arrest 30 seconds after release.',
      difficulty: 9,
      tags: ['crush', 'rhabdo'],
    },
    {
      id: 'tr-4',
      q: '45-year-old male with stab wound to left chest at 4th intercostal space. BP 78/40, HR 138, JVD, muffled heart tones, breath sounds present bilaterally. FAST shows pericardial effusion. After fluid bolus, BP transiently improves to 90/60 then drops again. Definitive treatment?',
      choices: [
        { text: 'Bilateral chest tubes', exp: 'Wrong. Breath sounds are present bilaterally and FAST shows pericardial fluid - this is tamponade, not pneumothorax. Chest tubes do not address pericardial blood.' },
        { text: 'Pericardiocentesis as a bridge, urgent OR for pericardial window or thoracotomy', exp: 'Correct. Beck triad (hypotension + JVD + muffled heart sounds) with FAST-confirmed pericardial fluid in penetrating chest trauma between the nipples = tamponade. Pericardiocentesis can buy minutes but blood reaccumulates because the hole is still open. Definitive is surgical drainage and repair.' },
        { text: 'Massive transfusion protocol and hold for hemodynamics to improve', exp: 'Volume helps tamponade physiology temporarily but does not fix the problem. The patient transiently responded then dropped again - classic tamponade pattern. Continued transfusion without surgery just delays death.' },
        { text: 'Aggressive crystalloid resuscitation, 4L NS', exp: 'Crystalloid in a bleeding patient dilutes clotting factors and worsens coagulopathy. Even in tamponade, blood products are preferred over crystalloid.' },
      ],
      correct: 1,
      exp: 'Penetrating chest trauma + Beck triad + FAST positive for pericardial fluid = tamponade. Pericardiocentesis is a bridge, the surgeon is the cure. Do not delay calling for OR. Tamponade physiology: small fluid bolus helps preload, but the only fix is removing the blood AND closing the hole.',
      difficulty: 8,
      tags: ['tamponade', 'penetrating-chest'],
    },
    {
      id: 'tr-5',
      q: 'House fire rescue. 30-year-old male, GCS 8, soot in nares, singed nasal hairs, hoarse voice, no obvious burns to face but dyspnea worsening. SpO2 reads 100% on NRB. Lactate 12. Most appropriate next step?',
      choices: [
        { text: 'Continue NRB, repeat ABG in 20 minutes', exp: 'SpO2 in CO poisoning is FALSELY normal - pulse ox cannot distinguish carboxyhemoglobin from oxyhemoglobin. The 100% reading is meaningless. Watching while airway swells is malpractice.' },
        { text: 'Intubate now AND give hydroxocobalamin (Cyanokit) 5g IV', exp: 'Correct. Inhalation injury with hoarse voice + soot + singed hairs = airway will swell. Intubate before swelling closes the trachea - once it does, you cant. Lactate 12 + house fire = cyanide until proven otherwise. Hydroxocobalamin binds cyanide. Also high-flow O2 for CO. House fire trio: thermal + CO + cyanide.' },
        { text: 'High-dose albuterol nebulizer and BiPAP', exp: 'BiPAP is contraindicated with airway burns and decreased LOC (cant protect airway). Albuterol does not address swelling, CO, or cyanide.' },
        { text: 'Mannitol 1 g/kg for cerebral edema', exp: 'No evidence of TBI. The altered mental status is from CO and cyanide, not edema. Mannitol does nothing here.' },
      ],
      correct: 1,
      exp: 'House fire victim with airway burn signs needs early intubation - wait and you wont be able to. Lactic acidosis out of proportion to burns = cyanide. Treat empirically with hydroxocobalamin, dont wait for confirmation. SpO2 is unreliable in CO poisoning - get a co-oximetry blood gas.',
      difficulty: 9,
      tags: ['inhalation-injury', 'cyanide'],
    },
    {
      id: 'tr-6',
      q: '70 kg adult with full-thickness burns to entire anterior trunk and both anterior legs. Burns occurred 90 minutes ago. Calculate the Parkland fluid total over 24 hours and the rate for the FIRST 8 hours from time of injury.',
      choices: [
        { text: '11,200 mL total, 700 mL/hr first 8 hours', exp: 'Wrong calculation. Anterior trunk = 18%, both anterior legs = 9% each = 18%. Total TBSA = 36%. 4 × 70 × 36 = 10,080. Half over first 8 hours from BURN time = 5040 over 6.5 remaining hours = 776 mL/hr. None of these numbers match.' },
        { text: '10,080 mL total, approximately 776 mL/hr for the next 6.5 hours', exp: 'Correct. 4 mL × 70 kg × 36% TBSA = 10,080 mL over 24 hours. Half (5040 mL) goes in over the first 8 hours from time of burn. 90 minutes have already passed, so 5040 / 6.5 = 776 mL/hr. Other half over next 16 hours.' },
        { text: '10,080 mL total, 1260 mL/hr for next 8 hours', exp: 'Calculation error. The 8-hour clock starts at time of BURN, not time of presentation. 90 minutes already elapsed must be subtracted from the first 8-hour window.' },
        { text: '20,160 mL total, 1260 mL/hr', exp: 'Doubled the formula. Parkland is 4 mL/kg/%TBSA, not 8 mL.' },
      ],
      correct: 1,
      exp: 'Parkland: 4 mL × kg × %TBSA over 24h. Half in first 8 hours FROM BURN, not from arrival. TBSA: anterior trunk 18%, anterior legs 9% each = 36%. 4 × 70 × 36 = 10,080. Time elapsed comes off the front. Titrate to UOP 0.5 mL/kg/hr.',
      difficulty: 8,
      tags: ['burns', 'parkland'],
    },
    {
      id: 'tr-7',
      q: 'Tibial fracture from a fall, splinted, 2 hours ago. Now: severe pain unrelieved by morphine, pain dramatically worse with passive dorsiflexion, leg tense and tight. Distal pulses present, no pallor. Capillary refill 3 seconds. Most accurate statement?',
      choices: [
        { text: 'Distal pulses present rules out compartment syndrome', exp: 'Wrong - and dangerous. Pulselessness is a LATE sign. By the time pulses are gone, the limb is dying. Pain out of proportion and pain with passive stretch are EARLY and reliable signs.' },
        { text: 'Compartment syndrome is suspected and requires fasciotomy without delay', exp: 'Correct. Pain out of proportion to injury + pain on passive stretch + tense compartment = compartment syndrome. Compartment pressures over 30 mmHg or within 30 of DBP confirm. Fasciotomy is the only treatment. Waiting for pallor, paresthesia, paralysis, pulselessness means waiting for irreversible damage.' },
        { text: 'Loosen the splint and reassess in 30 minutes', exp: 'Loosening a constricting splint is reasonable as a first step but if compartment syndrome is established, this delay loses muscle. Surgical consult should be simultaneous, not after a 30-minute trial.' },
        { text: 'Give more opioid and elevate the limb', exp: 'Opioid masks the most reliable early sign. Elevation may worsen perfusion in established compartment syndrome (some debate, but at minimum keep at heart level). Wrong management.' },
      ],
      correct: 1,
      exp: 'Compartment syndrome 5 Ps: Pain (early, most reliable), Paresthesia, Pallor, Paralysis (late), Pulselessness (very late, limb is dying). Pain on passive stretch is the most sensitive early sign. Tibia fractures, crush, burns, reperfusion are highest risk. Fasciotomy is the cure - there is no medical management.',
      difficulty: 8,
      tags: ['compartment-syndrome'],
    },
    {
      id: 'tr-8',
      q: '6-year-old struck by car. GCS 15, vital signs stable, but you note a transverse abrasion across the abdomen consistent with a lap belt. FAST is negative. Parents want to take him home - they say hes fine. Best response?',
      choices: [
        { text: 'Discharge with strict return precautions', exp: 'Wrong. Seatbelt sign in pediatrics is a marker for hollow viscus injury (small bowel perforation, mesenteric tear) that often does not show on initial imaging. FAST is insensitive for these. Bowel injuries can present 12-48 hours later with peritonitis.' },
        { text: 'CT abdomen/pelvis with IV contrast and admit for serial exams', exp: 'Correct. Seatbelt sign in a child = high suspicion for hollow viscus injury, mesenteric tear, lumbar Chance fracture. CT is reasonable but not perfect for hollow viscus injury - serial abdominal exams over 12-24 hours are critical. Repeat labs (lactate, lipase). Threshold for OR is low if exam worsens.' },
        { text: 'Plain abdominal X-ray and observe for 2 hours', exp: 'Plain films will miss bowel and solid organ injury. 2 hours is insufficient observation for delayed presentations.' },
        { text: 'Repeat FAST in 30 minutes, discharge if negative', exp: 'FAST repeats add little value for hollow viscus injury, which is the concern with seatbelt sign. Negative FAST cannot rule this out.' },
      ],
      correct: 1,
      exp: 'Pediatric seatbelt sign = hollow viscus, mesenteric, and Chance fracture risk. CT is helpful but doesnt rule out bowel injury - serial exams over 24 hours are needed. Bowel perforations declare themselves with worsening pain, fever, peritonitis. Send these kids home and theyll come back septic.',
      difficulty: 8,
      tags: ['pediatric-trauma', 'seatbelt-sign'],
    },
    {
      id: 'tr-9',
      q: 'High-speed MVC, unrestrained driver. CXR shows widened mediastinum, left apical cap, deviation of NG tube to the right. BP 168/95, HR 102. Most likely diagnosis and next step?',
      choices: [
        { text: 'Tension pneumothorax - needle decompression', exp: 'Tension pneumo causes hypotension and tracheal deviation but the CXR findings here (widened mediastinum, apical cap) point elsewhere. Needle decompression is wrong intervention.' },
        { text: 'Traumatic aortic injury - CT angiography of chest, control BP, surgery consult', exp: 'Correct. Widened mediastinum + left apical cap + deceleration mechanism = traumatic aortic injury until proven otherwise. Tear at aortic isthmus (just past left subclavian, where ligamentum arteriosum tethers aorta against deceleration force). HTN here is bad - increases shear on the tear. Goal SBP 100-120, HR under 100. Beta blockers (esmolol). CT angio confirms. Endovascular repair is now standard.' },
        { text: 'Diaphragmatic rupture - laparoscopy', exp: 'Diaphragmatic rupture appears as bowel in the chest on CXR. Different finding pattern.' },
        { text: 'Hemothorax - chest tube', exp: 'Hemothorax shows opacified hemithorax with blunting of the costophrenic angle, not isolated mediastinal widening.' },
      ],
      correct: 1,
      exp: 'Deceleration injury + widened mediastinum + apical cap = aortic injury until ruled out. Common at the isthmus where ligamentum arteriosum tethers. CT angio is gold standard. Control BP and HR aggressively to reduce shear stress. Endovascular repair has dropped mortality dramatically.',
      difficulty: 9,
      tags: ['aortic-injury', 'deceleration'],
    },
    {
      id: 'tr-10',
      q: 'Fall from 25-foot ladder. Patient awake, complaining of severe back pain. Cant move legs, no sensation below umbilicus. BP 78/52, HR 54, skin warm and flushed below injury, pale and clammy above. Most likely shock category and next step?',
      choices: [
        { text: 'Hemorrhagic shock - massive transfusion', exp: 'Patient is bradycardic and warm/flushed below injury - not hemorrhagic shock pattern (which is tachycardic, cool, pale). Mechanism could include occult hemorrhage but the presentation here is classic for something else.' },
        { text: 'Neurogenic shock - fluids first, then norepinephrine if BP doesnt respond', exp: 'Correct. Spinal cord injury at T6 or above causes loss of sympathetic tone below injury. Hypotension + bradycardia + warm flushed skin below injury = neurogenic shock. Treat with fluids first (modest), then vasopressors (norepi or phenylephrine) for refractory hypotension. Always rule out concurrent hemorrhage with FAST/CT - they can coexist.' },
        { text: 'Septic shock - broad-spectrum antibiotics', exp: 'No infectious source within minutes of trauma. Sepsis has different pattern.' },
        { text: 'Cardiogenic shock - dobutamine and diuretics', exp: 'No history of cardiac dysfunction. Mechanism is spinal trauma. Wrong shock category.' },
      ],
      correct: 1,
      exp: 'Spinal cord injury at T6 and above interrupts sympathetic outflow. Below injury: vasodilation (warm, flushed, hypotension). Above: intact (cool/clammy from any concurrent shock or pain). Heart rate is bradycardic from unopposed vagal tone, NOT compensating tachycardia. Always rule out hemorrhage simultaneously. Spinal shock (flaccid paralysis) is a separate, neurologic phenomenon.',
      difficulty: 8,
      tags: ['neurogenic-shock', 'spinal-trauma'],
    },
    {
      id: 'tr-11',
      q: 'Patient with chronic T4 spinal cord injury presents with severe headache, BP 220/120, HR 48, flushing above injury, pale below. What is the FIRST step in management?',
      choices: [
        { text: 'IV nitroprusside drip', exp: 'Pharmacologic BP control is appropriate but not the FIRST step. Treat the cause first - most cases resolve without antihypertensives once the trigger is removed.' },
        { text: 'Sit the patient up and search for and remove the noxious stimulus (most often distended bladder)', exp: 'Correct. Autonomic dysreflexia: noxious stimulus below injury level (distended bladder MOST common, then fecal impaction, then pressure ulcer or ingrown nail) triggers sympathetic surge below injury, vagal response above. Sitting up causes orthostatic drop. Catheterize, disimpact, find ingrown nail. BP usually normalizes within minutes once trigger is fixed.' },
        { text: 'Lay the patient flat and give Trendelenburg', exp: 'Backwards. Trendelenburg raises BP. Sit them UP for orthostatic drop.' },
        { text: 'Atropine for the bradycardia', exp: 'Bradycardia here is reflexive vagal response to massive HTN. Treating it without addressing the HTN doesnt fix the problem. The HTN is what kills (intracranial hemorrhage). Treat the cause.' },
      ],
      correct: 1,
      exp: 'Autonomic dysreflexia is a hypertensive emergency unique to chronic SCI at T6 or above. Treatment order: 1) Sit up. 2) Find and remove trigger (bladder, bowel, skin). 3) Antihypertensives (nitrates, hydralazine) only if BP doesnt respond. Ignored, this causes hemorrhagic stroke. Patient/family education on prevention is critical.',
      difficulty: 8,
      tags: ['autonomic-dysreflexia'],
    },
    {
      id: 'tr-12',
      q: 'Pelvic ring fracture from MVC. BP 82/48, HR 138. FAST negative. You apply a pelvic binder. Where does the binder go?',
      choices: [
        { text: 'Iliac crests (along the bony prominences at the waist)', exp: 'Common error. Binders applied at iliac crests do not provide effective compression of the pelvic ring. Reduces force vectors needed.' },
        { text: 'Greater trochanters (level of the hips, lower than where most people think)', exp: 'Correct. Pelvic binder must go at the level of the greater trochanters to compress the pelvic ring effectively, reduce volume, and tamponade venous bleeding. Applied too high (iliac crests), it compresses soft tissue but does not close the ring. Hip-level placement, not waist-level.' },
        { text: 'Mid-abdomen between umbilicus and pubis', exp: 'Wrong location. Compresses bowel, not bony pelvis.' },
        { text: 'Symphysis pubis only, leaving the back free', exp: 'Binder needs to be circumferential to close the ring.' },
      ],
      correct: 1,
      exp: 'Pelvic binder placement is at greater trochanters, NOT iliac crests. Open-book pelvic fractures can hemorrhage 2-3 liters into the retroperitoneum. Binder reduces volume, tamponades venous bleeding. Arterial bleeders need IR embolization or REBOA. Negative FAST does NOT rule out pelvic hemorrhage - bleeding is retroperitoneal, FAST misses it.',
      difficulty: 8,
      tags: ['pelvic-fracture'],
    },
    {
      id: 'tr-13',
      q: '21-year-old construction worker, fall from 30 feet. Femur fracture. 36 hours later, develops sudden hypoxia (SpO2 84% on RA), confusion, and petechiae across axilla and conjunctiva. BP 118/74, HR 124, RR 28. Most likely diagnosis?',
      choices: [
        { text: 'Pulmonary embolism', exp: 'Possible given the immobilization and trauma, but the petechiae and timing (36-72 hours after long-bone fracture) are classic for fat embolism. PE rarely causes petechiae.' },
        { text: 'Fat embolism syndrome', exp: 'Correct. Classic triad: hypoxia + petechiae (axilla, conjunctiva, oral mucosa) + altered mental status. Onset 24-72 hours after long-bone or pelvic fracture. Femur is highest risk. Pathophysiology: marrow fat enters venous circulation, causes mechanical and biochemical lung injury. Treatment is supportive - oxygen, ventilation, hemodynamic support. Early fracture stabilization reduces incidence. Mortality 5-15%.' },
        { text: 'Sepsis from open fracture', exp: 'Sepsis would not typically present with petechiae in this distribution and the timing/triad fits FES better.' },
        { text: 'TBI with delayed deterioration', exp: 'No mechanism for delayed TBI from a femur fracture without head impact. Petechiae and hypoxia are not TBI features.' },
      ],
      correct: 1,
      exp: 'Fat embolism syndrome: triad of hypoxia, petechiae, AMS at 24-72 hours after long-bone fracture. Often misdiagnosed as PE. No specific treatment - supportive care, early fracture fixation prevents it. Petechiae are pathognomonic when present but only 50% of cases.',
      difficulty: 8,
      tags: ['fat-embolism'],
    },
    {
      id: 'tr-14',
      q: 'Penetrating neck trauma, Zone II (cricoid to angle of mandible). Patient has expanding hematoma, hoarseness, and bruit over the neck. Most appropriate next step?',
      choices: [
        { text: 'CT angiography of the neck', exp: 'CT angio is for soft signs (small stable hematoma, dysphagia without distress, minor bleeding). This patient has HARD signs.' },
        { text: 'Direct surgical exploration in the OR', exp: 'Correct. Hard signs of vascular injury (expanding hematoma, bruit, active bleeding, airway compromise, hemodynamic instability) = OR for direct exploration, regardless of zone. Zone II is most accessible surgically. Zone I and III may use IR/angio for soft signs but hard signs always go to OR.' },
        { text: 'Observation with serial neck exams', exp: 'Hard signs cannot be observed. Vascular injuries with expanding hematoma can rupture suddenly.' },
        { text: 'Plain X-ray of the neck', exp: 'X-ray adds nothing useful and delays definitive care.' },
      ],
      correct: 1,
      exp: 'Hard signs of penetrating neck trauma (expanding hematoma, bruit, thrill, active bleeding, airway compromise, neuro deficit, hemodynamic instability) = immediate OR. Soft signs (small stable hematoma, dysphagia, mild hemoptysis) = CT angio. Zone II is most surgically accessible.',
      difficulty: 8,
      tags: ['penetrating-neck'],
    },
    {
      id: 'tr-15',
      q: 'Hemorrhagic shock patient receiving massive transfusion (8 units PRBC over 90 minutes). Suddenly develops perioral tingling, prolonged QT on monitor, ECG shows occasional PVCs. What is happening and what do you do?',
      choices: [
        { text: 'Hyperkalemia from cell lysis - calcium gluconate, insulin/D50', exp: 'Stored blood does have higher K+ but the symptoms here (perioral tingling, QT prolongation) point to hypocalcemia, not hyperkalemia.' },
        { text: 'Hypocalcemia from citrate binding - calcium chloride or gluconate IV', exp: 'Correct. Stored blood is preserved with citrate, which binds calcium. Massive transfusion causes hypocalcemia: perioral tingling, paresthesias, prolonged QT, hyporeflexia, eventually tetany and arrest. Replace calcium after every 2-4 units of PRBC. Calcium chloride (10 mL of 10%) preferred via central line; gluconate (1g) via peripheral.' },
        { text: 'Hypothermia - warm fluids only', exp: 'Hypothermia exacerbates the problem but the immediate fix for QT prolongation and tingling is calcium replacement.' },
        { text: 'Anaphylactic reaction to blood - epinephrine, stop transfusion', exp: 'Symptoms dont fit anaphylaxis (no rash, hypotension out of proportion, wheezing). Wrong diagnosis.' },
      ],
      correct: 1,
      exp: 'Massive transfusion lethal triad add-ons: hypocalcemia, hypothermia, hyperkalemia. Citrate in stored blood chelates calcium - replace empirically after every 2-4 units. Hypocalcemia worsens coagulopathy and causes QT prolongation, arrhythmias. Symptoms in awake patient: perioral tingling, Chvostek and Trousseau signs.',
      difficulty: 9,
      tags: ['massive-transfusion', 'hypocalcemia'],
    },
    {
      id: 'tr-16',
      q: 'Adult with full-thickness circumferential burn around the chest. Initial vent settings normal, peak airway pressures climbing rapidly. SpO2 dropping. What does he need?',
      choices: [
        { text: 'Increased PEEP and FiO2', exp: 'Wrong cause-effect. Rising airway pressures are mechanical from the eschar restricting chest expansion, not a ventilation problem fixable with PEEP.' },
        { text: 'Escharotomy of the chest along anterior axillary lines', exp: 'Correct. Circumferential full-thickness burn creates a rigid eschar that restricts chest excursion, mechanically prevents ventilation, raises airway pressures, drops oxygenation. Escharotomy: full-thickness incisions along the anterior axillary lines bilaterally and across the chest if needed. Cuts down to subcutaneous fat. Restores chest wall compliance.' },
        { text: 'Switch to high-frequency oscillatory ventilation', exp: 'HFOV is for severe ARDS. Doesnt address mechanical chest wall constriction.' },
        { text: 'Bronchoscopy to clear secretions', exp: 'No indication this is a secretion problem. Treats wrong issue.' },
      ],
      correct: 1,
      exp: 'Circumferential full-thickness burns cause compartment syndrome of the chest (impaired ventilation), abdomen (intraabdominal HTN), or extremities (limb ischemia). Escharotomy is bedside, life-saving, simple. Chest: mid-anterior axillary lines bilaterally. Extremity: medial and lateral. Abdomen: rare but indicated for ACS.',
      difficulty: 8,
      tags: ['burns', 'escharotomy'],
    },
    {
      id: 'tr-17',
      q: '85-year-old on warfarin, INR 3.5, fell down 3 stairs. GCS 14, lucid, mild headache. CT shows small subdural hematoma without midline shift. Best reversal strategy?',
      choices: [
        { text: 'Vitamin K 10 mg IV alone', exp: 'Vitamin K reverses warfarin too slowly (12-24 hours) for an acute intracranial bleed. Need rapid reversal.' },
        { text: 'Fresh frozen plasma 4 units', exp: 'FFP works but slowly (large volume, slow correction, fluid overload risk in elderly). PCC is faster and more effective in modern practice.' },
        { text: '4-factor prothrombin complex concentrate (PCC) plus vitamin K 10 mg IV', exp: 'Correct. PCC reverses warfarin in 15-30 minutes versus hours for FFP. Lower volume, no thawing, fewer transfusion reactions. Vitamin K is added for sustained reversal (PCC effect wears off in 6-8 hours, vitamin K maintains it). This is standard for warfarin-associated intracranial hemorrhage.' },
        { text: 'Andexanet alfa', exp: 'Andexanet is for factor Xa inhibitors (apixaban, rivaroxaban), NOT warfarin. Wrong reversal agent.' },
      ],
      correct: 2,
      exp: 'Anticoagulation reversal in trauma: Warfarin = PCC + vitamin K (FFP if PCC unavailable). Dabigatran = idarucizumab. Apixaban/rivaroxaban = andexanet alfa or PCC. Heparin = protamine. Speed matters - every minute of expanding intracranial hemorrhage worsens outcome.',
      difficulty: 8,
      tags: ['anticoagulation-reversal'],
    },
    {
      id: 'tr-18',
      q: '55-year-old motorcycle crash. BP 60/palp, HR 142, abdomen distended and rigid, FAST positive in all 4 quadrants. ATLS class IV shock. While prepping for OR, his BP drops further despite 4 units of PRBC. What is the next bridge until surgery?',
      choices: [
        { text: 'Vasopressors - norepinephrine drip', exp: 'Vasopressors in uncontrolled hemorrhagic shock raise BP but worsen perfusion to gut and kidney, mask ongoing bleeding, and dont fix the problem. Use sparingly while bridging to control. Not the first choice.' },
        { text: 'REBOA (resuscitative endovascular balloon occlusion of the aorta) - Zone 1 for abdominal hemorrhage', exp: 'Correct. REBOA Zone 1 (descending thoracic aorta, above diaphragm) provides temporary aortic occlusion to control infradiaphragmatic hemorrhage. Bridge to OR. Increases proximal perfusion (heart, brain) at cost of distal ischemia - clock starts immediately, must be deflated within 30 minutes ideally. Replaces resuscitative thoracotomy in select centers.' },
        { text: 'CPR, push ACLS dose epi', exp: 'Patient has not arrested. ACLS-dose epi in hemorrhagic shock raises BP transiently but does nothing for the bleed. Wrong context.' },
        { text: 'CT scan to identify the bleeding source', exp: 'Hemodynamically unstable patient does not go to CT. Goes to OR. CT is for stable patients.' },
      ],
      correct: 1,
      exp: 'In refractory hemorrhagic shock from below-diaphragm injury, REBOA is a bridge to OR. Zone 1 (above diaphragm) for abdominal/pelvic. Zone 3 (below renals) for pelvic only. Time-limited - distal ischemia is the cost. Replaces resuscitative thoracotomy in trauma centers with the capability.',
      difficulty: 9,
      tags: ['reboa', 'damage-control'],
    },
    {
      id: 'tr-19',
      q: 'Open globe injury from a metal shard. Patient cooperative, mild pain, vision preserved. What is the priority management?',
      choices: [
        { text: 'Topical anesthetic, gentle irrigation, then probing for foreign body', exp: 'Wrong on every count. Probing or pressing on an open globe causes vitreous extrusion = blindness. No drops, no irrigation, no pressure.' },
        { text: 'Apply a rigid eye shield, NPO for OR, antiemetics, IV antibiotics, tetanus, no pressure on the globe', exp: 'Correct. Open globe is hands-off. Fox shield or paper cup taped over the eye (not pressure patch). Anything that increases intraocular pressure (Valsalva, vomiting, eye pressing) extrudes vitreous. NPO for surgery, antiemetics for vomiting, broad-spectrum antibiotics, tetanus, ophthalmology emergency.' },
        { text: 'Pressure patch with gauze and tape', exp: 'PRESSURE on an open globe is contraindicated - extrudes vitreous. Use rigid shield without pressure.' },
        { text: 'Remove the foreign body and place a temporary suture', exp: 'Removing a penetrating object releases the seal. Done in OR by ophthalmology only.' },
      ],
      correct: 1,
      exp: 'Open globe management: rigid shield, no pressure, no drops, no probing, NPO, antiemetics, antibiotics, tetanus, OR. Visual acuity check on arrival has medicolegal weight. Remove nothing, touch nothing, transport carefully.',
      difficulty: 7,
      tags: ['eye-trauma'],
    },
    {
      id: 'tr-20',
      q: 'Hypothermic trauma patient pulled from a frozen river. Core temp 26C. Pulseless, no respirations. Monitor shows asystole. Most accurate guidance?',
      choices: [
        { text: 'Pronounce - patient is dead', exp: 'Wrong. "Not dead until warm and dead." Severe hypothermia mimics death and may protect from anoxic injury. Hearts can be revived from temperatures that would kill at normothermia.' },
        { text: 'Standard ACLS - push epi every 3-5 min, defibrillate VF up to 3 times', exp: 'Below 30C, drugs and defibrillation are largely ineffective. Standard ACLS doesnt apply. Continue CPR, withhold drugs and shocks until rewarmed past 30C.' },
        { text: 'CPR, NO drugs or shocks until temp over 30C, rapid extracorporeal rewarming (ECMO/cardiopulmonary bypass)', exp: 'Correct. Below 30C, the heart wont respond to drugs or shocks reliably. CPR is continued (often longer than usual - hours of CPR for severe hypothermia have produced neuro-intact survivors). Active core rewarming via ECMO is the gold standard. Below 28C, even shock-resistant V-fib can recover. Limit shocks to 1 attempt below 30C, then resume after rewarming.' },
        { text: 'Hot saline IV, 1L bolus', exp: 'Hot fluids alone wont rewarm fast enough. Surface rewarming for mild hypothermia, internal/extracorporeal for severe.' },
      ],
      correct: 2,
      exp: 'Severe hypothermia (under 28C): heart unresponsive to drugs and defibrillation. Continue CPR (hours if needed), withhold or limit drugs and shocks until 30C. Active rewarming with ECMO is the gold standard for arrest from severe hypothermia. Avoid rough handling - can trigger V-fib.',
      difficulty: 9,
      tags: ['hypothermia', 'arrest'],
    },
    {
      id: 'tr-21',
      q: '38-year-old female 32 weeks pregnant, restrained passenger in MVC. BP 102/68, HR 116, abdomen tender. FAST shows free fluid. Position the patient how before transport and ED workup?',
      choices: [
        { text: 'Supine, flat backboard', exp: 'Supine in third trimester causes aortocaval compression by gravid uterus, drops cardiac output, causes hypotension. Supine hypotension syndrome. Wrong position.' },
        { text: 'Left lateral decubitus or 15-30 degree left tilt of the backboard', exp: 'Correct. After 20 weeks, supine position compresses IVC and aorta against the spine, dropping venous return up to 30%. Left lateral tilt (or manually displacing the uterus to the left) restores it. Even on a backboard with C-spine precautions, tilt the entire board 15-30 degrees to the left.' },
        { text: 'Trendelenburg', exp: 'Trendelenburg in pregnancy worsens diaphragm compression, doesnt reliably help BP, and can worsen aspiration risk.' },
        { text: 'Reverse Trendelenburg', exp: 'Reverse T may worsen perfusion in shock patients. Doesnt address aortocaval compression.' },
      ],
      correct: 1,
      exp: 'Trauma in pregnancy: left lateral tilt to relieve aortocaval compression. Mom is the priority - best treatment for the fetus is resuscitating the mother. Anti-D for Rh-negative trauma patients. Consider placental abruption (vaginal bleeding, abdominal pain, contractions, fetal distress). Perimortem C-section within 4-5 minutes of arrest if over 24 weeks.',
      difficulty: 8,
      tags: ['pregnancy-trauma'],
    },
    {
      id: 'tr-22',
      q: 'Trauma patient in OR for damage control laparotomy. Surgeon stops bleeding, packs the abdomen, leaves it open with a temporary closure. Why?',
      choices: [
        { text: 'Definitive closure causes wound infection', exp: 'Infection is a concern but not the primary reason for damage control approach.' },
        { text: 'To prevent abdominal compartment syndrome from massive bowel edema after resuscitation, allow ICU correction of physiology, return for definitive repair when stable', exp: 'Correct. Damage control philosophy: stop bleeding and contamination quickly, get out, fix physiology in ICU (warm, correct acidosis, correct coagulopathy), return for definitive repair at 24-48 hours. Closing a swollen abdomen causes intraabdominal HTN - drops cardiac output, kidney perfusion, lung compliance. Open abdomen with temp closure (vac dressing, Bogota bag) prevents ACS.' },
        { text: 'Surgeon is exhausted and will return tomorrow', exp: 'Damage control is a deliberate strategy, not a fatigue accommodation.' },
        { text: 'To allow for second-look exploration only', exp: 'Second look is part of it but the primary driver is preventing ACS in a swollen, edematous abdomen.' },
      ],
      correct: 1,
      exp: 'Damage control surgery: abbreviated initial operation to stop bleeding and contamination. Resuscitation in ICU corrects lethal triad (hypothermia, acidosis, coagulopathy). Return to OR at 24-48h for definitive repair. Open abdomen with temporary closure prevents abdominal compartment syndrome from bowel edema after massive resuscitation.',
      difficulty: 8,
      tags: ['damage-control'],
    },
    {
      id: 'tr-23',
      q: 'Trauma patient receiving 6L of NS over 90 minutes during resuscitation. New bladder pressure 28 mmHg, BP 95/68, RR 24, peak airway pressures rising. Urine output dropped to 5 mL/hr. Diagnosis?',
      choices: [
        { text: 'Acute kidney injury from hypotension', exp: 'AKI from hypotension is a concern but the rising bladder pressure, climbing airway pressures, and pattern suggest something else mechanically driven.' },
        { text: 'Abdominal compartment syndrome', exp: 'Correct. Intraabdominal pressure over 20-25 mmHg with new organ dysfunction = abdominal compartment syndrome. Causes: massive resuscitation (over-crystalloid), bowel edema, abdominal trauma, retroperitoneal hematoma. Effects: kidney (oliguria), lung (high airway pressures, hypoxia), gut (ischemia), brain (raised ICP from impaired venous return). Treatment: decompressive laparotomy.' },
        { text: 'Pulmonary embolism', exp: 'PE doesnt cause rising bladder pressure or oliguria. Different presentation.' },
        { text: 'Ventilator-associated pneumonia', exp: 'Too early after resuscitation, doesnt explain bladder pressure or oliguria.' },
      ],
      correct: 1,
      exp: 'Abdominal compartment syndrome: intraabdominal pressure over 20-25 with organ dysfunction. Massive crystalloid resuscitation is a top cause. Effects: oliguria (kidney compression), high airway pressures (diaphragm pushed up), hypotension (IVC compression). Decompressive laparotomy. Prevention: damage control resuscitation with blood products, less crystalloid.',
      difficulty: 9,
      tags: ['acs', 'over-resuscitation'],
    },
    {
      id: 'tr-24',
      q: 'Multi-system trauma patient receiving uncrossmatched O-negative blood. Develops fever 39.5C, hypotension, hemoglobinuria 30 minutes into transfusion. Most likely reaction?',
      choices: [
        { text: 'Febrile non-hemolytic transfusion reaction', exp: 'Fever and chills only, no hemolysis. Hemoglobinuria points to something more serious.' },
        { text: 'Acute hemolytic transfusion reaction (ABO incompatibility)', exp: 'Correct. Fever, hypotension, hemoglobinuria 30 minutes into transfusion = ABO mismatch. Even O-negative blood can cause acute hemolytic reactions if patient has unusual antibodies. STOP the transfusion immediately. Maintain renal perfusion (crystalloid), alkalinize urine, support BP. Send unit and patient blood back to blood bank for workup.' },
        { text: 'TRALI (transfusion-related acute lung injury)', exp: 'TRALI presents as hypoxia and pulmonary edema within 6 hours. No primary hypoxia or pulmonary symptoms here.' },
        { text: 'TACO (transfusion-associated circulatory overload)', exp: 'TACO is volume overload - hypertension and pulmonary edema, not hypotension and hemolysis.' },
      ],
      correct: 1,
      exp: 'Acute hemolytic reaction: fever, hypotension, hemoglobinuria, back/chest pain, DIC. Stop the transfusion immediately. Send unit and labs back to blood bank. Support BP, maintain urine output (myoglobin/hemoglobin clears via kidneys). Most fatal transfusion reaction. Even O-neg can do it with rare antibodies.',
      difficulty: 8,
      tags: ['transfusion-reaction'],
    },
    {
      id: 'tr-25',
      q: '4-year-old, 16 kg, fall from second-story window. GCS 12, BP 76/48, HR 158. Tachypneic, capillary refill 4 seconds, mottled extremities. After 20 mL/kg NS bolus, vitals unchanged. Next step?',
      choices: [
        { text: 'Repeat 20 mL/kg crystalloid bolus, then reassess', exp: 'After one bolus without response, the next intervention is blood, not more crystalloid. PALS allows up to 3 boluses but trauma protocols call for blood after first or second non-response - too much crystalloid worsens coagulopathy.' },
        { text: '10 mL/kg PRBC and activate massive transfusion if available, plus pelvis/abdomen evaluation', exp: 'Correct. Pediatric hemorrhagic shock not responsive to one fluid bolus needs blood. 10-20 mL/kg PRBC. Look for the source (FAST, CT chest/abdomen/pelvis depending on stability). Pediatric massive transfusion ratio is similar adult 1:1:1 by volume. Pediatric tachycardia is a strong early sign - kids compensate longer than adults then crash hard.' },
        { text: 'Vasopressor drip (norepinephrine) for hypotension', exp: 'Vasopressors in hemorrhagic shock raise BP without addressing the volume deficit and worsen end-organ perfusion. Address volume/blood first.' },
        { text: 'CT scan in stable position', exp: 'Hypotensive trauma patient unresponsive to fluids does not go to CT. Goes to OR or for blood.' },
      ],
      correct: 1,
      exp: 'Pediatric trauma: kids compensate longer (HR up early, BP late) then decompensate fast. After 1-2 fluid boluses without response, switch to blood. Massive transfusion in peds: 10 mL/kg of each component. Always look for the source - pelvis, abdomen, chest, long bones, scalp lacerations (in infants). Hypotension in a child is LATE and ominous.',
      difficulty: 8,
      tags: ['pediatric-trauma', 'hemorrhagic-shock'],
    },
  ],
}
